// Compliance module: obligations register, built-in regulatory library, cross-framework crosswalk, regulatory change.
(function(){
const G=window.GRC,LIB=window.GRC_LIB,P=G.P;if(!G||!LIB)return;
const {E,fmt,addDays,dTo,pill,own,table,card,kpi,bar,toolbar,flt,match,lk,toast,logIt,commit,openDrawer,openForm,actions,TODAY,detail,dueState,csv,head,panel,personOpts,raise}=G;
const S=()=>G.S(),FW=id=>LIB.frameworks.find(f=>f.id===id),TH=LIB.themes;
const compK={Compliant:'green','Partially compliant':'amber','Non-compliant':'red','Not assessed':'blue','Not applicable':'blue'};
const STAT=Object.keys(compK);
const FWTAGS={dpdp:['DPDP'],gdpr:['GDPR'],dora:['DORA'],'rbi-itgrc':['RBI ITGRC'],'rbi-outsourcing':['RBI Outsourcing'],'rbi-kyc':['RBI KYC'],pmla:['PMLA','FATF'],'sebi-cscrf':['CSCRF'],'nist-csf2':['NIST CSF'],iso27001:['ISO 27001'],'rbi-csf':['RBI CSF'],certin:['CERT-In'],fatf:['FATF'],soc2:['SOC 2'],sox:['SOX'],iso22301:['ISO 22301'],'rbi-fraud':['RBI Fraud'],'sebi-lodr':['SEBI']};
const THKEY={PRIV:/consent|breach|privacy|data|request/i,SEC:/access|vulnerab|SOC|patch|change|endpoint/i,INC:/incident|SOC|breach|response/i,TPR:/third|vendor|supplier|due diligence|exit/i,RES:/BCP|continuity|backup|recovery|failover|DR/i,FC:/KYC|monitor|fraud|alert/i,TEST:/test|review|validation/i,RISK:/risk|review|limits/i,GOV:/policy|approval|review/i,DISC:/return|report|record/i,CONDUCT:/product|suitability|complaint|disclosure|consent/i,AI:/model|validation/i};
const obls=()=>S().obl||[],obl=id=>obls().find(o=>o.id===id);
// ---------------------------------------------------------------- seeds
function pickControls(fwId,theme){const cs=S().controls||[],tags=FWTAGS[fwId]||[];const cand=cs.filter(c=>c.fw.some(t=>tags.includes(t)));const key=THKEY[theme];let hit=cand.filter(c=>key&&key.test(c.name));if(!hit.length)hit=cs.filter(c=>key&&key.test(c.name));return hit.slice(0,2).map(c=>c.id)}
function makeObl(fwId,o,i,n,owners,assess){const th=o[3];const o2={id:'OB-'+String(n).padStart(3,'0'),fw:fwId,ref:o[0],title:o[1],req:o[2],theme:th,owner:owners[th]||'Morgan Chen',status:'Not assessed',controls:[],evidence:'',last:'',next:addDays(TODAY,45+(i*7)%120),notes:''};
 if(assess){const pat=['Compliant','Compliant','Compliant','Partially compliant','Compliant','Not assessed','Compliant','Non-compliant','Compliant','Partially compliant','Compliant','Compliant'];let st=pat[(n*5+i)%pat.length];o2.status=st;o2.controls=pickControls(fwId,th);if(st==='Compliant'&&!o2.controls.length)o2.status=st='Partially compliant';if(st!=='Not assessed'){o2.last=addDays(TODAY,-20-(i*11)%80);o2.next=addDays(o2.last,180);if(st==='Compliant')o2.evidence='Control test result and policy attestation on file'}
  if(i%9===4)o2.next=addDays(TODAY,-6-(i%5))}
 return o2}
G.seeders.obl=()=>{const out=[];let n=1;(P.adopt||[]).forEach(id=>{const f=FW(id);if(!f)return;f.obl.forEach((o,i)=>out.push(makeObl(id,o,i,n++,P.owners||{},true)))});return out};
const ST0=['New','Under assessment','Action plan','Implemented','Not applicable'];
const RCS={
 bfsi:[['RC-001','RBI revised KYC periodic-updation timelines (illustrative)','RBI','Circular','2026-09-02','2027-01-01','High','Action plan','Jordan Lee','rbi-kyc','Review interval and re-KYC process for all customer risk bands; update systems and policy.'],
  ['RC-002','RBI direction on cyber incident reporting channel and format (illustrative)','RBI','Circular','2026-09-20','2026-11-15','High','Under assessment','Sam Rivera','rbi-itgrc','New reporting template and portal for cyber incidents; align internal 6-hour clock and runbooks.'],
  ['RC-003','SEBI clarification on CSCRF audit submission timelines (illustrative)','SEBI','Circular','2026-09-28','2026-12-31','Medium','New','Sam Rivera','sebi-cscrf','Updated windows for cyber audit report submission and compliance certification.'],
  ['RC-004','DPDP Rules phase-in: next set of obligations (illustrative)','MeitY','Notification','2026-08-14','2027-05-01','High','Action plan','Priya Shah','dpdp','Consent manager interface, notice content and children’s data controls come into force; plan system changes.'],
  ['RC-005','EU RTS on register of information update (illustrative)','ESAs','Consultation','2026-10-01','2027-01-15','Medium','New','Sam Rivera','dora','Data-point changes to the register of information and submission calendar.'],
  ['RC-006','RBI amendments to digital lending disclosures (illustrative)','RBI','Circular','2026-07-10','2026-10-20','Medium','Implemented','Evan Brooks','','KFS template and APR disclosure update, completed and tested.']],
 general:[['RC-001','Updated privacy law guidance on breach notice content (illustrative)','Regulator','Notification','2026-09-12','2026-12-01','Medium','Under assessment','Priya Shah','gdpr','Notice content and timeline expectations for reportable breaches.'],
  ['RC-002','Customer contract clause change for supplier security (illustrative)','Industry body','Consultation','2026-09-25','2027-02-01','Low','New','Evan Brooks','','Proposed contractual security schedule for suppliers.'],
  ['RC-003','Revised sustainability disclosure requirements (illustrative)','Regulator','Circular','2026-08-05','2026-12-31','Medium','Action plan','Morgan Chen','','Scope changes to annual sustainability reporting.']],
 manufacturing:[['RC-001','CERT-In advisory update on log retention (illustrative)','CERT-In','Notification','2026-09-18','2026-12-01','Medium','Under assessment','Sam Rivera','certin','Clarification on log scope and retention location.'],
  ['RC-002','DPDP Rules phase-in: next obligations (illustrative)','MeitY','Notification','2026-08-14','2027-05-01','High','Action plan','Priya Shah','dpdp','Employee and vendor data notices and consent flows.'],
  ['RC-003','Pollution control board amendment to consent conditions (illustrative)','State PCB','Notification','2026-09-01','2026-11-30','Medium','New','Priya Shah','','Updated discharge monitoring and reporting conditions.']]};
G.seeders.regchg=pid=>(RCS[pid]||RCS.general).map(r=>({id:r[0],title:r[1],source:r[2],type:r[3],published:r[4],effective:r[5],impact:r[6],status:r[7],owner:r[8],fw:r[9],summary:r[10],obligations:[],notes:''}));
// ---------------------------------------------------------------- views
const GROUP='COMPLIANCE & PRIVACY';
G.mount({id:'obligations',label:'Obligations',ico:'☑',group:GROUP,title:'Compliance obligations',sub:'Regulatory and framework obligations broken down to what must be done, who owns it, which control covers it and what evidence proves it. Adopt frameworks from Standards & data, assess each requirement and track gaps to closure.',tabs:[['register','Obligations register'],['crosswalk','Cross-framework crosswalk']]});
G.mount({id:'regchange',label:'Regulatory change',ico:'⟳',group:GROUP,title:'Regulatory change management',sub:'Log new circulars, notifications and amendments, assess impact, assign owners and link the obligations and actions they change.',tabs:[['register','Change register']]});
const gap=o=>o.status==='Non-compliant'||o.status==='Partially compliant';
function renderObligations(){
 const all=obls(),sc=all.filter(o=>o.status!=='Not applicable'),comp=sc.filter(o=>o.status==='Compliant').length,pct=sc.length?Math.round(comp/sc.length*100):0;
 const gaps=sc.filter(gap).length,na=sc.filter(o=>o.status==='Not assessed').length,due=sc.filter(o=>o.next&&dTo(o.next)<=30).length;
 head('obligations','<button class="btn" data-op="obl-export"><span class="btnico">↓</span>Export register</button><button class="btn" data-op="obl-new"><span class="btnico">＋</span>Add obligation</button><button class="btn primary" data-op="obl-tab" data-tab="library"><span class="btnico">＋</span>Adopt framework</button>');
 const f=flt('obligations','reg'),fws=[...new Set(all.map(o=>o.fw))];
 const rows=all.filter(o=>match(f,[o.id,o.title,o.ref,o.req,o.owner,(FW(o.fw)||{}).code].join(' '))&&(!f.fw||f.fw==='All'||(FW(o.fw)||{}).code===f.fw)&&(!f.st||f.st==='All'||o.status===f.st)&&(!f.th||f.th==='All'||TH[o.theme]===f.th)).map(o=>{const fw=FW(o.fw)||{code:o.fw};return `<tr data-op="open" data-t="obligation" data-id="${o.id}"><td class="riskid">${o.id}</td><td><span class="badgepill pill-blue">${E(fw.code)}</span><div class="riskarea">${E(o.ref)}</div></td><td><div class="riskname">${E(o.title)}</div><div class="riskarea">${E(TH[o.theme]||'')}</div></td><td>${own(o.owner)}</td><td>${pill(o.status,compK[o.status])}</td><td>${o.controls.length?o.controls.length+' mapped':'<span class="badgepill pill-red">none</span>'}</td><td>${o.next?fmt(o.next):'—'}${o.next&&dTo(o.next)<0?' <span class="badgepill pill-red">overdue</span>':''}</td></tr>`});
 panel('obligations','register').innerHTML=`<div class="op-kpis">${kpi('Obligations in scope',sc.length,`${fws.length} framework${fws.length===1?'':'s'} adopted`)}${kpi('Compliant',pct+'%',`${comp} of ${sc.length} requirements`,pct>=85?'ok':'')}${kpi('Gaps',gaps,'partially or non-compliant',gaps?'warn':'ok')}${kpi('Not yet assessed',na,`${due} review${due===1?'':'s'} due in 30 days`,na?'warn':'ok')}</div>
 ${all.length?toolbar('obligations','reg','Search obligations, owners, requirements…',[['fw',['All',...[...new Set(all.map(o=>(FW(o.fw)||{code:o.fw}).code))],],'All frameworks'],['st',['All',...STAT],'All statuses'],['th',['All',...Object.values(TH)],'All themes']])+card('Obligations register',`${rows.length} of ${all.length} shown · click a row for the full record`,table(['ID','Framework','Obligation','Owner','Status','Controls','Next review'],rows,'No obligations match.')):card('No frameworks adopted yet','Choose a framework from the library','<div style="padding:0 18px 18px"><p class="op-note">Open <b>Standards & data</b> and adopt the regulations and standards that apply to you. Each requirement becomes a trackable obligation.</p></div>')}`;
 // crosswalk
 const rowsT=Object.entries(TH).map(([k,label])=>{const inT=all.filter(o=>o.theme===k),fwSet=new Set(inT.map(o=>o.fw)),cs=new Set(inT.flatMap(o=>o.controls)),cp=inT.length?Math.round(inT.filter(o=>o.status==='Compliant').length/inT.length*100):0;return `<tr data-op="open" data-t="theme" data-id="${k}"><td><div class="riskname">${E(label)}</div></td><td>${inT.length}</td><td>${fwSet.size}</td><td>${cs.size}</td><td style="min-width:120px">${inT.length?bar(cp,cp>=85?'':cp>=60?'amber':'red'):''}</td><td>${inT.length?cp+'%':'–'}</td><td>${inT.filter(o=>!o.controls.length&&o.status!=='Not applicable').length||'–'}</td></tr>`});
 panel('obligations','crosswalk').innerHTML=`<p class="op-note" style="margin:0 0 10px">Every requirement is tagged to a common theme. Where several frameworks ask for the same thing (for example incident reporting under DPDP, DORA, RBI and SEBI), one well-designed control and one evidence set can serve them all. Click a theme to see the obligations from every framework side by side.</p>${card('Theme crosswalk','Obligations, frameworks and controls per theme',table(['Theme','Obligations','Frameworks','Controls used','Coverage','Compliant','No control'],rowsT))}`;
}
G.renders.push(renderObligations);
function renderRegChange(){
 const all=S().regchg||[],open=all.filter(r=>r.status!=='Implemented'&&r.status!=='Not applicable');
 const late=open.filter(r=>r.status==='New'&&dTo(addDays(r.published,14))<0),soon=open.filter(r=>dTo(r.effective)<=90),hi=open.filter(r=>r.impact==='High');
 head('regchange','<button class="btn primary" data-op="rc-new"><span class="btnico">＋</span>Log regulatory change</button>');
 const f=flt('regchange','reg');
 const rows=all.filter(r=>match(f,[r.id,r.title,r.source,r.owner].join(' '))&&(!f.st||f.st==='All'||r.status===f.st)).sort((a,b)=>a.effective<b.effective?-1:1).map(r=>`<tr data-op="open" data-t="regchange" data-id="${r.id}"><td class="riskid">${r.id}</td><td><div class="riskname">${E(r.title)}</div><div class="riskarea">${E(r.source)} · ${E(r.type)} · published ${fmt(r.published)}</div></td><td>${pill(r.impact,r.impact==='High'?'red':r.impact==='Medium'?'amber':'green')}</td><td>${own(r.owner)}</td><td>${fmt(r.effective)}</td><td>${pill(r.status,r.status==='Implemented'?'green':r.status==='New'?'blue':'amber')}</td></tr>`);
 panel('regchange','register').innerHTML=`<div class="op-kpis">${kpi('Open changes',open.length,'not yet implemented')}${kpi('High impact',hi.length,'need an action plan',hi.length?'warn':'ok')}${kpi('Assessment overdue',late.length,'new for more than 14 days',late.length?'warn':'ok')}${kpi('Effective within 90 days',soon.length,'plan delivery now',soon.length?'warn':'ok')}</div>${toolbar('regchange','reg','Search changes, regulators, owners…',[['st',['All',...ST0],'All statuses']])}${card('Regulatory change register','Titles marked illustrative are sample entries',table(['ID','Change','Impact','Owner','Effective','Status'],rows,'No changes logged.'))}`;
 G.setBadge('regchange',late.length);
}
G.renders.push(renderRegChange);
// ---------------------------------------------------------------- drawers
const fwCode=id=>(FW(id)||{code:id||'Internal'}).code;
G.drawers.obligation=id=>{const o=obl(id);if(!o)return;const f=FW(o.fw)||{},cs=o.controls.map(c=>S().controls.find(x=>x.id===c)).filter(Boolean),iss=S().issues.filter(i=>i.link===o.id),open=iss.filter(i=>i.status!=='Closed'),P2=[];
 if(o.status==='Non-compliant')P2.push(['red','Marked <b>non-compliant</b>.'+(open.length?'':' No issue is tracking remediation.')]);
 if(o.status==='Partially compliant')P2.push(['amber','Marked <b>partially compliant</b>. Record what is missing and who closes it.']);
 if(o.status==='Not assessed')P2.push(['amber','Not yet assessed against current controls and evidence.']);
 if(o.status!=='Not applicable'&&!cs.length)P2.push(['amber','<b>No control is mapped</b> to this requirement.']);
 cs.filter(c=>c.result==='Ineffective').forEach(c=>P2.push(['red',`Mapped control <b>${E(c.id)}</b> failed its last test.`]));
 if(o.status==='Compliant'&&!o.evidence)P2.push(['amber','Compliant, but no evidence reference is recorded.']);
 const ds=o.next&&o.status!=='Not applicable'?dueState(o.next,30):null;if(ds)P2.push([ds[0],`Next review ${ds[1]}.`]);
 open.forEach(i=>P2.push(['amber',`Open issue ${i.id}: ${E(i.title)} (${E(i.owner)}, due ${fmt(i.due)}).`]));
 const todo=[];if(o.status==='Not assessed')todo.push('Assess the requirement against current controls and evidence and record the result.');
 if(!cs.length&&o.status!=='Not applicable')todo.push('Map one or more controls (or create one) that meet this requirement.');
 if(gap(o)&&!open.length)todo.push('Raise an issue with an owner, due date and corrective actions.');
 if(o.status==='Compliant')todo.push('Keep evidence current and re-review before the next review date.');
 todo.push(`${E(o.owner)} to confirm applicability and sign off at each review.`);
 const sameTheme=obls().filter(x=>x.theme===o.theme&&x.id!==o.id).slice(0,6);
 detail({kicker:'Obligation · '+o.id,title:o.title,pending:P2,ok:'Assessed, controlled and evidenced.',todo,
  facts:[['Framework',E(f.code||o.fw)],['Reference',E(o.ref)],['Theme',E(TH[o.theme]||'')],['Owner',E(o.owner)],['Status',pill(o.status,compK[o.status])],['Last reviewed',o.last?fmt(o.last):'—'],['Next review',o.next?fmt(o.next):'—'],['Controls mapped',String(cs.length)]],
  buttons:`<button class="op-mini p" data-op="obl-assess" data-id="${o.id}">Assess / update</button><button class="op-mini" data-op="obl-link" data-id="${o.id}">Map control</button>${gap(o)&&!open.length?`<button class="op-mini r" data-op="obl-issue" data-id="${o.id}">Raise issue</button>`:''}<button class="op-mini g" data-op="obl-review" data-id="${o.id}">Mark reviewed</button>`,
  extra:`<h4>What the requirement says</h4><p class="op-note" style="font-size:11px;color:#475569;margin-top:0">${E(o.req)}</p>${o.evidence?`<h4>Evidence</h4><p class="op-note" style="font-size:11px;color:#475569;margin-top:0">${E(o.evidence)}</p>`:''}${o.notes?`<h4>Notes</h4><p class="op-note" style="font-size:11px;color:#475569;margin-top:0">${E(o.notes)}</p>`:''}${f.verify?`<p class="op-note">⚠ ${E(f.verify)}</p>`:''}`,
  links:[...cs.map(c=>c.id),...iss.map(i=>i.id),...sameTheme.map(x=>x.id)]})};
G.drawers.fw=id=>{const f=FW(id);if(!f)return;const mine=obls().filter(o=>o.fw===id),a=mine.length>0;
 G.setDrawer(f.kind+' · '+f.region,f.code,`<p style="font-size:11px;line-height:1.6;color:#475569;margin-top:0">${E(f.name)}<br>${E(f.summary)}</p>${f.verify?`<div class="op-banner amber"><div><b>Verify before relying on this</b><div>${E(f.verify)}</div></div></div>`:''}<div class="op-btns">${a?'':`<button class="op-mini p" data-op="obl-adopt" data-fw="${f.id}">Adopt this framework (${f.obl.length} obligations)</button>`}<button class="op-mini" data-op="fw-export" data-id="${f.id}">↓ Export requirements</button></div>
  <h4>Requirements (${f.obl.length})</h4>${table(['Ref','Requirement','Theme',a?'Status':''],f.obl.map(o=>{const m=mine.find(x=>x.ref===o[0]&&x.title===o[1]);return `<tr ${m?`data-op="open" data-t="obligation" data-id="${m.id}"`:'style="cursor:default"'}><td class="riskid" style="white-space:normal">${E(o[0])}</td><td style="white-space:normal"><div class="riskname">${E(o[1])}</div><div class="riskarea" style="white-space:normal;line-height:1.5">${E(o[2])}</div></td><td style="white-space:normal">${E(TH[o[3]])}</td><td>${m?pill(m.status,compK[m.status]):''}</td></tr>`}))}`)};
G.drawers.theme=k=>{const rows=obls().filter(o=>o.theme===k);G.setDrawer('Crosswalk',TH[k],`<p class="op-note" style="margin-top:0">The same theme across every adopted framework. A control that serves one row can often serve several.</p>${rows.length?table(['Framework','Ref','Obligation','Status','Controls'],rows.map(o=>`<tr data-op="open" data-t="obligation" data-id="${o.id}"><td><span class="badgepill pill-blue">${E(fwCode(o.fw))}</span></td><td class="riskid">${E(o.ref)}</td><td style="white-space:normal">${E(o.title)}</td><td>${pill(o.status,compK[o.status])}</td><td>${o.controls.join(', ')||'<span class="badgepill pill-red">none</span>'}</td></tr>`)):'<p class="op-note">No adopted obligations in this theme.</p>'}`)};
G.drawers.regchange=id=>{const r=(S().regchg||[]).find(x=>x.id===id);if(!r)return;const P2=[],due=addDays(r.published,14);
 if(r.status==='New'){const ds=dueState(due,7);P2.push(ds?[ds[0],`Impact assessment ${ds[1]}.`]:['amber','Impact assessment has not started.'])}
 if(r.status!=='Implemented'&&r.status!=='Not applicable'){const ds=dueState(r.effective,90);if(ds)P2.push([ds[0],`Effective date ${ds[1]}.`]);if(!r.obligations.length)P2.push(['amber','No affected obligation is linked yet.'])}
 const todo=['Assess which obligations, controls, policies and systems change.','Link the affected obligations and confirm their owners.','Create an action plan with dated tasks before the effective date.','Update policy, procedures, training and evidence; mark implemented once tested.'];
 detail({kicker:'Regulatory change · '+r.id,title:r.title,pending:P2,ok:'Implemented or not applicable.',todo,facts:[['Source',E(r.source)],['Type',E(r.type)],['Published',fmt(r.published)],['Effective',fmt(r.effective)],['Impact',pill(r.impact,r.impact==='High'?'red':r.impact==='Medium'?'amber':'green')],['Owner',E(r.owner)],['Status',E(r.status)],['Framework',E(fwCode(r.fw))]],
  buttons:`<button class="op-mini p" data-op="rc-assess" data-id="${r.id}">Assess / update</button><button class="op-mini" data-op="rc-link" data-id="${r.id}">Link obligation</button><button class="op-mini r" data-op="rc-issue" data-id="${r.id}">Create action plan</button>`,
  extra:`<h4>Summary</h4><p class="op-note" style="font-size:11px;color:#475569;margin-top:0">${E(r.summary)}</p>${r.notes?`<h4>Notes</h4><p class="op-note" style="font-size:11px;color:#475569;margin-top:0">${E(r.notes)}</p>`:''}`,
  links:[...r.obligations,...S().issues.filter(i=>i.link===r.id).map(i=>i.id)]})};
G.linkers.push(id=>{const o=obl(id);if(o)return{type:'obligation',label:`${o.id} · ${o.title}`};const r=(S().regchg||[]).find(x=>x.id===id);return r?{type:'regchange',label:`${r.id} · ${r.title}`}:null});
// ---------------------------------------------------------------- actions
const nextObl=()=>obls().reduce((m,o)=>Math.max(m,+o.id.slice(3)),0)+1;
Object.assign(actions,{
 'obl-tab':b=>{actions.tab({dataset:{view:'obligations',tab:b.dataset.tab}})},
 'obl-adopt':b=>{const f=FW(b.dataset.fw),s=S();if(!f)return;if(obls().some(o=>o.fw===f.id)){toast(f.code+' is already adopted.');return}let n=nextObl();f.obl.forEach((o,i)=>s.obl.push(makeObl(f.id,o,i,n++,P.owners||{},false)));logIt(f.id,`Framework adopted: ${f.code} (${f.obl.length} obligations).`);commit();G.closeDrawer();toast(`${f.code} adopted: ${f.obl.length} obligations added to the register. Assess each one.`)},
 'obl-assess':b=>{const o=obl(b.dataset.id);openForm('Assess · '+o.id,[{name:'status',label:'Compliance status',type:'select',options:STAT,value:o.status},{name:'owner',label:'Owner',type:'select',options:personOpts(),value:o.owner},{name:'evidence',label:'Evidence reference',full:true,ph:'e.g. Control test CT-107, policy POL-004 v2.0, system report',value:o.evidence},{name:'notes',label:'Assessment notes / gap description',type:'textarea',full:true,value:o.notes},{name:'next',label:'Next review date',type:'date',value:o.next||addDays(TODAY,180)}],'Save assessment',v=>{o.status=v.status;o.owner=v.owner;o.evidence=v.evidence;o.notes=v.notes;o.next=v.next;o.last=TODAY;logIt(o.id,`Assessed as ${v.status}.`);commit()})},
 'obl-link':b=>{const o=obl(b.dataset.id),cs=S().controls.filter(c=>!o.controls.includes(c.id));openForm('Map control · '+o.id,[{name:'ctrl',label:'Control',type:'select',full:true,options:cs.map(c=>[c.id,`${c.id} · ${c.name} (${c.result})`])}],'Map control',v=>{if(!v.ctrl)return 'Select a control.';o.controls.push(v.ctrl);logIt(o.id,`Control ${v.ctrl} mapped.`);commit()})},
 'obl-issue':b=>{const o=obl(b.dataset.id);raise('Compliance obligation',o.id,`${fwCode(o.fw)} ${o.ref}: ${o.title}`,o.status==='Non-compliant'?'High':'Medium',o.owner,`Obligation is ${o.status.toLowerCase()}. ${o.req}`,'Control design');commit()},
 'obl-review':b=>{const o=obl(b.dataset.id);o.last=TODAY;o.next=addDays(TODAY,180);logIt(o.id,'Reviewed; next review in 180 days.');commit();toast(o.id+' marked reviewed.')},
 'obl-new':()=>openForm('Add obligation',[{name:'title',label:'Obligation / requirement',full:true},{name:'src',label:'Source (law, regulator, internal policy, contract)',ph:'e.g. Internal policy, Customer contract'},{name:'ref',label:'Reference',ph:'e.g. Clause 4.2'},{name:'theme',label:'Theme',type:'select',options:Object.entries(TH)},{name:'owner',label:'Owner',type:'select',options:personOpts(),value:G.me().name},{name:'req',label:'What it requires',type:'textarea',full:true}],'Add obligation',v=>{if(!v.title)return 'Add the obligation.';const n=nextObl();S().obl.push({id:'OB-'+String(n).padStart(3,'0'),fw:'',ref:v.ref||'—',title:v.title,req:v.req||v.title,theme:v.theme,owner:v.owner,status:'Not assessed',controls:[],evidence:'',last:'',next:addDays(TODAY,60),notes:v.src?'Source: '+v.src:''});commit()}),
 'obl-export':()=>csv('forge-obligations.csv',[['ID','Framework','Reference','Obligation','Theme','Owner','Status','Controls','Last reviewed','Next review'],...obls().map(o=>[o.id,fwCode(o.fw),o.ref,o.title,TH[o.theme],o.owner,o.status,o.controls.join('|'),o.last,o.next])],'Obligations exported as CSV.'),
 'fw-export':b=>{const f=FW(b.dataset.id);csv('forge-'+f.id+'-requirements.csv',[['Reference','Requirement','Detail','Theme'],...f.obl.map(o=>[o[0],o[1],o[2],TH[o[3]]])],f.code+' requirements exported.')},
 'rc-new':()=>openForm('Log regulatory change',[{name:'title',label:'Title',full:true},{name:'source',label:'Regulator / source',ph:'e.g. RBI, SEBI, MeitY, EU Commission'},{name:'type',label:'Type',type:'select',options:['Circular','Notification','Amendment','Consultation','Guidance']},{name:'published',label:'Published',type:'date',value:TODAY},{name:'effective',label:'Effective from',type:'date',value:addDays(TODAY,120)},{name:'impact',label:'Initial impact',type:'select',options:['High','Medium','Low'],value:'Medium'},{name:'owner',label:'Owner',type:'select',options:personOpts(),value:G.me().name},{name:'fw',label:'Related framework',type:'select',options:[['','— none —'],...LIB.frameworks.map(f=>[f.id,f.code])]},{name:'summary',label:'Summary of the change',type:'textarea',full:true}],'Log change',v=>{if(!v.title)return 'Add a title.';const rc=S().regchg;rc.push({id:'RC-'+String(rc.reduce((m,r)=>Math.max(m,+r.id.slice(3)),0)+1).padStart(3,'0'),title:v.title,source:v.source||'Regulator',type:v.type,published:v.published,effective:v.effective,impact:v.impact,status:'New',owner:v.owner,fw:v.fw,summary:v.summary||'',obligations:[],notes:''});commit()}),
 'rc-assess':b=>{const r=S().regchg.find(x=>x.id===b.dataset.id);openForm('Assess · '+r.id,[{name:'impact',label:'Impact',type:'select',options:['High','Medium','Low'],value:r.impact},{name:'status',label:'Status',type:'select',options:ST0,value:r.status},{name:'owner',label:'Owner',type:'select',options:personOpts(),value:r.owner},{name:'notes',label:'Impact assessment notes',type:'textarea',full:true,value:r.notes}],'Save',v=>{Object.assign(r,{impact:v.impact,status:v.status,owner:v.owner,notes:v.notes});logIt(r.id,`Updated: ${v.status}, ${v.impact} impact.`);commit()})},
 'rc-link':b=>{const r=S().regchg.find(x=>x.id===b.dataset.id),cand=obls().filter(o=>!r.obligations.includes(o.id)&&(!r.fw||o.fw===r.fw));openForm('Link obligation · '+r.id,[{name:'ob',label:'Affected obligation',type:'select',full:true,options:cand.map(o=>[o.id,`${o.id} · ${fwCode(o.fw)} ${o.ref} · ${o.title}`])}],'Link',v=>{if(!v.ob)return 'Select an obligation.';r.obligations.push(v.ob);logIt(r.id,`Linked ${v.ob}.`);commit()})},
 'rc-issue':b=>{const r=S().regchg.find(x=>x.id===b.dataset.id);raise('Regulatory change',r.id,`Implement: ${r.title}`,r.impact==='High'?'High':'Medium',r.owner,r.summary,'To be determined');if(r.status==='New'||r.status==='Under assessment')r.status='Action plan';commit()}
});
G.xTiles.push(()=>{const all=obls().filter(o=>o.status!=='Not applicable');if(!all.length)return null;const g=all.filter(o=>o.status==='Non-compliant'),pa=all.filter(o=>o.status==='Partially compliant'),pct=Math.round(all.filter(o=>o.status==='Compliant').length/all.length*100);return{key:'obl-gap',l:'Obligations compliant',v:pct+'%',f:`${g.length} non-compliant · ${pa.length} partial · ${all.filter(o=>o.status==='Not assessed').length} not assessed`,k:g.length>3||pct<70?'red':g.length||pct<90?'amber':'green',ic:'☑'}});
G.xTiles.push(()=>{const rc=(S().regchg||[]).filter(r=>r.status!=='Implemented'&&r.status!=='Not applicable');if(!(S().regchg||[]).length)return null;const hi=rc.filter(r=>r.impact==='High');return{key:'rc-open',l:'Regulatory changes open',v:rc.length,f:`${hi.length} high impact · ${rc.filter(r=>dTo(r.effective)<=90).length} effective within 90 days`,k:hi.length>1?'red':rc.length?'amber':'green',ic:'⟳'}});
const ob2r=o=>({id:o.id,sub:`${fwCode(o.fw)} ${o.ref} · ${o.owner} · ${o.controls.length?o.controls.length+' control(s)':'no control'}`,pill:pill(o.status,compK[o.status])});
G.metrics['obl-gap']=()=>['Compliance','Obligations needing attention','Non-compliant, partially compliant and not-yet-assessed requirements, worst first.',obls().filter(o=>['Non-compliant','Partially compliant','Not assessed'].includes(o.status)).sort((a,b)=>STAT.indexOf(b.status)<STAT.indexOf(a.status)?1:-1).map(ob2r)];
G.metrics['rc-open']=()=>['Regulation','Open regulatory changes','Sorted by effective date.',(S().regchg||[]).filter(r=>r.status!=='Implemented'&&r.status!=='Not applicable').sort((a,b)=>a.effective<b.effective?-1:1).map(r=>({id:r.id,sub:`${r.source} · effective ${fmt(r.effective)} · ${r.owner}`,pill:pill(r.status,'amber')}))];
G.renderAll();
})();
