// Risk & Control Self-Assessment (RCSA): campaigns, first-line self-assessments of risks and controls,
// second-line review and challenge, results against the register, and applying agreed ratings.
(function(){
const G=window.GRC;if(!G)return;
const {E,fmt,addDays,dTo,pill,own,table,card,kpi,bar,toolbar,flt,match,toast,logIt,commit,openForm,actions,TODAY,detail,dueState,csv,head,panel,personOpts,raise,me,risks,heatCol,riskLI}=G;
const S=()=>G.S(),R=()=>S().rcsa2||{camps:[],items:[],applied:{}};
const LAB=['','1 · Rare / negligible','2 · Unlikely / minor','3 · Possible / moderate','4 · Likely / major','5 · Almost certain / severe'];
const LLAB=['','1 · Rare','2 · Unlikely','3 · Possible','4 · Likely','5 · Almost certain'],ILAB=['','1 · Insignificant','2 · Minor','3 · Moderate','4 · Major','5 · Severe'];
const rate=sc=>{try{return scoresToRating(sc)}catch{return sc>=20?'Critical':sc>=15?'High':sc>=8?'Medium':'Low'}};
const sc=a=>a?a[0]*a[1]:0;
const can2=()=>me().role==='Administrator';
const rk=id=>risks.find(r=>r.id===id)||{id,name:id,area:'',owner:'',score:0};
const ctrlsOf=id=>S().controls.filter(c=>c.risks.includes(id));
const CST={'Not started':'blue','Sent back':'amber',Submitted:'amber',Agreed:'green',Overridden:'red'};
const RK={Effective:'green','Partially effective':'amber',Ineffective:'red','Not assessed':'blue'};
// ---------------------------------------------------------------- seed
G.seeders.rcsa2=()=>{
 const li=r=>riskLI(r,'residual'),items=[];
 const mkCtrls=(r,flip)=>ctrlsOf(r.id).map((c,k)=>({id:c.id,rating:c.result==='Not tested'?'Not assessed':(c.result==='Ineffective'&&flip&&k===0?'Effective':c.result),comment:''}));
 risks.forEach((r,i)=>{const reg=li(r),pat=i%6,st=['Agreed','Submitted','Not started','Submitted','Overridden','Not started'][pat];
  const it={id:'RA-'+String(i+1).padStart(3,'0'),camp:'RCSA-2026-Q4',risk:r.id,assessor:r.owner,status:st,inh:null,res:null,ctrls:[],q:{fail:'No',change:'No',kri:'Yes'},notes:'',submitted:'',reg,regScore:sc(reg),review:null};
  if(st!=='Not started'){const opt=pat===1||pat===4,self=opt&&reg[1]>1?[reg[0],reg[1]-1]:reg.slice();it.inh=[Math.min(5,reg[0]+1),reg[1]];it.res=self;it.ctrls=mkCtrls(r,pat===1);it.submitted=addDays('2026-10-01',(i%7)+1);it.q.fail=ctrlsOf(r.id).some(c=>c.result==='Ineffective')?'Yes':'No';
   it.notes=opt?'Controls operating as designed; residual considered lower than the register.':'Rating consistent with test results and indicators.';
   if(st==='Agreed')it.review={by:'Morgan Chen',outcome:'Agreed',res:self,comment:'Rating supported by test results and indicators.',date:addDays('2026-10-01',(i%7)+4)};
   if(st==='Overridden'){it.review={by:'Morgan Chen',outcome:'Overridden',res:reg,comment:'Control tests show weaknesses that the self-assessment does not reflect. Residual set to the register level.',date:addDays('2026-10-01',(i%7)+5)}}}
  items.push(it)});
 return{camps:[{id:'RCSA-2026-Q4',name:'Q4 2026 risk & control self-assessment',scope:'All',launched:'2026-10-01',due:'2026-10-30',status:'Open'},{id:'RCSA-2026-Q2',name:'Q2 2026 risk & control self-assessment',scope:'All',launched:'2026-04-01',due:'2026-04-30',status:'Closed',closed:'2026-05-12',hist:{n:risks.length,done:risks.length,overrides:3,exceptions:4}}],items,applied:{}}};
// ---------------------------------------------------------------- module
G.mount({id:'rcsa',label:'RCSA',ico:'☷',group:'RISK OPERATIONS',title:'Risk & control self-assessment (RCSA)',sub:'First-line owners assess their risks and controls, the second line challenges the ratings, and agreed results update the risk register. Run campaigns, track completion, and compare self-assessed ratings with test results and indicators.',tabs:[['campaigns','Campaigns'],['assess','Assessments'],['review','Review & challenge'],['results','Results']]});
const UIs=G.UI.rcsa={camp:''};
const cur=()=>{const c=R().camps.filter(x=>x.status==='Open').sort((a,b)=>a.launched<b.launched?1:-1)[0]||R().camps[0];return UIs.camp&&R().camps.find(x=>x.id===UIs.camp)||c};
const itemsOf=cid=>R().items.filter(i=>i.camp===cid);
const flags=it=>{const f=[];if(!it.res)return f;if(it.regScore-sc(it.res)>=4)f.push(['red','Self-assessed residual is much lower than the register']);else if(it.regScore-sc(it.res)>=2)f.push(['amber','Self-assessed residual is below the register']);
 it.ctrls.forEach(c=>{const x=S().controls.find(y=>y.id===c.id);if(x&&c.rating==='Effective'&&x.result==='Ineffective')f.push(['red',`${c.id} rated Effective but its last test failed`]);else if(x&&c.rating==='Effective'&&x.result==='Partially effective')f.push(['amber',`${c.id} rated Effective but test found exceptions`])});
 if(it.q.fail==='Yes')f.push(['amber','Control failures or near misses reported']);if(it.q.change==='Yes')f.push(['amber','Change affecting the risk reported']);if(it.q.kri==='No')f.push(['amber','Indicators outside tolerance']);if(!ctrlsOf(it.risk).length)f.push(['amber','No control mapped to this risk']);return f};
const final=it=>it.review&&it.review.res?it.review.res:it.res;
// ---------------------------------------------------------------- render
function renderRcsa(){
 if(!R().camps.length&&!R().items.length)return;
 if(!R().appliedDone){const a=R().applied||{};Object.keys(a).forEach(id=>{const r=risks.find(x=>x.id===id);if(r){r.score=a[id].score;r.rating=a[id].rating}});R().appliedDone=true;try{render()}catch{}}
 head('rcsa','<button class="btn" data-op="rc2-export"><span class="btnico">↓</span>Export results</button><button class="btn primary" data-op="rc2-new"><span class="btnico">＋</span>Launch campaign</button>');
 const c=cur(),its=itemsOf(c.id),done=its.filter(i=>i.status!=='Not started'&&i.status!=='Sent back'),pct=its.length?Math.round(done.length/its.length*100):0,od=its.filter(i=>(i.status==='Not started'||i.status==='Sent back')&&dTo(c.due)<0),wait=its.filter(i=>i.status==='Submitted'),flg=its.filter(i=>flags(i).some(f=>f[0]==='red'));
 const sel=`<select class="select" data-xf-rcsa="camp">${R().camps.map(x=>`<option value="${x.id}"${x.id===c.id?' selected':''}>${E(x.id)} · ${E(x.name)}</option>`).join('')}</select>`;
 const crow=R().camps.map(x=>{const ii=itemsOf(x.id),n=x.hist?x.hist.n:ii.length,d=x.hist?x.hist.done:ii.filter(i=>i.status!=='Not started'&&i.status!=='Sent back').length,p=n?Math.round(d/n*100):0;return `<tr data-op="open" data-t="rcamp" data-id="${x.id}"><td class="riskid">${x.id}</td><td><div class="riskname">${E(x.name)}</div><div class="riskarea">Scope: ${E(x.scope)} · launched ${fmt(x.launched)}</div></td><td>${fmt(x.due)}</td><td style="min-width:130px">${bar(p,p>=90?'':p>=50?'amber':'red')}<div class="op-note" style="margin-top:3px">${d} of ${n} complete</div></td><td>${x.hist?x.hist.overrides:ii.filter(i=>i.status==='Overridden').length}</td><td>${pill(x.status,x.status==='Open'?'amber':'green')}</td></tr>`});
 panel('rcsa','campaigns').innerHTML=`<div class="op-kpis">${kpi('Open campaign',E(c.id),E(c.name))}${kpi('Completion',pct+'%',`${done.length} of ${its.length} risks self-assessed`,pct<60?'warn':'ok')}${kpi('Overdue',od.length,`due ${fmt(c.due)}`,od.length?'warn':'ok')}${kpi('Awaiting challenge',wait.length,`${flg.length} flagged for review`,wait.length?'warn':'ok')}</div>${card('RCSA campaigns','Each campaign asks risk owners to rate inherent and residual risk, rate the controls and answer a short questionnaire',table(['ID','Campaign','Due','Progress','Overrides','Status'],crow,'No campaigns.'))}`;
 const f=flt('rcsa','as'),rowsA=its.filter(i=>match(f,[i.id,i.risk,rk(i.risk).name,i.assessor].join(' '))&&(!f.st||f.st==='All'||i.status===f.st)).map(i=>{const fl=flags(i),rr=fl.filter(x=>x[0]==='red').length;return `<tr data-op="open" data-t="rassess" data-id="${i.id}"><td class="riskid">${i.id}</td><td><div class="riskname">${E(rk(i.risk).name)}</div><div class="riskarea">${E(i.risk)} · ${E(rk(i.risk).area)}</div></td><td>${own(i.assessor)}</td><td>${i.res?`${sc(i.res)} <span class="riskarea">(L${i.res[0]} × I${i.res[1]})</span>`:'—'}</td><td>${i.regScore} <span class="riskarea">(L${i.reg[0]} × I${i.reg[1]})</span></td><td>${i.res?(i.regScore-sc(i.res)>0?pill('−'+(i.regScore-sc(i.res)),i.regScore-sc(i.res)>=4?'red':'amber'):'–'):''}</td><td>${fl.length?pill(fl.length+' flag'+(fl.length>1?'s':''),rr?'red':'amber'):''}</td><td>${pill(i.status,CST[i.status])}</td></tr>`});
 panel('rcsa','assess').innerHTML=`<div class="x-filters" style="margin-bottom:10px"><label>Campaign</label>${sel}</div>${toolbar('rcsa','as','Search risks, owners…',[['st',['All','Not started','Submitted','Sent back','Agreed','Overridden'],'All statuses']])}${card('Risk self-assessments',`${E(c.name)} · due ${fmt(c.due)}. Gap = register residual minus self-assessed residual.`,table(['ID','Risk','Assessor','Self residual','Register residual','Gap','Flags','Status'],rowsA,'No assessments.'))}`;
 const q=its.filter(i=>i.status==='Submitted').sort((a,b)=>flags(b).filter(x=>x[0]==='red').length-flags(a).filter(x=>x[0]==='red').length);
 const qr=q.map(i=>{const fl=flags(i);return `<tr data-op="open" data-t="rassess" data-id="${i.id}"><td class="riskid">${i.id}</td><td><div class="riskname">${E(rk(i.risk).name)}</div><div class="riskarea">${E(i.assessor)} · submitted ${fmt(i.submitted)}</div></td><td>${sc(i.res)} vs ${i.regScore}</td><td style="white-space:normal;max-width:360px">${fl.length?fl.map(x=>`<div class="riskarea" style="color:${x[0]==='red'?'#ad4b45':'#a66b13'}">• ${E(x[1])}</div>`).join(''):'<span class="badgepill pill-green">no flags</span>'}</td></tr>`});
 panel('rcsa','review').innerHTML=`<div class="op-kpis">${kpi('Awaiting challenge',q.length,'submitted by the first line',q.length?'warn':'ok')}${kpi('High-priority flags',flg.length,'rating or control inconsistent with evidence',flg.length?'warn':'ok')}${kpi('Overridden',its.filter(i=>i.status==='Overridden').length,'second line changed the rating')}${kpi('Sent back',its.filter(i=>i.status==='Sent back').length,'returned for more information')}</div>${can2()?'':'<p class="op-note" style="margin:0 0 10px">You are viewing as a first-line user. Switch to the Administrator demo user to challenge ratings.</p>'}${card('Second-line review queue','Challenge ratings that look too optimistic or conflict with test results. Agree, override with rationale, or send back.',table(['ID','Risk','Self vs register','Why it needs a look'],qr,'Nothing waiting for challenge.'))}`;
 // results: heatmap of final residual vs register
 const cells={};its.filter(i=>final(i)).forEach(i=>{const k=final(i).join('-');(cells[k]=cells[k]||[]).push(i.risk)});
 let grid='<div class="op-axis"></div>'+[1,2,3,4,5].map(i=>`<div class="op-axis">${i}</div>`).join('');
 for(let l=5;l>=1;l--){grid+=`<div class="op-axis">${l}</div>`;for(let i=1;i<=5;i++){const rs=cells[l+'-'+i]||[];grid+=`<div class="op-cell${l*i>(S().appetite||12)?' out':''}" style="background:${heatCol(l*i)}" data-op="open" data-t="cell" data-id="${l}-${i}">${rs.map(x=>`<span class="op-chip">${E(x)}</span>`).join('')}<small>${l*i}</small></div>`}}
 const areas=[...new Set(risks.map(r=>r.area))],ar=areas.map(a=>{const ii=its.filter(i=>rk(i.risk).area===a&&final(i));if(!ii.length)return `<tr><td>${E(a)}</td><td>–</td><td>–</td><td>–</td><td>0</td></tr>`;const reg=ii.reduce((s,i)=>s+i.regScore,0)/ii.length,self=ii.reduce((s,i)=>s+sc(final(i)),0)/ii.length;return `<tr><td><div class="riskname">${E(a)}</div></td><td>${ii.length}</td><td>${reg.toFixed(1)}</td><td>${self.toFixed(1)}</td><td>${reg-self>=2?pill('optimistic','amber'):pill('aligned','green')}</td></tr>`}).join('');
 const cc=its.flatMap(i=>i.ctrls),agree=cc.filter(x=>{const t=S().controls.find(y=>y.id===x.id);return t&&(t.result===x.rating||x.rating==='Not assessed')}).length;
 const done2=its.filter(i=>i.status==='Agreed'||i.status==='Overridden'),appl=done2.filter(i=>R().applied[i.risk]&&R().applied[i.risk].camp===c.id).length;
 panel('rcsa','results').innerHTML=`<div class="op-kpis">${kpi('Final ratings',done2.length,`of ${its.length} risks (agreed or overridden)`)}${kpi('Applied to register',appl,'ratings written to the risk register')}${kpi('Controls rated consistently',cc.length?Math.round(agree/cc.length*100)+'%':'–','self rating matches latest test',cc.length&&agree/cc.length<0.8?'warn':'ok')}${kpi('Exceptions reported',its.filter(i=>i.q.fail==='Yes').length,'control failures or near misses')}</div><div class="op-two"><article class="card panel"><div class="panelhead"><div><div class="panel-title">Residual risk after RCSA</div><div class="panel-sub">Final rating per risk (agreed or overridden, otherwise self-assessed). Click a cell to list risks.</div></div><button class="op-mini p" data-op="rc2-apply" data-id="${c.id}">Apply to risk register</button></div><div class="op-heat">${grid}</div></article><article class="card panel"><div class="panel-title">By area</div><div class="panel-sub" style="margin-bottom:8px">Average residual score: register vs RCSA</div><div class="tablewrap"><table><thead><tr><th>Area</th><th>Risks</th><th>Register</th><th>RCSA</th><th></th></tr></thead><tbody>${ar}</tbody></table></div></article></div>`;
 G.setBadge('rcsa',wait.length+od.length)}
G.renders.push(renderRcsa);
document.addEventListener('change',e=>{const k=e.target.dataset&&e.target.dataset.xfRcsa;if(k){UIs.camp=e.target.value;G.renderAll()}});
// ---------------------------------------------------------------- drawers
G.drawers.rcamp=id=>{const c=R().camps.find(x=>x.id===id);if(!c)return;const its=itemsOf(c.id),ns=its.filter(i=>i.status==='Not started'||i.status==='Sent back'),P2=[];
 if(c.status==='Open'){const ds=dueState(c.due,7);if(ds)P2.push([ds[0],`Campaign due ${ds[1]}.`]);if(ns.length)P2.push([dTo(c.due)<0?'red':'amber',`${ns.length} assessment(s) not yet submitted.`]);const w=its.filter(i=>i.status==='Submitted').length;if(w)P2.push(['amber',`${w} submission(s) awaiting second-line challenge.`])}
 detail({kicker:'RCSA campaign · '+c.id,title:c.name,pending:P2,ok:c.status==='Closed'?'Campaign closed.':'On schedule.',todo:['Send reminders to assessors with open items.','Challenge submitted ratings, especially the flagged ones.','Apply agreed ratings to the risk register and raise issues for weak controls.','Close the campaign and report to the risk committee.'],
  facts:[['Scope',E(c.scope)],['Launched',fmt(c.launched)],['Due',fmt(c.due)],['Status',E(c.status)],['Assessments',String(its.length)],['Submitted',String(its.filter(i=>i.status!=='Not started'&&i.status!=='Sent back').length)]],
  buttons:c.status==='Open'?`<button class="op-mini p" data-op="rc2-remind" data-id="${c.id}">Send reminders (${ns.length})</button><button class="op-mini" data-op="rc2-apply" data-id="${c.id}">Apply agreed ratings to register</button><button class="op-mini g" data-op="rc2-close" data-id="${c.id}">Close campaign</button>`:'',links:ns.map(i=>i.id)})};
G.drawers.rassess=id=>{const it=R().items.find(x=>x.id===id);if(!it)return;const r=rk(it.risk),cs=ctrlsOf(it.risk),fl=flags(it),c=R().camps.find(x=>x.id===it.camp),P2=[];
 if(it.status==='Not started'||it.status==='Sent back'){const ds=dueState(c.due,7);P2.push(ds?[ds[0],`Self-assessment ${ds[1]}.`]:['amber','Self-assessment not yet submitted.']);if(it.status==='Sent back'&&it.review)P2.push(['amber',`Sent back by ${E(it.review.by)}: ${E(it.review.comment)}`])}
 if(it.status==='Submitted')P2.push(['amber','Awaiting second-line challenge.']);fl.forEach(x=>P2.push([x[0],E(x[1])+'.']));
 const todo=it.status==='Not started'||it.status==='Sent back'?['Rate inherent risk (before controls), rate each control and rate residual risk.','Answer the questionnaire honestly: failures, change and indicators.','Attach evidence in the notes and submit.']:it.status==='Submitted'?['Second line reviews evidence, tests and indicators.','Agree, override with rationale, or send back for more detail.']:['Rating is final. Apply agreed ratings to the register from the Results tab.'];
 detail({kicker:'Self-assessment · '+it.id,title:r.name,pending:P2,ok:'Assessed, challenged and agreed.',todo,
  facts:[['Risk',E(it.risk)+' · '+E(r.area)],['Assessor',E(it.assessor)],['Status',pill(it.status,CST[it.status])],['Inherent (self)',it.inh?`${sc(it.inh)} (L${it.inh[0]} × I${it.inh[1]})`:'—'],['Residual (self)',it.res?`${sc(it.res)} (L${it.res[0]} × I${it.res[1]})`:'—'],['Residual (register)',`${it.regScore} (L${it.reg[0]} × I${it.reg[1]})`],['Final rating',final(it)&&(it.status==='Agreed'||it.status==='Overridden')?`${sc(final(it))} · ${rate(sc(final(it)))}`:'Pending'],['Submitted',it.submitted?fmt(it.submitted):'—']],
  buttons:`${it.status==='Not started'||it.status==='Sent back'?`<button class="op-mini p" data-op="rc2-assess" data-id="${it.id}">Complete self-assessment</button>`:''}${it.status==='Submitted'&&can2()?`<button class="op-mini p" data-op="rc2-challenge" data-id="${it.id}">Challenge / review</button>`:''}${it.status==='Submitted'&&!can2()?'<span class="op-note">Only the second line can challenge this rating.</span>':''}${fl.some(x=>x[0]==='red')?`<button class="op-mini r" data-op="rc2-issue" data-id="${it.id}">Raise issue</button>`:''}`,
  extra:`${it.ctrls.length?`<h4>Control ratings</h4>${table(['Control','Self-rated','Latest test'],it.ctrls.map(x=>{const t=S().controls.find(y=>y.id===x.id);return `<tr style="cursor:default"><td>${E(x.id)} · ${E(t?t.name:'')}</td><td>${pill(x.rating,RK[x.rating])}</td><td>${t?pill(t.result,RK[t.result]||'blue'):''}</td></tr>`}))}`:''}${it.status!=='Not started'?`<h4>Questionnaire</h4>${G.bl([`Control failures or near misses this period: <b>${it.q.fail}</b>`,`Changes affecting this risk (people, process, system, regulation): <b>${it.q.change}</b>`,`Key risk indicators within tolerance: <b>${it.q.kri}</b>`])}`:''}${it.notes?`<h4>Assessor notes</h4><p class="op-note" style="font-size:11px;color:#475569;margin-top:0">${E(it.notes)}</p>`:''}${it.review?`<h4>Second-line review</h4><p class="op-note" style="font-size:11px;color:#475569;margin-top:0"><b>${E(it.review.outcome)}</b> by ${E(it.review.by)} on ${fmt(it.review.date)}${it.review.res?` · residual ${sc(it.review.res)}`:''}<br>${E(it.review.comment)}</p>`:''}`,
  links:[it.risk,...cs.map(x=>x.id),...S().kris.filter(k=>k.risk===it.risk).map(k=>k.id),...S().issues.filter(i=>i.link===it.id).map(i=>i.id)]})};
G.linkers.push(id=>{const it=R().items.find(x=>x.id===id);return it?{type:'rassess',label:`${it.id} · ${rk(it.risk).name}`}:null});
// ---------------------------------------------------------------- actions
const lsel=(n,l,v,lab)=>({name:n,label:l,type:'select',options:[1,2,3,4,5].map(x=>[String(x),lab[x]]),value:String(v)});
Object.assign(actions,{
 'rc2-new':()=>openForm('Launch RCSA campaign',[{name:'name',label:'Campaign name',full:true,value:'Q1 2027 risk & control self-assessment'},{name:'scope',label:'Scope',type:'select',options:['All',...new Set(risks.map(r=>r.area))]},{name:'due',label:'Responses due',type:'date',value:addDays(TODAY,21)}],'Launch',v=>{if(!v.name)return 'Name the campaign.';const s=R(),n=s.camps.length+1,id='RCSA-'+TODAY.slice(0,4)+'-C'+String(n).padStart(2,'0');const rs=risks.filter(r=>v.scope==='All'||r.area===v.scope);let k=s.items.reduce((m,i)=>Math.max(m,+i.id.slice(3)),0);s.camps.push({id,name:v.name,scope:v.scope,launched:TODAY,due:v.due,status:'Open'});rs.forEach(r=>{const reg=riskLI(r,'residual');s.items.push({id:'RA-'+String(++k).padStart(3,'0'),camp:id,risk:r.id,assessor:r.owner,status:'Not started',inh:null,res:null,ctrls:[],q:{fail:'No',change:'No',kri:'Yes'},notes:'',submitted:'',reg,regScore:sc(reg),review:null})});UIs.camp=id;logIt(id,`Campaign launched for ${rs.length} risks.`);commit();toast(`${id} launched: ${rs.length} self-assessments assigned to risk owners.`)}),
 'rc2-assess':b=>{const it=R().items.find(x=>x.id===b.dataset.id),r=rk(it.risk),cs=ctrlsOf(it.risk);const reg=it.reg;
  openForm('Self-assessment · '+r.name,[lsel('il','Inherent likelihood (before controls)',it.inh?it.inh[0]:Math.min(5,reg[0]+1),LLAB),lsel('ii','Inherent impact',it.inh?it.inh[1]:reg[1],ILAB),...cs.map((c,k)=>({name:'c'+k,label:`Control ${c.id}: ${c.name}`,type:'select',full:true,options:['Effective','Partially effective','Ineffective','Not assessed'],value:(it.ctrls.find(x=>x.id===c.id)||{}).rating||(c.result==='Not tested'?'Not assessed':c.result)})),lsel('rl','Residual likelihood (after controls)',it.res?it.res[0]:reg[0],LLAB),lsel('ri','Residual impact',it.res?it.res[1]:reg[1],ILAB),{name:'q1',label:'Any control failures or near misses this period?',type:'select',options:['No','Yes'],value:it.q.fail},{name:'q2',label:'Any change affecting this risk (people, process, system, regulation)?',type:'select',options:['No','Yes'],value:it.q.change},{name:'q3',label:'Are the key risk indicators within tolerance?',type:'select',options:['Yes','No'],value:it.q.kri},{name:'notes',label:'Rationale and evidence',type:'textarea',full:true,value:it.notes}],'Submit self-assessment',v=>{const inh=[+v.il,+v.ii],res=[+v.rl,+v.ri];if(sc(res)>sc(inh))return 'Residual risk cannot be higher than inherent risk.';if(!v.notes)return 'Add a short rationale or evidence reference.';
   it.inh=inh;it.res=res;it.ctrls=cs.map((c,k)=>({id:c.id,rating:v['c'+k],comment:''}));it.q={fail:v.q1,change:v.q2,kri:v.q3};it.notes=v.notes;it.submitted=TODAY;it.status='Submitted';it.review=null;logIt(it.id,`${it.assessor} submitted self-assessment (residual ${sc(res)}).`);commit();toast('Submitted for second-line review.')})},
 'rc2-challenge':b=>{const it=R().items.find(x=>x.id===b.dataset.id),fl=flags(it);
  openForm('Challenge · '+rk(it.risk).name,[{name:'out',label:'Outcome',type:'select',options:['Agreed','Overridden','Sent back'],value:fl.some(x=>x[0]==='red')?'Overridden':'Agreed'},lsel('rl','Residual likelihood (if overriding)',it.reg[0],LLAB),lsel('ri','Residual impact (if overriding)',it.reg[1],ILAB),{name:'c',label:'Rationale',type:'textarea',full:true,ph:'Evidence considered, test results, indicators, incidents',value:fl.length?'Considered: '+fl.map(x=>x[1]).join('; ')+'.':''}],'Record decision',v=>{if(!v.c)return 'Record your rationale.';it.review={by:me().name,outcome:v.out,res:v.out==='Overridden'?[+v.rl,+v.ri]:v.out==='Agreed'?it.res:null,comment:v.c,date:TODAY};it.status=v.out;logIt(it.id,`Challenge: ${v.out}.`);commit();toast(`${it.id}: ${v.out}.`)})},
 'rc2-issue':b=>{const it=R().items.find(x=>x.id===b.dataset.id),r=rk(it.risk);raise('RCSA',it.id,`RCSA exception: ${r.name}`,'High',it.assessor,flags(it).map(x=>x[1]).join('. ')+'.','Control design');commit()},
 'rc2-remind':b=>{const c=R().camps.find(x=>x.id===b.dataset.id),ns=itemsOf(c.id).filter(i=>i.status==='Not started'||i.status==='Sent back'),who=[...new Set(ns.map(i=>i.assessor))];logIt(c.id,`Reminders sent to ${who.join(', ')}.`);G.save();toast(`Reminders sent to ${who.length} assessor(s) with ${ns.length} open assessment(s).`)},
 'rc2-apply':b=>{const c=R().camps.find(x=>x.id===b.dataset.id),its=itemsOf(c.id).filter(i=>i.status==='Agreed'||i.status==='Overridden');if(!its.length){toast('No agreed or overridden ratings to apply yet.');return}let n=0;its.forEach(i=>{const r=risks.find(x=>x.id===i.risk),f=final(i);if(!r||!f)return;r.score=sc(f);r.rating=rate(sc(f));R().applied[i.risk]={score:r.score,rating:r.rating,camp:c.id};n++});try{render()}catch{}logIt(c.id,`Applied ${n} agreed ratings to the risk register.`);commit();toast(`${n} ratings applied to the risk register.`)},
 'rc2-close':b=>{const c=R().camps.find(x=>x.id===b.dataset.id),open=itemsOf(c.id).filter(i=>i.status==='Not started'||i.status==='Sent back'||i.status==='Submitted').length;if(open){toast(`${open} assessment(s) are still open. Complete or challenge them first.`);return}c.status='Closed';c.closed=TODAY;logIt(c.id,'Campaign closed.');commit();G.closeDrawer();toast(c.id+' closed.')},
 'rc2-export':()=>{const c=cur();csv('forge-rcsa-'+c.id+'.csv',[['ID','Risk','Area','Assessor','Status','Inherent','Self residual','Register residual','Final residual','Flags','Reviewer','Outcome'],...itemsOf(c.id).map(i=>[i.id,i.risk+' '+rk(i.risk).name,rk(i.risk).area,i.assessor,i.status,i.inh?sc(i.inh):'',i.res?sc(i.res):'',i.regScore,final(i)?sc(final(i)):'',flags(i).map(x=>x[1]).join('; '),i.review?i.review.by:'',i.review?i.review.outcome:''])],'RCSA results exported as CSV.')}
});
G.xTiles.push(()=>{const c=cur();if(!c)return null;const its=itemsOf(c.id);if(!its.length)return null;const done=its.filter(i=>i.status!=='Not started'&&i.status!=='Sent back').length,pct=Math.round(done/its.length*100),w=its.filter(i=>i.status==='Submitted').length,od=its.filter(i=>(i.status==='Not started'||i.status==='Sent back')&&dTo(c.due)<0).length;return{key:'rcsa-open',l:'RCSA completion',v:pct+'%',f:`${c.id} · ${w} awaiting challenge · ${od} overdue · due ${fmt(c.due)}`,k:od||pct<50?'red':pct<90?'amber':'green',ic:'☷'}});
G.metrics['rcsa-open']=()=>{const c=cur();return['RCSA',c.id+' · open assessments','Not started, sent back or awaiting second-line challenge.',itemsOf(c.id).filter(i=>i.status!=='Agreed'&&i.status!=='Overridden').map(i=>({id:i.id,sub:`${rk(i.risk).name} · ${i.assessor}${flags(i).length?' · '+flags(i).length+' flag(s)':''}`,pill:pill(i.status,CST[i.status])}))]};
G.renderAll();
})();
