// Built-in regulatory & framework library (BFSI, privacy, cyber, resilience and general GRC).
// Obligations are plain-language summaries for planning and mapping, NOT legal text. Each framework carries a
// "verify" flag: confirm the current wording, dates and applicability against the official source and your
// legal/compliance team before relying on it. Themes let one control satisfy obligations across regimes.
window.GRC_LIB={
 themes:{
  GOV:'Governance & accountability',RISK:'Risk management',TPR:'Third-party & outsourcing',INC:'Incident management & reporting',
  RES:'Resilience & continuity',TEST:'Testing & assurance',PRIV:'Data protection & privacy',SEC:'Information & cyber security',
  DISC:'Records, reporting & disclosure',CONDUCT:'Customer protection & conduct',FC:'Financial crime (AML / KYC / fraud)',AI:'AI & model risk'
 },
 frameworks:[
 {id:'gdpr',code:'GDPR',name:'EU General Data Protection Regulation (2016/679)',kind:'Law',region:'EU / EEA (extra-territorial)',sectors:['All','BFSI'],issuer:'European Union',
  summary:'Rules for processing personal data of people in the EU. Fines up to €20m or 4% of worldwide turnover.',
  obl:[
  ['Art. 5','Processing principles','Process personal data lawfully, fairly and transparently, for specified purposes, minimised, accurate, time-limited and secured; be able to demonstrate it.','PRIV'],
  ['Art. 6–7','Lawful basis and consent','Record a lawful basis for each processing purpose; where relying on consent, keep proof, make it specific and as easy to withdraw as to give.','PRIV'],
  ['Art. 12–14','Transparency notices','Give clear privacy notices at collection: who you are, purposes, recipients, transfers, retention and rights.','PRIV'],
  ['Art. 15–22','Data-subject rights','Handle access, rectification, erasure, restriction, portability and objection requests within one month (extendable by two).','PRIV'],
  ['Art. 24–25','Accountability and privacy by design','Implement measures and policies proportionate to risk; build data protection into systems by design and default.','GOV'],
  ['Art. 28','Processor contracts','Use processors only under a written contract covering instructions, security, sub-processors, audit and deletion/return.','TPR'],
  ['Art. 30','Records of processing (ROPA)','Maintain a record of processing activities with purposes, data categories, recipients, transfers, retention and security measures.','DISC'],
  ['Art. 32','Security of processing','Apply appropriate technical and organisational measures: pseudonymisation/encryption, resilience, restoration, regular testing.','SEC'],
  ['Art. 33','Breach notification to authority','Notify the supervisory authority within 72 hours of becoming aware of a personal data breach, unless unlikely to risk individuals.','INC'],
  ['Art. 34','Breach communication to individuals','Tell affected individuals without undue delay where the breach is likely to result in high risk to them.','INC'],
  ['Art. 35','Data protection impact assessment','Carry out a DPIA before high-risk processing (profiling, large-scale special-category data, systematic monitoring).','RISK'],
  ['Art. 37–39','Data Protection Officer','Appoint a DPO where required; ensure independence, resources and direct reporting to top management.','GOV'],
  ['Art. 44–49','International transfers','Transfer personal data outside the EEA only with an adequacy decision, SCCs/BCRs or another valid safeguard and a transfer assessment.','PRIV']]},
 {id:'dpdp',code:'DPDP Act 2023',name:'India Digital Personal Data Protection Act, 2023 (and DPDP Rules, 2025)',kind:'Law',region:'India',sectors:['All','BFSI'],issuer:'Government of India / Data Protection Board of India',
  summary:'India’s data protection law for digital personal data. Penalties up to ₹250 crore per instance. Rules were notified in 2025 and obligations are being phased in.',verify:'Confirm phase-in dates and the final Rules text; some obligations (e.g. consent managers, most duties) commence later than the Board.',
  obl:[
  ['s.4–7','Lawful grounds: consent or legitimate use','Process personal data only with valid consent or a listed legitimate use; consent must be free, specific, informed, unconditional and unambiguous, with clear affirmative action.','PRIV'],
  ['s.5','Notice to data principals','Give an itemised notice (data, purpose, how to exercise rights and complain to the Board) in plain language, with an option of English or an Eighth Schedule language.','PRIV'],
  ['s.6(4)–(6)','Withdrawal of consent and consent managers','Make withdrawal as easy as giving consent and stop processing within a reasonable time; support registered consent managers.','PRIV'],
  ['s.8(3)–(4)','Accuracy and organisational measures','Ensure data used for decisions or disclosure is complete and accurate; implement appropriate technical and organisational measures.','GOV'],
  ['s.8(5)','Reasonable security safeguards','Protect personal data in your possession or control (including with processors) with reasonable security safeguards to prevent breach.','SEC'],
  ['s.8(6)','Personal data breach intimation','Intimate the Data Protection Board and each affected data principal of a personal data breach, with a detailed report to the Board within the Rules’ timeline (72 hours).','INC'],
  ['s.8(7)','Erasure when purpose is served','Erase personal data when consent is withdrawn or the purpose is no longer served, unless law requires retention; ensure processors erase too.','PRIV'],
  ['s.8(9)–(10)','Contact point and grievance redressal','Publish the business contact of a DPO or designated person and provide an effective grievance mechanism (response within the Rules’ period, 90 days).','CONDUCT'],
  ['s.9','Children’s data','Obtain verifiable parental/guardian consent for under-18s; no tracking, behavioural monitoring or targeted advertising directed at children.','PRIV'],
  ['s.10','Significant Data Fiduciary duties','If notified as an SDF: appoint an India-based DPO, an independent data auditor, and run periodic DPIAs and audits.','GOV'],
  ['s.11–14','Rights of data principals','Support rights to access a summary, correct, complete, update and erase data, grievance redressal and nominating another person.','PRIV'],
  ['s.8(2) / s.16','Processors and cross-border transfer','Engage processors only under a valid contract; transfers outside India are allowed except to countries restricted by the Government.','TPR'],
  ['Rules 2025','Retention of logs and records','Retain personal data processing logs and related records for the period the Rules specify (one year) to support detection and investigation.','DISC']]},
 {id:'dora',code:'DORA',name:'EU Digital Operational Resilience Act (2022/2554)',kind:'Law',region:'EU financial sector',sectors:['BFSI'],issuer:'European Union (EBA / ESMA / EIOPA oversight)',
  summary:'Harmonised ICT risk, incident, testing and third-party rules for EU financial entities. Applies from 17 January 2025.',
  obl:[
  ['Art. 5','Management body accountability','The management body defines, approves, oversees and is accountable for the ICT risk framework, and must keep ICT knowledge up to date.','GOV'],
  ['Art. 6–7','ICT risk management framework','Maintain a documented, reviewed ICT risk management framework with strategies, policies, procedures and up-to-date ICT systems, protocols and tools.','RISK'],
  ['Art. 8','Identification','Identify, classify and document ICT-supported business functions, assets, dependencies and risk sources; keep inventories current.','RISK'],
  ['Art. 9–10','Protection, prevention and detection','Apply security policies, access control, patching and encryption; detect anomalous activity and have multiple layers of detection.','SEC'],
  ['Art. 11–12','Response, recovery and backup','Maintain ICT business continuity and response/recovery plans, backup policies and restoration tested periodically.','RES'],
  ['Art. 13–14','Learning and communication','Learn from incidents and tests, run awareness training, and have communication plans for incidents and disclosures.','RES'],
  ['Art. 17–18','Incident management and classification','Run an ICT-related incident process, classify incidents and cyber threats by criteria (clients, duration, geography, data loss, criticality, economic impact).','INC'],
  ['Art. 19','Major incident reporting','Report major ICT incidents to the competent authority: initial notification (within 4 hours of classification, 24 hours of detection), intermediate and final reports.','INC'],
  ['Art. 24–25','Digital operational resilience testing','Run a risk-based testing programme at least yearly for critical systems (vulnerability scans, scenario tests, penetration tests), remediating findings.','TEST'],
  ['Art. 26–27','Threat-led penetration testing (TLPT)','Significant entities perform advanced TLPT at least every three years on live critical functions using accredited testers.','TEST'],
  ['Art. 28','Third-party risk strategy and register of information','Manage ICT third-party risk as part of the framework, with a strategy, policy and a register of information on all contractual arrangements.','TPR'],
  ['Art. 29','Concentration risk','Assess ICT concentration risk before entering contracts for critical or important functions, including sub-outsourcing chains.','TPR'],
  ['Art. 30','Key contractual provisions','Include service descriptions, locations, security, incident assistance, audit/access rights, exit strategies and termination rights in ICT contracts.','TPR'],
  ['Art. 45','Information sharing','Voluntarily exchange cyber threat information within trusted communities, with safeguards, and notify the authority of participation.','SEC']]},
 {id:'rbi-itgrc',code:'RBI IT Governance MD',name:'RBI Master Direction on IT Governance, Risk, Controls and Assurance Practices (2023)',kind:'Regulator direction',region:'India',sectors:['BFSI'],issuer:'Reserve Bank of India',
  summary:'IT governance and assurance requirements for banks, NBFCs (top, upper and middle layers) and other regulated entities. Effective 1 April 2024.',verify:'Confirm entity-type applicability and any later amendments.',
  obl:[
  ['Governance','Board-approved IT strategy and committees','Board approves the IT strategy and policy; set up an IT Strategy Committee and an IT Steering Committee with defined responsibilities.','GOV'],
  ['Governance','Accountable CIO and CISO','Appoint a CIO/Head IT and an independent CISO with adequate authority, resources and reporting lines.','GOV'],
  ['IT risk','IT and information security risk management','Maintain an IT risk framework integrated with enterprise risk; periodic risk assessment, risk appetite and board reporting.','RISK'],
  ['Controls','Access, change, patch and configuration controls','Implement access management, change and release management, patching and secure configuration baselines.','SEC'],
  ['Cyber','Cyber incident reporting to RBI','Report cyber incidents to RBI within the prescribed window (6 hours of detection) and conduct root-cause analysis.','INC'],
  ['BCP / DR','Business continuity and disaster recovery','Maintain BCP/DR plans, defined RTO/RPO for critical systems, and test at least annually.','RES'],
  ['Assurance','Information systems audit','Risk-based IS audit by qualified auditors, with findings tracked to closure and reported to the Audit Committee.','TEST'],
  ['Outsourcing','IT outsourcing governance','Apply governance, due diligence, monitoring and exit planning for IT outsourcing and cloud arrangements.','TPR'],
  ['Data','Data governance, classification and retention','Classify information assets, protect sensitive data, and define retention and secure disposal.','PRIV']]},
 {id:'rbi-outsourcing',code:'RBI IT Outsourcing MD',name:'RBI Master Direction on Outsourcing of Information Technology Services (2023)',kind:'Regulator direction',region:'India',sectors:['BFSI'],issuer:'Reserve Bank of India',
  summary:'Governance of IT outsourcing and cloud by regulated entities. Effective 1 October 2023.',verify:'Confirm entity-type applicability.',
  obl:[
  ['Policy','Board-approved IT outsourcing policy','Maintain a policy covering materiality assessment, risk evaluation, selection and monitoring of service providers.','GOV'],
  ['Due diligence','Service provider due diligence','Assess financial soundness, capability, security, business continuity, reputation and sub-contracting before and during engagement.','TPR'],
  ['Contract','Mandatory contract provisions','Include SLAs, security and confidentiality, incident notification, right to audit (including RBI), data location and termination in agreements.','TPR'],
  ['Concentration','Concentration and sub-outsourcing risk','Assess dependence on a single provider or group and manage risks from sub-contracting.','TPR'],
  ['Data','Data protection and location','Retain control of customer data; ensure confidentiality, segregation and access to data held abroad is available to RBI.','PRIV'],
  ['Exit','Exit strategy and business continuity','Maintain tested exit plans and continuity arrangements for critical outsourced services.','RES'],
  ['Register','Register of IT outsourcing arrangements','Keep a current register of all IT outsourcing arrangements and report material ones as required.','DISC']]},
 {id:'rbi-csf',code:'RBI Cyber Security Framework',name:'RBI Cyber Security Framework in Banks (2016) and related cyber directions',kind:'Regulator direction',region:'India',sectors:['BFSI'],issuer:'Reserve Bank of India',
  summary:'Baseline cyber controls, SOC and crisis management expected of banks and similar regulated entities.',verify:'Applicability differs by entity type; check the current circulars and annexures.',
  obl:[
  ['Policy','Board-approved cyber security policy','Maintain a distinct cyber security policy approved by the Board, reviewed at least annually.','GOV'],
  ['Annex 1','Baseline cyber controls','Implement baseline controls: inventory, secure configuration, patching, anti-malware, email/web filtering, network segmentation, privileged access, logging.','SEC'],
  ['SOC','Security operations centre','Operate (or contract) a 24x7 SOC for continuous surveillance and timely detection and response.','SEC'],
  ['CCMP','Cyber crisis management plan','Maintain and test a cyber crisis management plan aligned with CERT-In and RBI guidance.','RES'],
  ['Reporting','Incident reporting','Report unusual cyber incidents to RBI and CERT-In within the required time frames and provide root-cause analysis.','INC'],
  ['Testing','Vulnerability assessment and penetration testing','Run periodic VA/PT and red-team style exercises, and remediate findings by risk.','TEST'],
  ['Payments','Digital payment security controls','Apply the digital payment security control requirements for internet, mobile and card channels.','SEC']]},
 {id:'rbi-kyc',code:'RBI KYC MD',name:'RBI Master Direction – Know Your Customer (2016, as amended)',kind:'Regulator direction',region:'India',sectors:['BFSI'],issuer:'Reserve Bank of India',
  summary:'Customer due diligence and AML/CFT obligations for regulated entities, aligned to the Prevention of Money-laundering Act.',verify:'Re-confirm periodic-updation intervals and any recent amendments.',
  obl:[
  ['Policy','Board-approved KYC / AML policy','Maintain a KYC policy with customer acceptance, identification, monitoring and risk management elements; appoint a Designated Director and Principal Officer.','GOV'],
  ['CDD','Customer due diligence','Identify and verify customers, and beneficial owners of legal entities, using officially valid documents or e-KYC.','FC'],
  ['Risk','Customer risk categorisation','Categorise customers as low, medium or high risk and apply enhanced due diligence to high risk (PEPs, complex structures, high-risk geographies).','FC'],
  ['Monitoring','Ongoing monitoring and periodic updation','Monitor transactions against customer profile and update KYC periodically (broadly 2 / 8 / 10 years for high / medium / low risk).','FC'],
  ['Reporting','CTR and STR reporting to FIU-IND','File cash and suspicious transaction reports with FIU-IND within the prescribed timelines; no tipping-off.','FC'],
  ['Records','Record keeping','Preserve identification and transaction records for the prescribed period (at least five years after the relationship ends / transaction).','DISC']]},
 {id:'pmla',code:'PMLA 2002',name:'India Prevention of Money-laundering Act, 2002 and PML Rules',kind:'Law',region:'India',sectors:['BFSI'],issuer:'Government of India / FIU-IND',
  summary:'Reporting entities must verify clients, keep records and report cash and suspicious transactions to FIU-IND.',verify:'Reporting timelines and thresholds are set in the Rules; verify current values.',
  obl:[
  ['s.12','Reporting entity duties','Maintain records of transactions and client identity, and furnish information to the Financial Intelligence Unit – India.','FC'],
  ['Rule 3–8','Transaction records and reporting','Report cash transactions above ₹10 lakh (monthly) and suspicious transactions promptly after concluding suspicion (within 7 working days).','FC'],
  ['Rule 9','Client due diligence','Verify identity of clients and beneficial owners; apply enhanced diligence on risk triggers.','FC'],
  ['Governance','Designated Director and Principal Officer','Appoint and notify a Designated Director and a Principal Officer responsible for compliance with the Act.','GOV'],
  ['Review','Internal policies and independent testing','Maintain AML policies, staff training, hiring screening and independent evaluation of the programme.','TEST']]},
 {id:'rbi-fraud',code:'RBI Fraud Risk MD',name:'RBI Master Directions on Fraud Risk Management (2024)',kind:'Regulator direction',region:'India',sectors:['BFSI'],issuer:'Reserve Bank of India',
  summary:'Fraud risk governance, early warning systems, classification and reporting for banks and NBFCs.',verify:'Confirm entity-specific directions and timelines.',
  obl:[
  ['Governance','Board policy and special committee','Board-approved fraud risk policy and a Special Committee of the Board for fraud monitoring.','GOV'],
  ['EWS','Early warning signals framework','Operate a data-driven early warning system to flag accounts and transactions showing fraud indicators.','FC'],
  ['Natural justice','Show-cause and fair hearing before classification','Give borrowers notice and an opportunity to respond before classifying an account as fraud.','CONDUCT'],
  ['Reporting','Fraud reporting to RBI and law enforcement','Report frauds to RBI (within 14 days of classification) and to law enforcement, with prescribed returns.','INC'],
  ['Review','Staff accountability and root-cause review','Examine staff accountability and conduct root-cause analysis; strengthen controls after each fraud.','RISK']]},
 {id:'rbi-digital-lending',code:'RBI Digital Lending',name:'RBI Digital Lending Guidelines / Directions (2022, 2025)',kind:'Regulator direction',region:'India',sectors:['BFSI'],issuer:'Reserve Bank of India',
  summary:'Borrower protection, transparency, data and lending-service-provider rules for digital lending.',verify:'The 2025 Directions consolidate earlier guidelines; verify current requirements.',
  obl:[
  ['Disclosure','Key Fact Statement and APR','Give every borrower a Key Fact Statement with the all-inclusive annual percentage rate before the contract is executed.','CONDUCT'],
  ['Flow of funds','Direct disbursal and repayment','Disburse and collect directly between the borrower’s bank account and the regulated entity, with no pass-through accounts of service providers.','CONDUCT'],
  ['LSP','Lending service provider oversight','Conduct due diligence on LSPs and digital lending apps, publish their details and remain responsible for their conduct.','TPR'],
  ['Data','Data minimisation and storage in India','Collect only need-based data with explicit consent, no biometric storage, and keep data on servers in India.','PRIV'],
  ['Grievance','Grievance redressal and cooling-off','Nominate a grievance officer, give a cooling-off period to exit, and resolve complaints within the prescribed time.','CONDUCT']]},
 {id:'sebi-cscrf',code:'SEBI CSCRF',name:'SEBI Cybersecurity and Cyber Resilience Framework (CSCRF) for SEBI Regulated Entities (2024)',kind:'Regulator direction',region:'India',sectors:['BFSI'],issuer:'Securities and Exchange Board of India',
  summary:'Goal-based cyber framework (Anticipate, Withstand, Contain, Recover, Evolve) built on six functions: Governance, Identify, Protect, Detect, Respond, Recover. Controls scale with the entity category: Market Infrastructure Institution, Qualified, Mid-size, Small-size or Self-certification RE.',
  verify:'Applicability, control sets, audit frequency and deadlines depend on the RE category and later SEBI clarifications and extensions. Confirm against the current circular and your category before adopting dates.',
  obl:[
  ['GV.1','Board-approved cyber security and resilience policy','Board (or equivalent) approves and reviews a cyber security and cyber resilience policy aligned to CSCRF, at least annually and after major incidents.','GOV'],
  ['GV.2','CISO / designated officer and technology committee','Appoint a CISO or designated officer with authority and reporting access to the board; set up a technology / IT strategy committee to oversee cyber posture.','GOV'],
  ['GV.3','Cyber risk appetite and cyber crisis management plan','Define cyber risk appetite and maintain a cyber crisis management plan (CCMP) with escalation, decision rights and regulator communication.','RISK'],
  ['GV.4','Entity categorisation and category-specific controls','Determine the RE category (MII, Qualified, Mid-size, Small-size, Self-certification) and implement the mandatory controls for that category.','GOV'],
  ['GV.5','Periodic compliance submissions','Submit the periodic CSCRF compliance / self-assessment reports and certifications to SEBI or the exchange within the prescribed timelines.','DISC'],
  ['GV.6','Comprehensive cyber audit','Commission a cyber audit by a CERT-In empanelled auditor at the prescribed frequency; table the report to the board and track findings to closure.','TEST'],
  ['ID.1','Asset inventory and classification','Maintain a current inventory of hardware, software, data, APIs and cloud assets; classify by criticality and identify critical systems.','RISK'],
  ['ID.2','Cyber risk assessment','Run periodic cyber risk assessments covering critical assets, threats, third parties and cloud, with documented treatment decisions.','RISK'],
  ['ID.3','Software bill of materials and supply chain inventory','For critical software, maintain a software bill of materials (SBOM) or equivalent component inventory and track vulnerabilities in dependencies.','TPR'],
  ['PR.1','Identity, access and privileged access management','Enforce least privilege, multi-factor authentication for privileged and remote access, joiner-mover-leaver controls and periodic access recertification.','SEC'],
  ['PR.2','Network security and segmentation','Segment critical networks, restrict internet exposure, use firewalls, secure remote access and control wireless and third-party connectivity.','SEC'],
  ['PR.3','Data security and encryption','Encrypt sensitive data at rest and in transit, prevent data leakage, and keep regulated data where the rules require.','SEC'],
  ['PR.4','Secure configuration, patching and change management','Apply hardening baselines, patch critical vulnerabilities within defined SLAs, and control changes with testing and approval.','SEC'],
  ['PR.5','Application and API security','Secure the SDLC, test web, mobile and trading applications and APIs before release, and protect against common attacks.','SEC'],
  ['PR.6','Awareness, training and phishing resilience','Provide regular cyber awareness and role-based training and run phishing simulations; protect email and endpoints.','SEC'],
  ['DE.1','Security operations centre and monitoring','Operate a 24x7 SOC (own or managed) with a SIEM, defined use cases and log retention to detect anomalies and attacks in time.','SEC'],
  ['DE.2','Threat intelligence and early warning','Consume and act on threat intelligence and regulator / CERT-In advisories; track emerging threats relevant to the entity.','SEC'],
  ['DE.3','Vulnerability assessment and penetration testing','Run VA and penetration tests of critical systems at the prescribed frequency and after major changes; red-team for higher categories; remediate by risk.','TEST'],
  ['RS.1','Incident response plan and playbooks','Maintain tested incident response plans and playbooks (ransomware, DDoS, data theft, insider) with roles, tooling and evidence handling.','INC'],
  ['RS.2','Incident reporting within 6 hours','Report cyber incidents and suspected incidents to SEBI / the exchange / CERT-In within 6 hours of noticing them, using the prescribed format.','INC'],
  ['RS.3','Root cause analysis within 14 days','Submit a root-cause analysis and corrective actions for each incident within 14 days, and track lessons learned.','INC'],
  ['RC.1','Business continuity, disaster recovery and RTO / RPO','Define RTO and RPO for critical services, maintain a DR site and conduct DR drills at the prescribed frequency.','RES'],
  ['RC.2','Backups and recovery assurance','Maintain secure, offline or immutable backups and test restoration regularly, including from ransomware scenarios.','RES'],
  ['RC.3','Stakeholder and regulator communication','Pre-agree communication to clients, exchanges and regulators during and after an incident or disruption.','RES'],
  ['TP.1','Outsourcing, cloud and managed service providers','Apply due diligence, contractual security and audit rights, data location and exit plans for outsourced, cloud and managed services; follow the SEBI cloud framework.','TPR'],
  ['TP.2','Vendor compliance attestation','Require vendors and service providers to meet and attest to the CSCRF controls relevant to the services provided, and monitor them.','TPR'],
  ['EV.1','Cyber Capability Index and continuous improvement','Where applicable, assess and report the Cyber Capability Index (CCI) and use audits, incidents and exercises to improve the programme.','TEST']]},
 {id:'sebi-cloud',code:'SEBI Cloud Framework',name:'SEBI Framework for Adoption of Cloud Services by SEBI Regulated Entities (2023)',kind:'Regulator direction',region:'India',sectors:['BFSI'],issuer:'Securities and Exchange Board of India',
  summary:'Governance, security and data requirements when regulated entities use cloud services.',verify:'Confirm applicability, MeitY empanelment and data-localisation expectations in the current circular.',
  obl:[
  ['Governance','Cloud strategy, risk assessment and board oversight','Define a cloud policy and assess risk, criticality and concentration before adopting cloud services; keep management accountable.','GOV'],
  ['Provider','Provider due diligence and empanelment','Use providers that meet the prescribed standards (e.g. MeitY empanelment) and assess their security, resilience and certifications.','TPR'],
  ['Data','Data security, encryption and key custody','Encrypt data and retain control of encryption keys; keep logs and regulated data within the required jurisdiction.','SEC'],
  ['Contract','Contractual safeguards and audit rights','Include security, incident notice, sub-contracting, regulator access and audit rights in cloud contracts.','TPR'],
  ['Exit','Exit, portability and business continuity','Maintain tested exit and migration plans and continuity arrangements for cloud-hosted critical services.','RES'],
  ['Monitoring','Continuous monitoring and reporting','Monitor provider performance, configuration and incidents and report as required.','TEST']]},
 {id:'sebi-lodr',code:'SEBI LODR',name:'SEBI (Listing Obligations and Disclosure Requirements) Regulations, 2015',kind:'Regulator direction',region:'India',sectors:['All','BFSI'],issuer:'Securities and Exchange Board of India',
  summary:'Governance and continuous disclosure rules for listed entities, including risk management and sustainability reporting.',verify:'Several provisions apply to a defined top-listed cohort; confirm applicability.',
  obl:[
  ['Reg. 17','Board composition and committees','Maintain the required mix of executive, non-executive and independent directors and board effectiveness.','GOV'],
  ['Reg. 21','Risk Management Committee','Constitute a Risk Management Committee (where applicable) that reviews risk, cyber security and business continuity frameworks.','GOV'],
  ['Reg. 23','Related party transactions','Obtain approvals and make disclosures for related party transactions per the policy and thresholds.','DISC'],
  ['Reg. 30','Material event disclosure','Disclose material events and information to stock exchanges within the prescribed time (generally 12–24 hours, 30 minutes for board outcomes).','DISC'],
  ['Reg. 33','Financial results','Publish quarterly and annual financial results with limited-review / audit within the specified timelines.','DISC'],
  ['Reg. 34(2)(f)','Business Responsibility and Sustainability Report','Publish BRSR (with assurance for BRSR Core) where applicable, covering ESG disclosures.','DISC'],
  ['Reg. 46','Website disclosures','Keep policies, board composition and required disclosures current on the company website.','DISC']]},
 {id:'irdai-cyber',code:'IRDAI Cyber Guidelines',name:'IRDAI Information and Cyber Security Guidelines (2023)',kind:'Regulator direction',region:'India',sectors:['BFSI'],issuer:'Insurance Regulatory and Development Authority of India',
  summary:'Information and cyber security governance and controls for insurers and insurance intermediaries.',verify:'Confirm applicability and timelines for your licence type.',
  obl:[
  ['Governance','Board-approved policy and CISO','Board-approved information and cyber security policy; designated CISO and an Information Security Committee.','GOV'],
  ['Risk','Risk assessment and data classification','Classify information assets and conduct periodic risk assessments.','RISK'],
  ['Controls','Access, logging and encryption controls','Apply access management, logging and monitoring, encryption and secure configuration controls.','SEC'],
  ['Testing','VAPT and audit','Annual VAPT, independent IS audit and remediation tracking.','TEST'],
  ['Incident','Incident reporting','Report cyber incidents to IRDAI and CERT-In within 6 hours of detection.','INC'],
  ['Outsourcing','Third-party security','Embed security and audit rights in outsourced and cloud arrangements.','TPR']]},
 {id:'certin',code:'CERT-In Directions 2022',name:'India CERT-In Directions under IT Act s.70B(6) (28 April 2022)',kind:'Regulator direction',region:'India',sectors:['All','BFSI'],issuer:'CERT-In (MeitY)',
  summary:'Mandatory cyber incident reporting within 6 hours and log retention for service providers and body corporates.',
  obl:[
  ['Dir. 1–2','Report cyber incidents within 6 hours','Report specified cyber incidents to CERT-In within 6 hours of noticing them, with details to support response.','INC'],
  ['Dir. 3','Synchronise system clocks','Synchronise ICT system clocks to NTP servers of NIC/NPL for reliable log timelines.','SEC'],
  ['Dir. 4','Log retention','Maintain logs of all ICT systems securely for 180 days, within Indian jurisdiction, and provide them on request.','SEC'],
  ['Dir. 5','Point of contact','Designate and notify a point of contact for CERT-In coordination.','GOV']]},
 {id:'nist-csf2',code:'NIST CSF 2.0',name:'NIST Cybersecurity Framework 2.0 (2024)',kind:'Framework',region:'Global',sectors:['All','BFSI'],issuer:'NIST (US)',
  summary:'Outcome-based cybersecurity framework with six functions: Govern, Identify, Protect, Detect, Respond, Recover.',
  obl:[
  ['GV.OC','Organizational context','Understand mission, stakeholders, and legal/regulatory requirements that shape cyber risk decisions.','GOV'],
  ['GV.RM','Risk management strategy','Establish risk appetite, tolerance and strategy for cybersecurity risk.','RISK'],
  ['GV.RR','Roles, responsibilities and authorities','Assign and communicate cyber roles with accountability and resources.','GOV'],
  ['GV.PO','Policy','Establish, communicate and review cybersecurity policy.','GOV'],
  ['GV.OV','Oversight','Use results of cyber risk management to inform strategy and adjust direction.','GOV'],
  ['GV.SC','Cybersecurity supply chain risk management','Identify, assess and manage supplier cyber risk across the lifecycle.','TPR'],
  ['ID.AM','Asset management','Inventory hardware, software, services, data and suppliers and prioritise by criticality.','RISK'],
  ['ID.RA','Risk assessment','Understand cyber risk to operations, assets and individuals through threat and vulnerability analysis.','RISK'],
  ['ID.IM','Improvement','Identify improvements from evaluations, tests and incidents.','TEST'],
  ['PR.AA','Identity management, authentication and access control','Limit access to authorised users, services and hardware, managed by risk.','SEC'],
  ['PR.AT','Awareness and training','Provide cybersecurity awareness and role-based training.','SEC'],
  ['PR.DS','Data security','Protect data at rest, in transit and in use according to risk.','SEC'],
  ['PR.PS','Platform security','Manage hardware, software and services securely, including configuration, patching and logging.','SEC'],
  ['PR.IR','Technology infrastructure resilience','Manage security architecture to protect asset confidentiality, integrity and availability and organisational resilience.','RES'],
  ['DE.CM','Continuous monitoring','Monitor assets for anomalies and adverse events.','SEC'],
  ['DE.AE','Adverse event analysis','Analyse anomalies to characterise events and declare incidents.','INC'],
  ['RS.MA','Incident management','Manage responses to detected incidents, including triage, escalation and recovery coordination.','INC'],
  ['RS.AN','Incident analysis','Investigate to ensure effective response and support forensics and recovery.','INC'],
  ['RS.CO','Incident response reporting and communication','Coordinate response activities with internal and external stakeholders.','INC'],
  ['RS.MI','Incident mitigation','Perform activities to prevent expansion and reduce impact.','INC'],
  ['RC.RP','Incident recovery plan execution','Execute restoration activities to ensure operational availability.','RES'],
  ['RC.CO','Incident recovery communication','Coordinate restoration communication with stakeholders.','RES']]},
 {id:'nist-800-53',code:'NIST SP 800-53 r5',name:'NIST SP 800-53 Revision 5 – Security and Privacy Controls',kind:'Framework',region:'Global (US federal origin)',sectors:['All'],issuer:'NIST (US)',
  summary:'Catalogue of security and privacy controls organised into 20 families; widely used as a control library.',
  obl:[
  ['AC','Access control','Limit system access to authorised users, processes and devices, and enforce least privilege.','SEC'],
  ['AT','Awareness and training','Train personnel on security and privacy responsibilities.','SEC'],
  ['AU','Audit and accountability','Create, protect and review audit records.','SEC'],
  ['CA','Assessment, authorization and monitoring','Assess controls, authorise systems and monitor continuously.','TEST'],
  ['CM','Configuration management','Establish and maintain baseline configurations and control changes.','SEC'],
  ['CP','Contingency planning','Plan for, test and execute contingency and recovery operations.','RES'],
  ['IA','Identification and authentication','Identify and authenticate users, devices and services.','SEC'],
  ['IR','Incident response','Establish incident handling capability: preparation, detection, analysis, containment, recovery.','INC'],
  ['MA','Maintenance','Perform and control system maintenance securely.','SEC'],
  ['MP','Media protection','Protect, sanitise and control media.','SEC'],
  ['PE','Physical and environmental protection','Control physical access and protect facilities and equipment.','SEC'],
  ['PL','Planning','Develop security and privacy plans and rules of behaviour.','GOV'],
  ['PM','Program management','Run an enterprise security and privacy program.','GOV'],
  ['PS','Personnel security','Screen personnel and manage terminations and transfers.','SEC'],
  ['PT','PII processing and transparency','Manage processing of personally identifiable information and transparency.','PRIV'],
  ['RA','Risk assessment','Assess risk and vulnerabilities, and use results in decisions.','RISK'],
  ['SA','System and services acquisition','Allocate resources, apply secure development and manage acquisitions.','TPR'],
  ['SC','System and communications protection','Protect boundaries, communications and cryptography.','SEC'],
  ['SI','System and information integrity','Identify and correct flaws, protect from malware and monitor.','SEC'],
  ['SR','Supply chain risk management','Manage supply chain risk through policies, vendor assessment and monitoring.','TPR']]},
 {id:'nist-ai-rmf',code:'NIST AI RMF 1.0',name:'NIST AI Risk Management Framework (2023)',kind:'Framework',region:'Global',sectors:['All','BFSI'],issuer:'NIST (US)',
  summary:'Voluntary framework to manage risks of AI systems across four functions.',
  obl:[
  ['GOVERN','Governance of AI risk','Cultivate a risk-aware culture with policies, accountability, workforce diversity and third-party AI oversight.','AI'],
  ['MAP','Map context and risks','Establish context, intended use, stakeholders and potential impacts for each AI system.','AI'],
  ['MEASURE','Measure and test','Analyse, test and track AI risks using validated metrics and independent assessment.','AI'],
  ['MANAGE','Manage and respond','Prioritise, treat and monitor AI risks, with incident response and decommissioning plans.','AI']]},
 {id:'iso27001',code:'ISO/IEC 27001:2022',name:'ISO/IEC 27001:2022 Information security management systems',kind:'Standard',region:'Global',sectors:['All','BFSI'],issuer:'ISO / IEC',
  summary:'Requirements for an information security management system (ISMS) with a risk-based set of Annex A controls.',
  obl:[
  ['Cl. 4','Context of the organisation','Determine internal/external issues, interested parties and ISMS scope.','GOV'],
  ['Cl. 5','Leadership','Top management commitment, information security policy and assigned roles.','GOV'],
  ['Cl. 6.1','Risk assessment and treatment','Define and apply a risk assessment and treatment process; produce a Statement of Applicability.','RISK'],
  ['Cl. 7','Support','Provide resources, competence, awareness, communication and documented information.','GOV'],
  ['Cl. 8','Operation','Plan and run processes; perform risk assessments and implement the treatment plan.','SEC'],
  ['Cl. 9','Performance evaluation','Monitor and measure, run internal audit and management review.','TEST'],
  ['Cl. 10','Improvement','Handle nonconformities and corrective action; continually improve.','TEST'],
  ['A.5','Organizational controls','Policies, roles, asset management, access control, supplier relationships, incident management, continuity and compliance.','SEC'],
  ['A.6','People controls','Screening, terms of employment, awareness, discipline and remote working.','SEC'],
  ['A.7','Physical controls','Secure areas, equipment security, clear desk and media handling.','SEC'],
  ['A.8','Technological controls','Endpoint, privileged access, authentication, malware, vulnerability, backup, logging, network and secure development controls.','SEC']]},
 {id:'pci-dss',code:'PCI DSS v4.0.1',name:'Payment Card Industry Data Security Standard v4.0.1',kind:'Standard',region:'Global',sectors:['BFSI'],issuer:'PCI Security Standards Council',
  summary:'Security requirements for entities that store, process or transmit payment card data.',verify:'Future-dated v4.0 requirements became mandatory on 31 March 2025.',
  obl:[
  ['Req. 1','Install and maintain network security controls','Control traffic between trusted and untrusted networks and the cardholder data environment.','SEC'],
  ['Req. 2','Apply secure configurations','Remove vendor defaults and harden systems.','SEC'],
  ['Req. 3','Protect stored account data','Minimise retention, mask and render PAN unreadable, and manage cryptographic keys.','SEC'],
  ['Req. 4','Protect cardholder data in transit','Use strong cryptography over open public networks.','SEC'],
  ['Req. 5','Protect against malware','Deploy and maintain anti-malware and phishing protections.','SEC'],
  ['Req. 6','Develop and maintain secure systems and software','Patch promptly, secure the SDLC, and protect web applications.','SEC'],
  ['Req. 7','Restrict access by business need to know','Limit access to system components and data to the minimum necessary.','SEC'],
  ['Req. 8','Identify users and authenticate access','Unique IDs, strong authentication and MFA for access to the CDE.','SEC'],
  ['Req. 9','Restrict physical access','Control physical access to cardholder data and systems.','SEC'],
  ['Req. 10','Log and monitor all access','Log, review and retain audit trails for at least 12 months.','SEC'],
  ['Req. 11','Test security regularly','Quarterly scans, annual penetration tests, change-detection and segmentation testing.','TEST'],
  ['Req. 12','Support information security with policies and programs','Policy, risk assessment, awareness, incident response plan and third-party service provider management.','GOV']]},
 {id:'soc2',code:'SOC 2 (TSC)',name:'AICPA SOC 2 Trust Services Criteria',kind:'Standard',region:'Global (US origin)',sectors:['All','BFSI'],issuer:'AICPA',
  summary:'Attestation criteria for service organisations across security, availability, processing integrity, confidentiality and privacy.',
  obl:[
  ['CC1–CC2','Control environment, communication and information','Demonstrate integrity, board oversight, accountability and effective internal/external communication.','GOV'],
  ['CC3','Risk assessment','Specify objectives, identify and analyse risks including fraud and change.','RISK'],
  ['CC4–CC5','Monitoring and control activities','Evaluate controls on an ongoing basis and deploy policies and procedures through technology controls.','TEST'],
  ['CC6','Logical and physical access','Restrict logical and physical access and manage the lifecycle of credentials and data.','SEC'],
  ['CC7','System operations','Detect and respond to anomalies and security incidents, and recover.','INC'],
  ['CC8','Change management','Authorise, test and approve changes to infrastructure and software.','SEC'],
  ['CC9','Risk mitigation','Mitigate business disruption risk and manage vendor and business-partner risk.','TPR'],
  ['A1','Availability','Capacity, environmental protections, backup and recovery to meet availability commitments.','RES'],
  ['C1','Confidentiality','Identify and protect confidential information and dispose of it per policy.','PRIV'],
  ['P1–P8','Privacy','Notice, choice and consent, collection, use, retention, access, disclosure, quality and monitoring.','PRIV']]},
 {id:'cobit',code:'COBIT 2019',name:'ISACA COBIT 2019 – Governance and Management of Enterprise IT',kind:'Framework',region:'Global',sectors:['All','BFSI'],issuer:'ISACA',
  summary:'IT governance framework with a governance domain (EDM) and four management domains.',
  obl:[
  ['EDM','Evaluate, Direct and Monitor','Governance: ensure benefits realisation, risk optimisation, resource optimisation and stakeholder engagement.','GOV'],
  ['APO','Align, Plan and Organize','Manage strategy, enterprise architecture, budget, risk, security, vendors and data.','GOV'],
  ['BAI','Build, Acquire and Implement','Manage programmes, requirements, change, knowledge and configuration.','SEC'],
  ['DSS','Deliver, Service and Support','Manage operations, incidents, continuity, security services and business process controls.','RES'],
  ['MEA','Monitor, Evaluate and Assess','Monitor performance, internal control and external-requirement compliance.','TEST']]},
 {id:'fatf',code:'FATF 40 Recs',name:'FATF Recommendations (AML / CFT / CPF)',kind:'Standard',region:'Global',sectors:['BFSI'],issuer:'Financial Action Task Force',
  summary:'International standards for combating money laundering, terrorist financing and proliferation financing.',
  obl:[
  ['R.1','Risk-based approach','Identify, assess and understand ML/TF risks and apply resources in proportion to the risk.','FC'],
  ['R.10','Customer due diligence','Identify and verify customers and beneficial owners and understand the nature of the relationship.','FC'],
  ['R.11','Record keeping','Keep transaction and CDD records for at least five years.','DISC'],
  ['R.12','Politically exposed persons','Apply enhanced measures to domestic and foreign PEPs.','FC'],
  ['R.13','Correspondent banking','Apply enhanced due diligence to cross-border correspondent relationships.','FC'],
  ['R.16','Wire transfers','Include required originator and beneficiary information with transfers.','FC'],
  ['R.20','Reporting of suspicious transactions','Promptly report suspicious transactions to the financial intelligence unit.','FC'],
  ['R.24–25','Beneficial ownership transparency','Ensure adequate, accurate and timely information on beneficial owners of legal persons and arrangements.','FC']]},
 {id:'basel',code:'Basel (BCBS 239 & Op Res)',name:'Basel Committee: BCBS 239, Operational Resilience and Operational Risk principles',kind:'Standard',region:'Global',sectors:['BFSI'],issuer:'Basel Committee on Banking Supervision',
  summary:'Principles for risk data aggregation and reporting, operational resilience and sound operational risk management.',
  obl:[
  ['BCBS 239 P1–P3','Governance, architecture and data quality','Strong governance for risk data; integrated data architecture; accurate and reliable data with controls.','DISC'],
  ['BCBS 239 P4–P6','Completeness, timeliness and adaptability','Capture all material risks; generate data promptly, including in stress; adapt to ad hoc requests.','DISC'],
  ['BCBS 239 P7–P11','Risk reporting practices','Accurate, comprehensive, clear, frequent and distributed risk reports to the right recipients.','DISC'],
  ['BCBS 239 P12–P14','Supervisory review','Be ready for supervisory review, remediation and cooperation among authorities.','TEST'],
  ['Op Res P1–P2','Governance and operational risk management','Board oversees resilience; align resilience with the operational risk framework.','RES'],
  ['Op Res P3–P4','Business continuity and mapping','Identify critical operations, set impact tolerances and map people, processes, technology and dependencies.','RES'],
  ['Op Res P5–P6','Third-party dependencies and incident management','Manage third-party dependencies and maintain incident response and recovery plans.','TPR'],
  ['Op Res P7','Resilient ICT including cyber','Implement ICT, including cyber security, that supports critical operations.','RES']]},
 {id:'nis2',code:'NIS2',name:'EU NIS2 Directive (2022/2555)',kind:'Law',region:'EU',sectors:['All','BFSI'],issuer:'European Union',
  summary:'Cyber risk management and reporting duties for essential and important entities across sectors.',verify:'Applies via national transposition; check member-state law. DORA is lex specialis for EU financial entities.',
  obl:[
  ['Art. 20','Management body accountability','Management approves cyber risk measures, oversees implementation, can be held liable, and undergoes training.','GOV'],
  ['Art. 21','Cyber risk-management measures','Take appropriate technical, operational and organisational measures: risk analysis, incident handling, continuity, supply chain security, vulnerability handling, cryptography, access control.','SEC'],
  ['Art. 23','Incident reporting','Early warning within 24 hours, incident notification within 72 hours, and a final report within one month of significant incidents.','INC'],
  ['Art. 21(2)(d)','Supply chain security','Address security in relationships with direct suppliers and service providers.','TPR']]},
 {id:'iso22301',code:'ISO 22301:2019',name:'ISO 22301:2019 Business continuity management systems',kind:'Standard',region:'Global',sectors:['All','BFSI'],issuer:'ISO',
  summary:'Requirements for a business continuity management system (BCMS).',
  obl:[
  ['Cl. 4–5','Context, scope, leadership and policy','Define the BCMS scope and obtain leadership commitment and a BC policy.','GOV'],
  ['Cl. 8.2','Business impact analysis and risk assessment','Identify prioritised activities, recovery time objectives, dependencies and disruption risks.','RES'],
  ['Cl. 8.3','Business continuity strategies and solutions','Select and resource strategies to protect prioritised activities and meet RTOs.','RES'],
  ['Cl. 8.4','Business continuity plans and procedures','Document incident response structure, warning and communication, and recovery procedures.','RES'],
  ['Cl. 8.5','Exercise programme','Exercise and test plans at planned intervals and act on the results.','TEST'],
  ['Cl. 9–10','Performance evaluation and improvement','Monitor, audit, review and improve the BCMS.','TEST']]},
 {id:'iso42001',code:'ISO/IEC 42001:2023',name:'ISO/IEC 42001:2023 Artificial intelligence management system',kind:'Standard',region:'Global',sectors:['All','BFSI'],issuer:'ISO / IEC',
  summary:'Requirements for establishing and improving an AI management system.',
  obl:[
  ['Cl. 4–5','Context, leadership and AI policy','Define AI scope, stakeholders and obtain leadership commitment with an AI policy.','AI'],
  ['Cl. 6','AI risk and impact assessment','Assess AI risks and the impact of AI systems on individuals and society and plan treatments.','AI'],
  ['Cl. 8','AI system lifecycle controls','Control design, data, testing, deployment, monitoring and third-party AI.','AI'],
  ['Cl. 9–10','Evaluation and improvement','Monitor, audit and continually improve the AI management system.','TEST']]},
 {id:'sox',code:'SOX 302 / 404',name:'US Sarbanes-Oxley Act – Sections 302 and 404 (internal control over financial reporting)',kind:'Law',region:'US-listed entities',sectors:['All','BFSI'],issuer:'US Congress / SEC / PCAOB',
  summary:'Management certification and assessment of internal control over financial reporting.',
  obl:[
  ['s.302','CEO / CFO certification','Certify financial reports and the effectiveness of disclosure controls and report deficiencies to auditors and the audit committee.','DISC'],
  ['s.404(a)','Management assessment of ICFR','Document, test and assess internal control over financial reporting annually.','TEST'],
  ['s.404(b)','Auditor attestation','Support the external auditor’s attestation on ICFR (for accelerated filers).','TEST'],
  ['IT GC','IT general controls','Operate and evidence access, change management and operations controls over financially relevant systems.','SEC']]},
 {id:'iso31000',code:'ISO 31000:2018',name:'ISO 31000:2018 Risk management – Guidelines',kind:'Standard',region:'Global',sectors:['All','BFSI'],issuer:'ISO',
  summary:'Principles, framework and process for managing risk in any organisation.',
  obl:[
  ['Principles','Integrated, structured, customised, dynamic','Embed risk management in governance and decision-making, tailored to context and responsive to change.','RISK'],
  ['Framework','Leadership, integration, design, implementation, evaluation, improvement','Provide mandate, resources and accountabilities for risk management and keep the framework improving.','GOV'],
  ['Process','Scope, assess, treat, monitor, communicate','Apply a consistent process: establish context, identify, analyse and evaluate risk, treat, record and report, monitor and review.','RISK']]}
 ]
};
