// Clause-level layer for the major frameworks: individual clauses, criteria, controls, principles and articles.
// Each entry is [reference, title, plain-language requirement, theme]. Summaries only, not the standard's text:
// verify against the official document you license or the legal text.
(function(){
const L=window.GRC_LIB;if(!L)return;
const set=(id,rows)=>{const f=L.frameworks.find(x=>x.id===id);if(f)f.clauses=rows};
// ---------------------------------------------------------------- ISO/IEC 27001:2022
set('iso27001',[
 ['Cl. 4.1','Understanding the organization and its context','Determine external and internal issues that affect the ISMS achieving its intended outcomes.','GOV'],
 ['Cl. 4.2','Needs and expectations of interested parties','Identify interested parties, their requirements and which become ISMS requirements.','GOV'],
 ['Cl. 4.3','Scope of the ISMS','Define and document the boundaries and applicability of the ISMS.','GOV'],
 ['Cl. 4.4','Information security management system','Establish, implement, maintain and continually improve the ISMS.','GOV'],
 ['Cl. 5.1','Leadership and commitment','Top management demonstrates leadership, integrates the ISMS into processes and provides resources.','GOV'],
 ['Cl. 5.2','Policy','Establish an information security policy suited to the organisation and communicate it.','GOV'],
 ['Cl. 5.3','Organizational roles, responsibilities and authorities','Assign and communicate ISMS roles, including reporting on performance.','GOV'],
 ['Cl. 6.1.1','Actions to address risks and opportunities: general','Plan actions for risks and opportunities, integrate them and evaluate effectiveness.','RISK'],
 ['Cl. 6.1.2','Information security risk assessment','Define criteria and perform repeatable risk assessments with owners and levels.','RISK'],
 ['Cl. 6.1.3','Information security risk treatment','Choose treatment options, determine necessary controls, and produce the Statement of Applicability and treatment plan.','RISK'],
 ['Cl. 6.2','Information security objectives and planning','Set measurable security objectives and plan how to achieve them.','GOV'],
 ['Cl. 6.3','Planning of changes','Carry out changes to the ISMS in a planned manner.','GOV'],
 ['Cl. 7.1','Resources','Provide the resources needed for the ISMS.','GOV'],
 ['Cl. 7.2','Competence','Ensure people are competent through education, training or experience.','GOV'],
 ['Cl. 7.3','Awareness','Ensure people know the policy, their contribution and the implications of non-conformity.','SEC'],
 ['Cl. 7.4','Communication','Determine what, when, with whom and how to communicate about the ISMS.','GOV'],
 ['Cl. 7.5','Documented information','Create, control and maintain documented information required by the standard and the organisation.','DISC'],
 ['Cl. 8.1','Operational planning and control','Plan, implement and control processes and keep outsourced processes under control.','SEC'],
 ['Cl. 8.2','Information security risk assessment (operation)','Perform risk assessments at planned intervals and on significant change.','RISK'],
 ['Cl. 8.3','Information security risk treatment (operation)','Implement the risk treatment plan and retain the results.','RISK'],
 ['Cl. 9.1','Monitoring, measurement, analysis and evaluation','Decide what to measure, how and when, and evaluate ISMS performance.','TEST'],
 ['Cl. 9.2','Internal audit','Conduct internal audits at planned intervals with objective, impartial auditors.','TEST'],
 ['Cl. 9.3','Management review','Top management reviews the ISMS at planned intervals and records decisions.','GOV'],
 ['Cl. 10.1','Continual improvement','Continually improve the suitability, adequacy and effectiveness of the ISMS.','TEST'],
 ['Cl. 10.2','Nonconformity and corrective action','React to nonconformities, determine root cause and correct, then review effectiveness.','TEST'],
 ['A.5.1','Policies for information security','Define, approve, publish and periodically review security policy and topic-specific policies.','GOV'],
 ['A.5.2','Information security roles and responsibilities','Define and allocate security roles and responsibilities.','GOV'],
 ['A.5.3','Segregation of duties','Separate conflicting duties and areas of responsibility.','SEC'],
 ['A.5.4','Management responsibilities','Require personnel to apply security in line with policies and procedures.','GOV'],
 ['A.5.5','Contact with authorities','Maintain contact with relevant authorities.','INC'],
 ['A.5.6','Contact with special interest groups','Maintain contact with security forums and professional associations.','SEC'],
 ['A.5.7','Threat intelligence','Collect and analyse information on threats to produce threat intelligence.','SEC'],
 ['A.5.8','Information security in project management','Integrate security into project management.','RISK'],
 ['A.5.9','Inventory of information and other associated assets','Develop and maintain an inventory of information and associated assets with owners.','RISK'],
 ['A.5.10','Acceptable use of information and other associated assets','Identify, document and implement rules for acceptable use and handling.','SEC'],
 ['A.5.11','Return of assets','Return organisational assets on change or end of employment or agreement.','SEC'],
 ['A.5.12','Classification of information','Classify information by confidentiality, integrity, availability and requirements.','SEC'],
 ['A.5.13','Labelling of information','Label information in line with the classification scheme.','SEC'],
 ['A.5.14','Information transfer','Set rules and agreements for transferring information in all forms.','SEC'],
 ['A.5.15','Access control','Establish and implement rules to control physical and logical access.','SEC'],
 ['A.5.16','Identity management','Manage the full lifecycle of identities.','SEC'],
 ['A.5.17','Authentication information','Control allocation and management of authentication information.','SEC'],
 ['A.5.18','Access rights','Provision, review, modify and remove access rights per policy.','SEC'],
 ['A.5.19','Information security in supplier relationships','Define and implement processes to manage supplier security risk.','TPR'],
 ['A.5.20','Addressing information security within supplier agreements','Establish and agree relevant security requirements with each supplier.','TPR'],
 ['A.5.21','Managing information security in the ICT supply chain','Manage security risks in the ICT products and services supply chain.','TPR'],
 ['A.5.22','Monitoring, review and change management of supplier services','Regularly monitor, review, evaluate and manage change in supplier services.','TPR'],
 ['A.5.23','Information security for use of cloud services','Establish processes for acquisition, use, management and exit from cloud services.','TPR'],
 ['A.5.24','Information security incident management planning and preparation','Plan and prepare incident management with roles, processes and communication.','INC'],
 ['A.5.25','Assessment and decision on information security events','Assess events and decide whether they are incidents.','INC'],
 ['A.5.26','Response to information security incidents','Respond to incidents according to documented procedures.','INC'],
 ['A.5.27','Learning from information security incidents','Use incident knowledge to strengthen controls.','INC'],
 ['A.5.28','Collection of evidence','Identify, collect, acquire and preserve evidence related to security events.','INC'],
 ['A.5.29','Information security during disruption','Plan to maintain security at an appropriate level during disruption.','RES'],
 ['A.5.30','ICT readiness for business continuity','Plan, implement, maintain and test ICT readiness against continuity objectives.','RES'],
 ['A.5.31','Legal, statutory, regulatory and contractual requirements','Identify, document and keep current the applicable requirements.','DISC'],
 ['A.5.32','Intellectual property rights','Protect intellectual property rights.','DISC'],
 ['A.5.33','Protection of records','Protect records from loss, destruction, falsification and unauthorised access.','DISC'],
 ['A.5.34','Privacy and protection of PII','Identify and meet requirements for privacy and protection of personal data.','PRIV'],
 ['A.5.35','Independent review of information security','Review the approach to managing information security independently at intervals.','TEST'],
 ['A.5.36','Compliance with policies, rules and standards for information security','Regularly review compliance with policies, rules and standards.','TEST'],
 ['A.5.37','Documented operating procedures','Document and make available operating procedures to personnel who need them.','SEC'],
 ['A.6.1','Screening','Carry out background verification checks on candidates before joining and ongoing.','SEC'],
 ['A.6.2','Terms and conditions of employment','State security responsibilities in employment agreements.','SEC'],
 ['A.6.3','Information security awareness, education and training','Provide appropriate awareness, education and training with regular updates.','SEC'],
 ['A.6.4','Disciplinary process','Formalise a disciplinary process for security policy violations.','GOV'],
 ['A.6.5','Responsibilities after termination or change of employment','Define security duties that remain valid after termination or change.','SEC'],
 ['A.6.6','Confidentiality or non-disclosure agreements','Identify, document, review and sign confidentiality agreements.','SEC'],
 ['A.6.7','Remote working','Implement security measures when personnel work remotely.','SEC'],
 ['A.6.8','Information security event reporting','Provide a mechanism for personnel to report observed or suspected events promptly.','INC'],
 ['A.7.1','Physical security perimeters','Define and use security perimeters to protect areas with information assets.','SEC'],
 ['A.7.2','Physical entry','Protect secure areas with appropriate entry controls.','SEC'],
 ['A.7.3','Securing offices, rooms and facilities','Design and implement physical security for offices, rooms and facilities.','SEC'],
 ['A.7.4','Physical security monitoring','Continuously monitor premises for unauthorised physical access.','SEC'],
 ['A.7.5','Protecting against physical and environmental threats','Protect against natural disasters and other physical threats.','RES'],
 ['A.7.6','Working in secure areas','Design and implement security measures for working in secure areas.','SEC'],
 ['A.7.7','Clear desk and clear screen','Define and enforce clear desk and clear screen rules.','SEC'],
 ['A.7.8','Equipment siting and protection','Site and protect equipment securely.','SEC'],
 ['A.7.9','Security of assets off-premises','Protect off-site assets.','SEC'],
 ['A.7.10','Storage media','Manage storage media through its lifecycle of acquisition, use, transport and disposal.','SEC'],
 ['A.7.11','Supporting utilities','Protect facilities from power and utility failures.','RES'],
 ['A.7.12','Cabling security','Protect power and data cabling from interception, interference and damage.','SEC'],
 ['A.7.13','Equipment maintenance','Maintain equipment correctly to preserve availability, integrity and confidentiality.','SEC'],
 ['A.7.14','Secure disposal or re-use of equipment','Verify that data and software are removed or overwritten before disposal or re-use.','SEC'],
 ['A.8.1','User endpoint devices','Protect information stored on, processed by or accessible via endpoint devices.','SEC'],
 ['A.8.2','Privileged access rights','Restrict and manage allocation and use of privileged access.','SEC'],
 ['A.8.3','Information access restriction','Restrict access to information and associated assets per policy.','SEC'],
 ['A.8.4','Access to source code','Manage read and write access to source code, tools and libraries.','SEC'],
 ['A.8.5','Secure authentication','Implement secure authentication technologies and procedures.','SEC'],
 ['A.8.6','Capacity management','Monitor and adjust resource use against capacity requirements.','RES'],
 ['A.8.7','Protection against malware','Implement protection against malware supported by user awareness.','SEC'],
 ['A.8.8','Management of technical vulnerabilities','Obtain information on vulnerabilities, evaluate exposure and take action.','SEC'],
 ['A.8.9','Configuration management','Establish, document, implement, monitor and review secure configurations.','SEC'],
 ['A.8.10','Information deletion','Delete information when no longer required.','PRIV'],
 ['A.8.11','Data masking','Use data masking in line with access control and other policies.','PRIV'],
 ['A.8.12','Data leakage prevention','Apply data leakage prevention measures to systems, networks and devices.','SEC'],
 ['A.8.13','Information backup','Maintain and regularly test backup copies.','RES'],
 ['A.8.14','Redundancy of information processing facilities','Implement redundancy to meet availability requirements.','RES'],
 ['A.8.15','Logging','Produce, store, protect and analyse logs.','SEC'],
 ['A.8.16','Monitoring activities','Monitor networks, systems and applications for anomalous behaviour.','SEC'],
 ['A.8.17','Clock synchronization','Synchronise clocks of information processing systems to approved time sources.','SEC'],
 ['A.8.18','Use of privileged utility programs','Restrict and tightly control utility programs that can override controls.','SEC'],
 ['A.8.19','Installation of software on operational systems','Implement procedures to manage software installation on operational systems.','SEC'],
 ['A.8.20','Networks security','Secure, manage and control networks and network devices.','SEC'],
 ['A.8.21','Security of network services','Identify and implement security mechanisms and service levels for network services.','SEC'],
 ['A.8.22','Segregation of networks','Segregate groups of services, users and systems in networks.','SEC'],
 ['A.8.23','Web filtering','Manage access to external websites to reduce exposure to malicious content.','SEC'],
 ['A.8.24','Use of cryptography','Define and implement rules for effective use of cryptography and key management.','SEC'],
 ['A.8.25','Secure development life cycle','Establish and apply rules for secure development.','SEC'],
 ['A.8.26','Application security requirements','Identify, specify and approve security requirements for applications.','SEC'],
 ['A.8.27','Secure system architecture and engineering principles','Establish and apply secure engineering principles.','SEC'],
 ['A.8.28','Secure coding','Apply secure coding principles to software development.','SEC'],
 ['A.8.29','Security testing in development and acceptance','Define and implement security testing in the development lifecycle.','TEST'],
 ['A.8.30','Outsourced development','Direct, monitor and review outsourced system development.','TPR'],
 ['A.8.31','Separation of development, test and production environments','Separate and secure environments.','SEC'],
 ['A.8.32','Change management','Subject changes to information processing facilities and systems to change management.','SEC'],
 ['A.8.33','Test information','Select, protect and manage test information appropriately.','PRIV'],
 ['A.8.34','Protection of information systems during audit testing','Plan and agree audit tests so they minimise disruption.','TEST']]);
// ---------------------------------------------------------------- SOC 2 Trust Services Criteria
set('soc2',[
 ['CC1.1','Commitment to integrity and ethical values','The entity demonstrates a commitment to integrity and ethical values.','GOV'],
 ['CC1.2','Board independence and oversight','The board exercises oversight of internal control, independent of management.','GOV'],
 ['CC1.3','Structures, reporting lines, authorities','Management establishes structures, reporting lines and appropriate authorities and responsibilities.','GOV'],
 ['CC1.4','Competence','The entity attracts, develops and retains competent individuals.','GOV'],
 ['CC1.5','Accountability','The entity holds individuals accountable for internal control responsibilities.','GOV'],
 ['CC2.1','Quality information','The entity obtains or generates and uses relevant, quality information to support internal control.','DISC'],
 ['CC2.2','Internal communication','The entity internally communicates information, including objectives and responsibilities for internal control.','DISC'],
 ['CC2.3','External communication','The entity communicates with external parties about matters affecting internal control.','DISC'],
 ['CC3.1','Objectives','The entity specifies objectives with sufficient clarity to enable identification of risks.','RISK'],
 ['CC3.2','Risk identification and analysis','The entity identifies risks to its objectives and analyses them to decide how to manage them.','RISK'],
 ['CC3.3','Fraud risk','The entity considers the potential for fraud when assessing risks.','RISK'],
 ['CC3.4','Significant change','The entity identifies and assesses changes that could significantly affect internal control.','RISK'],
 ['CC4.1','Ongoing and separate evaluations','The entity selects, develops and performs evaluations to determine whether controls are present and functioning.','TEST'],
 ['CC4.2','Deficiencies','The entity evaluates and communicates deficiencies to those responsible for corrective action.','TEST'],
 ['CC5.1','Control activities','The entity selects and develops control activities that mitigate risks to acceptable levels.','SEC'],
 ['CC5.2','Technology general controls','The entity selects and develops general control activities over technology.','SEC'],
 ['CC5.3','Policies and procedures','The entity deploys control activities through policies that establish expectations and procedures that put them into action.','GOV'],
 ['CC6.1','Logical access security','The entity implements logical access security software, infrastructure and architectures to protect information assets.','SEC'],
 ['CC6.2','User registration and removal','Prior to issuing credentials, the entity registers and authorises users; access is removed when no longer authorised.','SEC'],
 ['CC6.3','Role-based access and least privilege','The entity authorises, modifies or removes access based on roles, least privilege and segregation of duties.','SEC'],
 ['CC6.4','Physical access','The entity restricts physical access to facilities and protected information assets.','SEC'],
 ['CC6.5','Disposal','The entity discontinues logical and physical protections over assets only after they can no longer be read or recovered.','SEC'],
 ['CC6.6','Boundary protection','The entity implements logical access security measures to protect against threats from outside its system boundaries.','SEC'],
 ['CC6.7','Information transmission and movement','The entity restricts transmission, movement and removal of information to authorised parties and protects it in transit.','SEC'],
 ['CC6.8','Malicious software','The entity implements controls to prevent or detect and act upon unauthorised or malicious software.','SEC'],
 ['CC7.1','Detection and vulnerability monitoring','The entity uses detection and monitoring procedures to identify configuration changes and new vulnerabilities.','SEC'],
 ['CC7.2','Anomaly monitoring','The entity monitors system components and operation for anomalies indicative of malicious acts, disasters and errors.','SEC'],
 ['CC7.3','Incident evaluation','The entity evaluates security events to determine whether they are incidents.','INC'],
 ['CC7.4','Incident response','The entity responds to identified security incidents using a defined programme.','INC'],
 ['CC7.5','Incident recovery','The entity identifies, develops and implements activities to recover from security incidents.','INC'],
 ['CC8.1','Change management','The entity authorises, designs, develops, tests, approves and implements changes to infrastructure, data, software and procedures.','SEC'],
 ['CC9.1','Business disruption risk mitigation','The entity identifies, selects and develops risk mitigation activities for business disruptions.','RES'],
 ['CC9.2','Vendor and business partner risk','The entity assesses and manages risks associated with vendors and business partners.','TPR'],
 ['A1.1','Capacity','The entity maintains, monitors and evaluates current processing capacity and use of system components.','RES'],
 ['A1.2','Environmental protection, backup and recovery','The entity authorises, designs, implements and monitors environmental protections, backups and recovery infrastructure.','RES'],
 ['A1.3','Recovery testing','The entity tests recovery plan procedures that support system recovery.','RES'],
 ['C1.1','Confidential information identification','The entity identifies and maintains confidential information to meet its confidentiality objectives.','PRIV'],
 ['C1.2','Confidential information disposal','The entity disposes of confidential information to meet its confidentiality objectives.','PRIV'],
 ['PI1.1','Processing definitions','The entity obtains or generates relevant, quality information about the definitions of processing.','DISC'],
 ['PI1.2','System inputs','The entity implements policies and procedures over system inputs to result in complete and accurate processing.','SEC'],
 ['PI1.3','System processing','The entity implements policies and procedures over system processing to result in products and services meeting specifications.','SEC'],
 ['PI1.4','System outputs','The entity implements policies and procedures to deliver outputs completely, accurately and timely.','SEC'],
 ['PI1.5','Stored items','The entity implements policies and procedures to store inputs, items in processing and outputs completely and accurately.','SEC'],
 ['P1','Notice and communication of objectives','Provide notice to data subjects about privacy practices and objectives.','PRIV'],
 ['P2','Choice and consent','Communicate choices and obtain consent for personal information.','PRIV'],
 ['P3','Collection','Collect personal information only as identified in the notice.','PRIV'],
 ['P4','Use, retention and disposal','Limit use to identified purposes, retain only as needed and dispose securely.','PRIV'],
 ['P5','Access','Give individuals access to review and correct their personal information.','PRIV'],
 ['P6','Disclosure and notification','Disclose to third parties only with consent and notify of breaches and incidents.','INC'],
 ['P7','Quality','Maintain accurate, complete and relevant personal information.','PRIV'],
 ['P8','Monitoring and enforcement','Monitor compliance with privacy commitments and address complaints and disputes.','TEST']]);
// ---------------------------------------------------------------- COBIT 2019 (40 governance and management objectives)
set('cobit',[
 ['EDM01','Ensured governance framework setting and maintenance','Analyse and articulate governance requirements and set up and maintain governance bodies and principles.','GOV'],
 ['EDM02','Ensured benefits delivery','Optimise the value contribution of the business from I&T investments.','GOV'],
 ['EDM03','Ensured risk optimization','Ensure enterprise risk related to I&T does not exceed risk appetite and tolerance.','RISK'],
 ['EDM04','Ensured resource optimization','Ensure adequate and optimal I&T resources and capabilities.','GOV'],
 ['EDM05','Ensured stakeholder engagement','Ensure stakeholders are identified, engaged and receive transparent reporting.','GOV'],
 ['APO01','Managed I&T management framework','Design the management system with processes, policies and structures.','GOV'],
 ['APO02','Managed strategy','Provide a holistic view of the current environment and the I&T strategy.','GOV'],
 ['APO03','Managed enterprise architecture','Establish a common architecture of business, information, data, applications and technology.','GOV'],
 ['APO04','Managed innovation','Maintain awareness of technology trends and exploit them for innovation.','GOV'],
 ['APO05','Managed portfolio','Execute the strategic direction by managing the I&T investment portfolio.','GOV'],
 ['APO06','Managed budget and costs','Manage the I&T financial management activities.','GOV'],
 ['APO07','Managed human resources','Provide a structured approach to optimise human resources.','GOV'],
 ['APO08','Managed relationships','Manage relationships between business and IT in a formal and transparent way.','GOV'],
 ['APO09','Managed service agreements','Align I&T-enabled services and service levels with enterprise needs.','TPR'],
 ['APO10','Managed vendors','Manage I&T-related products and services provided by all types of vendors.','TPR'],
 ['APO11','Managed quality','Define and communicate quality requirements in all processes.','TEST'],
 ['APO12','Managed risk','Continually identify, assess and reduce I&T-related risk.','RISK'],
 ['APO13','Managed security','Define, operate and monitor an information security management system.','SEC'],
 ['APO14','Managed data','Achieve and sustain effective management of the enterprise data assets.','PRIV'],
 ['BAI01','Managed programs','Manage all programmes from the investment portfolio in alignment with strategy.','GOV'],
 ['BAI02','Managed requirements definition','Identify solutions and analyse requirements before acquisition or creation.','GOV'],
 ['BAI03','Managed solutions identification and build','Establish and maintain identified solutions in line with requirements.','SEC'],
 ['BAI04','Managed availability and capacity','Balance current and future needs for availability, performance and capacity.','RES'],
 ['BAI05','Managed organizational change','Maximise the likelihood of successful implementation of change.','GOV'],
 ['BAI06','Managed IT changes','Manage all changes in a controlled manner.','SEC'],
 ['BAI07','Managed IT change acceptance and transitioning','Formally accept and make operational new solutions.','SEC'],
 ['BAI08','Managed knowledge','Maintain the availability of relevant, current, validated and reliable knowledge.','GOV'],
 ['BAI09','Managed assets','Manage I&T assets through their life cycle.','RISK'],
 ['BAI10','Managed configuration','Define and maintain descriptions and relationships between key resources and capabilities.','SEC'],
 ['BAI11','Managed projects','Manage all projects initiated within the enterprise.','GOV'],
 ['DSS01','Managed operations','Coordinate and execute activities required to deliver I&T services.','RES'],
 ['DSS02','Managed service requests and incidents','Provide timely and effective response to user requests and incidents.','INC'],
 ['DSS03','Managed problems','Identify and classify problems and their root causes.','INC'],
 ['DSS04','Managed continuity','Establish and maintain a plan to adapt and respond to disruptions.','RES'],
 ['DSS05','Managed security services','Protect enterprise information to maintain risk at an acceptable level.','SEC'],
 ['DSS06','Managed business process controls','Define and maintain business process controls for information processing.','SEC'],
 ['MEA01','Managed performance and conformance monitoring','Collect, validate and evaluate goals and metrics.','TEST'],
 ['MEA02','Managed system of internal control','Continuously monitor and evaluate the control environment.','TEST'],
 ['MEA03','Managed compliance with external requirements','Evaluate that I&T processes comply with laws, regulations and contractual requirements.','DISC'],
 ['MEA04','Managed assurance','Plan, scope and execute assurance initiatives.','TEST']]);
// ---------------------------------------------------------------- COSO
set('coso-ic',[
 ['P1','Demonstrates commitment to integrity and ethical values','The organisation sets the tone, standards of conduct and addresses deviations in a timely manner.','GOV'],
 ['P2','Exercises oversight responsibility','The board is independent of management and oversees internal control.','GOV'],
 ['P3','Establishes structure, authority and responsibility','Management sets structures, reporting lines and appropriate authorities.','GOV'],
 ['P4','Demonstrates commitment to competence','The organisation attracts, develops and retains competent individuals.','GOV'],
 ['P5','Enforces accountability','The organisation holds individuals accountable for their internal control responsibilities.','GOV'],
 ['P6','Specifies suitable objectives','Objectives are specific enough to identify and assess related risks.','RISK'],
 ['P7','Identifies and analyses risk','The organisation identifies risks across the entity and analyses them to determine how they should be managed.','RISK'],
 ['P8','Assesses fraud risk','The organisation considers the potential for fraud, including incentives, opportunities and rationalisation.','RISK'],
 ['P9','Identifies and analyses significant change','The organisation assesses changes in the external environment, business model and leadership.','RISK'],
 ['P10','Selects and develops control activities','Control activities mitigate risks to acceptable levels and consider segregation of duties.','SEC'],
 ['P11','Selects and develops general controls over technology','General technology controls support achievement of objectives.','SEC'],
 ['P12','Deploys through policies and procedures','Control activities are put into action through policies and procedures.','GOV'],
 ['P13','Uses relevant information','The organisation obtains and uses quality information.','DISC'],
 ['P14','Communicates internally','Internal communication supports the functioning of internal control.','DISC'],
 ['P15','Communicates externally','The organisation communicates with external parties about internal control matters.','DISC'],
 ['P16','Conducts ongoing and/or separate evaluations','The organisation evaluates whether components of internal control are present and functioning.','TEST'],
 ['P17','Evaluates and communicates deficiencies','Deficiencies are communicated to responsible parties and senior management and the board as appropriate.','TEST']]);
set('coso-erm',[
 ['P1','Exercises board risk oversight','The board provides oversight of strategy and carries out governance responsibilities.','GOV'],
 ['P2','Establishes operating structures','The organisation establishes operating structures in pursuit of strategy and business objectives.','GOV'],
 ['P3','Defines desired culture','The organisation defines the desired behaviours that characterise its culture.','GOV'],
 ['P4','Demonstrates commitment to core values','The organisation shows commitment to its core values.','GOV'],
 ['P5','Attracts, develops and retains capable individuals','The organisation builds human capital aligned with strategy.','GOV'],
 ['P6','Analyses business context','The organisation considers the potential effects of the business context on its risk profile.','RISK'],
 ['P7','Defines risk appetite','The organisation defines risk appetite in the context of creating, preserving and realising value.','RISK'],
 ['P8','Evaluates alternative strategies','The organisation evaluates alternative strategies and the potential impact on risk profile.','RISK'],
 ['P9','Formulates business objectives','The organisation considers risk while establishing the business objectives.','RISK'],
 ['P10','Identifies risk','The organisation identifies risk that affects performance of strategy and business objectives.','RISK'],
 ['P11','Assesses severity of risk','The organisation assesses the severity of risk.','RISK'],
 ['P12','Prioritises risks','The organisation prioritises risks as a basis for selecting responses.','RISK'],
 ['P13','Implements risk responses','The organisation identifies and selects risk responses.','RISK'],
 ['P14','Develops portfolio view','The organisation develops and evaluates a portfolio view of risk.','RISK'],
 ['P15','Assesses substantial change','The organisation identifies and assesses changes that may substantially affect strategy and objectives.','TEST'],
 ['P16','Reviews risk and performance','The organisation reviews entity performance and considers risk.','TEST'],
 ['P17','Pursues improvement in enterprise risk management','The organisation pursues improvement of enterprise risk management.','TEST'],
 ['P18','Leverages information and technology','The organisation leverages the entity’s information and technology systems to support ERM.','DISC'],
 ['P19','Communicates risk information','The organisation uses communication channels to support ERM.','DISC'],
 ['P20','Reports on risk, culture and performance','The organisation reports on risk, culture and performance at multiple levels.','DISC']]);
// ---------------------------------------------------------------- ISO 31000:2018
set('iso31000',[
 ['Cl. 4','Principles','Integrated, structured and comprehensive, customised, inclusive, dynamic, best available information, human and cultural factors, continual improvement.','RISK'],
 ['Cl. 5.2','Leadership and commitment','Top management and oversight bodies ensure risk management is integrated and resourced.','GOV'],
 ['Cl. 5.3','Integration','Integrate risk management into governance, strategy, objectives and operations.','GOV'],
 ['Cl. 5.4','Design','Understand the organisation and context, articulate commitment, assign roles, allocate resources and establish communication.','GOV'],
 ['Cl. 5.5','Implementation','Implement the framework with a plan, timing and resources and modify decision making where needed.','RISK'],
 ['Cl. 5.6','Evaluation','Periodically measure framework performance against its purpose and expected behaviour.','TEST'],
 ['Cl. 5.7','Improvement','Continually adapt and improve the suitability, adequacy and effectiveness of the framework.','TEST'],
 ['Cl. 6.2','Communication and consultation','Engage relevant stakeholders at all stages of the process.','DISC'],
 ['Cl. 6.3','Scope, context and criteria','Define scope, internal and external context and risk criteria.','RISK'],
 ['Cl. 6.4.2','Risk identification','Find, recognise and describe risks that might help or prevent achievement of objectives.','RISK'],
 ['Cl. 6.4.3','Risk analysis','Understand the nature and characteristics of risk, including level of risk.','RISK'],
 ['Cl. 6.4.4','Risk evaluation','Compare analysis results with risk criteria to decide where additional action is needed.','RISK'],
 ['Cl. 6.5','Risk treatment','Select and implement options to address risk and assess residual risk.','RISK'],
 ['Cl. 6.6','Monitoring and review','Assure and improve the quality and effectiveness of process design, implementation and outcomes.','TEST'],
 ['Cl. 6.7','Recording and reporting','Document and report risk management activities and outcomes to inform decisions.','DISC']]);
// ---------------------------------------------------------------- ISO/IEC 42001:2023
set('iso42001',[
 ['Cl. 4.1','Understanding the organisation and its context','Determine internal and external issues relevant to the AI management system.','AI'],
 ['Cl. 4.2','Interested parties','Identify interested parties and their requirements regarding AI.','AI'],
 ['Cl. 4.3','Scope of the AIMS','Determine the boundaries and applicability of the AI management system.','AI'],
 ['Cl. 4.4','AI management system','Establish, implement, maintain and continually improve the AIMS.','AI'],
 ['Cl. 5.1','Leadership and commitment','Top management demonstrates leadership and commitment to the AIMS.','AI'],
 ['Cl. 5.2','AI policy','Establish an AI policy appropriate to the organisation’s purpose.','AI'],
 ['Cl. 5.3','Roles, responsibilities and authorities','Assign and communicate AI roles and responsibilities.','AI'],
 ['Cl. 6.1.2','AI risk assessment','Define and apply an AI risk assessment process.','AI'],
 ['Cl. 6.1.3','AI risk treatment','Define an AI risk treatment process and produce a statement of applicability.','AI'],
 ['Cl. 6.1.4','AI system impact assessment','Assess consequences of AI systems for individuals, groups and society.','AI'],
 ['Cl. 6.2','AI objectives and planning to achieve them','Set AI objectives and plan how to achieve them.','AI'],
 ['Cl. 7','Support','Provide resources, competence, awareness, communication and documented information.','AI'],
 ['Cl. 8.1','Operational planning and control','Plan, implement and control the processes needed for the AIMS.','AI'],
 ['Cl. 8.2–8.4','Operational risk assessment, treatment and impact assessment','Perform AI risk assessment, treatment and AI system impact assessment at planned intervals and on change.','AI'],
 ['Cl. 9','Performance evaluation','Monitor, measure, audit internally and review the AIMS.','TEST'],
 ['Cl. 10','Improvement','Continually improve and correct nonconformities.','TEST'],
 ['A.2','Policies related to AI','Document AI policy, align with other policies and review it.','AI'],
 ['A.3','Internal organisation','Define AI roles and responsibilities and a process to report concerns.','AI'],
 ['A.4','Resources for AI systems','Document resources for AI systems: data, tooling, system and computing resources, and human resources.','AI'],
 ['A.5','Assessing impacts of AI systems','Assess and document impacts on individuals, groups and society, including legal and social effects.','AI'],
 ['A.6','AI system life cycle','Define objectives and responsible development, requirements, design, verification and validation, deployment, operation, monitoring and event logs.','AI'],
 ['A.7','Data for AI systems','Manage data for development and enhancement: provenance, quality, acquisition and preparation.','AI'],
 ['A.8','Information for interested parties','Provide system documentation, external reporting, incident communication and information to users.','AI'],
 ['A.9','Use of AI systems','Define processes for responsible use, objectives and intended use of AI systems.','AI'],
 ['A.10','Third-party and customer relationships','Allocate responsibilities, manage suppliers and consider customer expectations for AI.','TPR']]);
// ---------------------------------------------------------------- GDPR articles
set('gdpr',[
 ['Art. 5','Principles relating to processing','Lawfulness, fairness, transparency, purpose limitation, minimisation, accuracy, storage limitation, integrity and confidentiality, accountability.','PRIV'],
 ['Art. 6','Lawfulness of processing','Have a lawful basis for each processing purpose.','PRIV'],
 ['Art. 7','Conditions for consent','Demonstrate consent, make it distinguishable, freely given and as easy to withdraw as to give.','PRIV'],
 ['Art. 8','Child’s consent in relation to information society services','Obtain parental authorisation for children below the applicable age (13–16).','PRIV'],
 ['Art. 9','Special categories of personal data','Do not process special-category data unless a specific condition applies.','PRIV'],
 ['Art. 10','Criminal convictions and offences data','Process only under official authority or authorised by law.','PRIV'],
 ['Art. 11','Processing which does not require identification','Do not collect more data just to identify people to comply.','PRIV'],
 ['Art. 12','Transparent information and communication','Provide concise, intelligible information and facilitate the exercise of rights, replying within one month.','PRIV'],
 ['Art. 13','Information to be provided where data are collected from the data subject','Give identity, purposes, basis, recipients, transfers, retention and rights at collection.','PRIV'],
 ['Art. 14','Information where data have not been obtained from the data subject','Provide required information within a reasonable period, at most one month.','PRIV'],
 ['Art. 15','Right of access','Confirm processing and provide a copy of the data and related information.','PRIV'],
 ['Art. 16','Right to rectification','Correct inaccurate data without undue delay.','PRIV'],
 ['Art. 17','Right to erasure (“right to be forgotten”)','Erase data when grounds apply and inform recipients.','PRIV'],
 ['Art. 18','Right to restriction of processing','Restrict processing in the cases specified.','PRIV'],
 ['Art. 19','Notification obligation regarding rectification, erasure or restriction','Notify each recipient of rectification, erasure or restriction.','PRIV'],
 ['Art. 20','Right to data portability','Provide data in a structured, commonly used, machine-readable format and transmit on request.','PRIV'],
 ['Art. 21','Right to object','Stop processing based on legitimate interest or direct marketing when the individual objects.','PRIV'],
 ['Art. 22','Automated individual decision-making, including profiling','Do not subject people to solely automated decisions with significant effects without safeguards.','AI'],
 ['Art. 24','Responsibility of the controller','Implement appropriate technical and organisational measures and demonstrate compliance.','GOV'],
 ['Art. 25','Data protection by design and by default','Build data protection into processing and default to the least data.','GOV'],
 ['Art. 26','Joint controllers','Set out each joint controller’s responsibilities in an arrangement.','TPR'],
 ['Art. 27','Representatives of controllers not established in the Union','Designate an EU representative where Art. 3(2) applies.','GOV'],
 ['Art. 28','Processor','Use only processors with sufficient guarantees under a binding contract.','TPR'],
 ['Art. 29','Processing under the authority of the controller or processor','Process only on instructions.','TPR'],
 ['Art. 30','Records of processing activities','Maintain records of processing activities.','DISC'],
 ['Art. 31','Cooperation with the supervisory authority','Cooperate with the supervisory authority on request.','GOV'],
 ['Art. 32','Security of processing','Implement appropriate security measures, including encryption, resilience, testing.','SEC'],
 ['Art. 33','Notification of a personal data breach to the supervisory authority','Notify within 72 hours of awareness unless unlikely to result in risk.','INC'],
 ['Art. 34','Communication of a personal data breach to the data subject','Communicate without undue delay where there is high risk.','INC'],
 ['Art. 35','Data protection impact assessment','Assess impact of high-risk processing before starting.','RISK'],
 ['Art. 36','Prior consultation','Consult the supervisory authority where a DPIA indicates high residual risk.','RISK'],
 ['Art. 37','Designation of the data protection officer','Designate a DPO where required.','GOV'],
 ['Art. 38','Position of the data protection officer','Involve the DPO properly, with independence and resources.','GOV'],
 ['Art. 39','Tasks of the data protection officer','Inform, advise, monitor compliance and cooperate with the authority.','GOV'],
 ['Art. 40–43','Codes of conduct and certification','Consider approved codes of conduct and certification to demonstrate compliance.','TEST'],
 ['Art. 44','General principle for transfers','Transfers must keep the level of protection of the GDPR.','PRIV'],
 ['Art. 45','Transfers on the basis of an adequacy decision','Transfer freely to countries with an adequacy decision.','PRIV'],
 ['Art. 46','Transfers subject to appropriate safeguards','Use SCCs, BCRs or other safeguards with enforceable rights.','PRIV'],
 ['Art. 47','Binding corporate rules','Use approved BCRs for intra-group transfers.','PRIV'],
 ['Art. 48','Transfers not authorised by Union law','Foreign court orders are recognised only under an international agreement.','PRIV'],
 ['Art. 49','Derogations for specific situations','Rely on derogations (consent, contract, etc.) only in the limited cases allowed.','PRIV'],
 ['Art. 82–83','Liability and administrative fines','Be aware of liability and fines up to €20m or 4% of worldwide turnover.','GOV']]);
// ---------------------------------------------------------------- HIPAA
set('hipaa',[
 ['164.502','Uses and disclosures: general rules','Use or disclose PHI only as permitted or required, applying minimum necessary.','PRIV'],
 ['164.504','Organisational requirements and business associate contracts','Have compliant business associate contracts and hybrid/affiliated entity arrangements.','TPR'],
 ['164.506','Uses and disclosures for treatment, payment and health care operations','Permitted without authorisation within these purposes.','PRIV'],
 ['164.508','Authorisation','Obtain a valid authorisation for uses and disclosures not otherwise permitted.','PRIV'],
 ['164.510','Opportunity to agree or object','Give individuals the chance to agree or object (e.g. facility directories, family involvement).','PRIV'],
 ['164.512','Uses and disclosures without authorisation','Disclose for public health, law enforcement, judicial proceedings and other defined purposes.','PRIV'],
 ['164.514','De-identification and minimum necessary','De-identify by safe harbour or expert determination; apply limited data set rules.','PRIV'],
 ['164.520','Notice of privacy practices','Provide and publish a notice of privacy practices.','PRIV'],
 ['164.522','Rights to request restrictions and confidential communications','Consider restriction requests and accommodate reasonable confidential communication requests.','PRIV'],
 ['164.524','Access of individuals to PHI','Provide access to designated record sets, generally within 30 days.','PRIV'],
 ['164.526','Amendment of PHI','Handle requests to amend PHI.','PRIV'],
 ['164.528','Accounting of disclosures','Provide an accounting of certain disclosures on request.','PRIV'],
 ['164.530','Administrative requirements','Designate a privacy official, train staff, safeguard PHI, handle complaints, apply sanctions and document.','GOV'],
 ['164.308(a)(1)','Security management process','Risk analysis, risk management, sanction policy and information system activity review.','RISK'],
 ['164.308(a)(2)','Assigned security responsibility','Identify the official responsible for security.','GOV'],
 ['164.308(a)(3)','Workforce security','Authorisation, supervision, clearance and termination procedures.','SEC'],
 ['164.308(a)(4)','Information access management','Isolate clearinghouse functions, authorise access and manage access establishment and modification.','SEC'],
 ['164.308(a)(5)','Security awareness and training','Security reminders, malware protection, log-in monitoring and password management.','SEC'],
 ['164.308(a)(6)','Security incident procedures','Identify, respond to and document security incidents.','INC'],
 ['164.308(a)(7)','Contingency plan','Data backup, disaster recovery and emergency mode operation plans, with testing.','RES'],
 ['164.308(a)(8)','Evaluation','Perform periodic technical and non-technical evaluation.','TEST'],
 ['164.310(a)','Facility access controls','Contingency operations, facility security plan, access control and validation, maintenance records.','SEC'],
 ['164.310(b)–(c)','Workstation use and security','Specify proper use and secure physical attributes of workstations.','SEC'],
 ['164.310(d)','Device and media controls','Disposal, media re-use, accountability and data backup and storage.','SEC'],
 ['164.312(a)','Access control','Unique user identification, emergency access, automatic logoff and encryption.','SEC'],
 ['164.312(b)','Audit controls','Record and examine activity in systems containing ePHI.','SEC'],
 ['164.312(c)','Integrity','Protect ePHI from improper alteration or destruction.','SEC'],
 ['164.312(d)','Person or entity authentication','Verify that the person seeking access is the one claimed.','SEC'],
 ['164.312(e)','Transmission security','Integrity controls and encryption for ePHI in transmission.','SEC'],
 ['164.314','Organisational requirements for the Security Rule','Business associate contracts and group health plan requirements.','TPR'],
 ['164.316','Policies, procedures and documentation','Maintain policies and keep documentation for six years.','DISC'],
 ['164.404','Notification to individuals','Notify affected individuals without unreasonable delay and within 60 days.','INC'],
 ['164.406','Notification to the media','Notify prominent media outlets for breaches affecting more than 500 residents of a state.','INC'],
 ['164.408','Notification to the Secretary','Notify HHS contemporaneously for 500+ and annually for smaller breaches.','INC'],
 ['164.410','Notification by a business associate','Business associates notify the covered entity without unreasonable delay and within 60 days.','INC'],
 ['164.412','Law enforcement delay','Delay notification when law enforcement states it would impede an investigation.','INC']]);
// ---------------------------------------------------------------- PCI DSS v4.0.1
set('pci-dss',[
 ['1.1','Network security controls: processes defined and understood','Define roles and document processes for network security controls.','SEC'],
 ['1.2','Network security controls configured and maintained','Configure, review and keep NSC rulesets and network diagrams current.','SEC'],
 ['1.3','Network access to and from the CDE restricted','Allow only necessary inbound and outbound traffic to the cardholder data environment.','SEC'],
 ['1.4','Connections between trusted and untrusted networks controlled','Control and restrict connections, with anti-spoofing measures.','SEC'],
 ['1.5','Risks from devices that connect to both untrusted networks and the CDE mitigated','Apply security controls to such computing devices.','SEC'],
 ['2.1','Secure configuration: processes defined','Define roles and processes for secure configuration.','SEC'],
 ['2.2','System components configured and managed securely','Use hardened standards, change vendor defaults and enable only necessary services.','SEC'],
 ['2.3','Wireless environments configured and managed securely','Inventory wireless networks, change defaults and use strong encryption.','SEC'],
 ['3.1','Protection of stored account data: processes defined','Define roles and document data retention and security processes.','PRIV'],
 ['3.2','Storage of account data kept to a minimum','Define and enforce retention and disposal.','PRIV'],
 ['3.3','Sensitive authentication data not stored after authorisation','Do not retain SAD after authorisation, even if encrypted.','PRIV'],
 ['3.4','Displays of full PAN and ability to copy restricted','Mask PAN and restrict access to full PAN.','PRIV'],
 ['3.5','PAN secured wherever it is stored','Render PAN unreadable using strong cryptography, hashing or truncation.','SEC'],
 ['3.6','Cryptographic keys used to protect stored data secured','Restrict access to keys and store them securely.','SEC'],
 ['3.7','Key management processes and procedures defined','Generate, distribute, store, rotate, retire and replace keys securely.','SEC'],
 ['4.1','Cryptography in transit: processes defined','Define roles and processes for transmission protection.','SEC'],
 ['4.2','PAN protected with strong cryptography during transmission','Use strong cryptography and trusted certificates over open, public networks.','SEC'],
 ['5.1','Malware protection: processes defined','Define roles and processes for malware protection.','SEC'],
 ['5.2','Malicious software prevented or detected and addressed','Deploy anti-malware on systems commonly affected by malware.','SEC'],
 ['5.3','Anti-malware mechanisms active, maintained and monitored','Keep mechanisms current, running scans and generating logs.','SEC'],
 ['5.4','Anti-phishing mechanisms protect users','Detect and protect personnel against phishing attacks.','SEC'],
 ['6.1','Secure systems and software: processes defined','Define roles and processes for secure development and maintenance.','SEC'],
 ['6.2','Bespoke and custom software developed securely','Train developers and review code before release.','SEC'],
 ['6.3','Security vulnerabilities identified and addressed','Identify, rank and patch vulnerabilities; maintain an inventory of software components.','SEC'],
 ['6.4','Public-facing web applications protected against attacks','Use automated technical solutions (e.g. WAF) or regular assessment; manage payment page scripts.','SEC'],
 ['6.5','Changes to all system components managed securely','Follow change procedures with approval, testing and back-out plans.','SEC'],
 ['7.1','Restrict access by need to know: processes defined','Define roles and processes for restricting access.','SEC'],
 ['7.2','Access appropriately defined and assigned','Define access needs by job function and review regularly.','SEC'],
 ['7.3','Access managed via an access control system','Enforce deny-all by default through an access control system.','SEC'],
 ['8.1','User identification and authentication: processes defined','Define roles and processes for identification and authentication.','SEC'],
 ['8.2','User and administrator accounts strictly managed throughout lifecycle','Unique IDs, controlled use of shared accounts and prompt removal.','SEC'],
 ['8.3','Strong authentication established and managed','Strong passwords or passphrases, secure storage and change controls.','SEC'],
 ['8.4','MFA implemented to secure access into the CDE','Require multi-factor authentication for all access into the CDE and for administrators.','SEC'],
 ['8.5','MFA systems configured to prevent misuse','Prevent replay, bypass and require all factors.','SEC'],
 ['8.6','Application and system accounts strictly managed','Manage interactive use, credentials in code and password changes.','SEC'],
 ['9.1','Physical access: processes defined','Define roles and processes for physical access controls.','SEC'],
 ['9.2','Physical access controls manage entry','Use facility entry controls and monitor sensitive areas.','SEC'],
 ['9.3','Physical access for personnel and visitors authorised and managed','Identify, authorise and log visitors.','SEC'],
 ['9.4','Media with cardholder data securely stored, accessed, distributed and destroyed','Control media handling and destruction.','SEC'],
 ['9.5','POI devices protected from tampering and substitution','Maintain a list of devices and inspect periodically.','SEC'],
 ['10.1','Logging and monitoring: processes defined','Define roles and processes for logging and monitoring.','SEC'],
 ['10.2','Audit logs implemented to support detection and forensics','Log individual access, privileged actions, authentication events and changes.','SEC'],
 ['10.3','Audit logs protected from destruction and unauthorised modification','Limit access and back up logs.','SEC'],
 ['10.4','Audit logs reviewed to identify anomalies','Review logs daily using automated mechanisms and alert on exceptions.','SEC'],
 ['10.5','Audit log history retained and available','Retain 12 months with the most recent 3 months immediately available.','SEC'],
 ['10.6','Time-synchronisation mechanisms','Synchronise time across all critical systems.','SEC'],
 ['10.7','Failures of critical security control systems detected and responded to','Detect, alert and respond to failures promptly.','SEC'],
 ['11.1','Regular testing: processes defined','Define roles and processes for security testing.','TEST'],
 ['11.2','Wireless access points identified and monitored','Detect unauthorised wireless access points at least quarterly.','TEST'],
 ['11.3','Vulnerabilities regularly identified, prioritised and addressed','Run internal and external scans at least quarterly with rescans.','TEST'],
 ['11.4','Penetration testing regularly performed','Perform internal and external penetration tests annually and after significant change.','TEST'],
 ['11.5','Network intrusions and unexpected file changes detected and responded to','Use intrusion detection and change-detection mechanisms.','TEST'],
 ['11.6','Unauthorised changes on payment pages detected and responded to','Detect tampering with payment pages in the consumer browser.','TEST'],
 ['12.1','Information security policy known and current','Establish, publish, maintain and disseminate a security policy; review annually.','GOV'],
 ['12.2','Acceptable use policies for end-user technologies','Define acceptable use and approved technologies.','GOV'],
 ['12.3','Risks to the CDE formally identified, evaluated and managed','Perform targeted risk analyses and review cryptographic suites.','RISK'],
 ['12.4','PCI DSS compliance managed','Assign executive responsibility and perform periodic operational reviews.','GOV'],
 ['12.5','PCI DSS scope documented and validated','Maintain inventory, data-flow diagrams and validate scope annually.','RISK'],
 ['12.6','Security awareness education ongoing','Provide awareness programme at hire and at least annually, including phishing and social engineering.','SEC'],
 ['12.7','Personnel screened to reduce insider threat risks','Screen personnel before hire.','SEC'],
 ['12.8','Risk from third-party service provider relationships managed','Maintain a list of TPSPs, written agreements, due diligence and monitoring.','TPR'],
 ['12.9','TPSPs support customers’ PCI DSS compliance','TPSPs acknowledge responsibility and provide compliance information.','TPR'],
 ['12.10','Suspected and confirmed security incidents responded to immediately','Maintain and test an incident response plan, including alerts from security systems.','INC']]);
})();
