// Phase 3 modules: Cyber & technology risk (assets, NIST CSF maturity, models & AI), Business continuity (BIA, plans),
// Financial crime & conduct (BFSI: AML cases, KYC health, complaints) and Internal audit (plan, coverage, findings).
(function(){
const G=window.GRC;if(!G)return;
const P=G.P,{E,fmt,addDays,dTo,pill,own,table,card,kpi,bar,toolbar,flt,match,toast,logIt,commit,openForm,actions,TODAY,detail,dueState,csv,head,panel,personOpts,raise,me,risks}=G;
const S=()=>G.S(),FREQ={Monthly:30,Quarterly:91,'Semi-annual':182,Annual:365};
const nid=(list,pre,w=2)=>pre+String(list.reduce((m,r)=>Math.max(m,+r.id.replace(/\D/g,'')),0)+1).padStart(w,'0');
const RG='RESILIENCE & TECH RISK',RO='RISK OPERATIONS';
// ---------------------------------------------------------------- seeds
const A={ // assets: [id,name,type,tier,owner,internet,crit,high,lastScan,mfa,enc,ibs]
 bfsi:[['AS-01','Internet banking portal','Application','Tier 1','Sam Rivera',true,2,5,'2026-09-30',true,true,'IBS-02'],['AS-02','Mobile banking app and APIs','Application','Tier 1','Sam Rivera',true,1,4,'2026-09-30',true,true,'IBS-01'],['AS-03','Core banking database','Data store','Tier 1','Sam Rivera',false,0,2,'2026-10-04',true,true,'IBS-02'],['AS-04','Payments switch','Infrastructure','Tier 1','Jordan Lee',false,3,6,'2026-08-14',false,true,'IBS-01'],['AS-05','Trading engine','Application','Tier 1','Evan Brooks',true,0,1,'2026-10-02',true,true,'IBS-04'],['AS-06','Customer analytics data warehouse','Data store','Tier 2','Priya Shah',false,1,7,'2026-07-19',true,false,''],['AS-07','Branch network and ATMs','Network','Tier 2','Sam Rivera',false,4,11,'2026-09-12',false,true,''],['AS-08','Email and collaboration (cloud)','Application','Tier 2','Sam Rivera',true,0,3,'2026-10-01',true,true,'']],
 general:[['AS-01','ERP system','Application','Tier 1','Sam Rivera',false,1,6,'2026-09-28',true,true,''],['AS-02','Customer portal','Application','Tier 1','Sam Rivera',true,2,4,'2026-09-30',true,true,''],['AS-03','Finance database','Data store','Tier 1','Priya Shah',false,0,2,'2026-10-03',true,true,''],['AS-04','Email and collaboration (cloud)','Application','Tier 2','Sam Rivera',true,0,3,'2026-10-01',true,true,''],['AS-05','Office network and VPN','Network','Tier 2','Sam Rivera',true,3,9,'2026-08-05',false,true,''],['AS-06','Endpoint fleet','Infrastructure','Tier 2','Sam Rivera',false,2,14,'2026-09-15',true,false,'']],
 manufacturing:[['AS-01','SCADA / HMI for Line 3','OT system','Tier 1','Sam Rivera',false,3,5,'2026-07-01',false,false,''],['AS-02','PLC network (legacy)','OT system','Tier 1','Sam Rivera',false,5,8,'2026-06-10',false,false,''],['AS-03','MES / production planning','Application','Tier 1','Jordan Lee',false,1,4,'2026-09-20',true,true,''],['AS-04','ERP system','Application','Tier 1','Evan Brooks',false,0,3,'2026-10-01',true,true,''],['AS-05','Vendor remote-access gateway','Network','Tier 1','Sam Rivera',true,2,2,'2026-09-05',true,true,''],['AS-06','Engineering workstations','Infrastructure','Tier 2','Jordan Lee',false,2,10,'2026-08-22',false,false,'']]};
const MAT={bfsi:[['Govern',2.5,3.5],['Identify',2.8,3.5],['Protect',2.6,3.5],['Detect',3.0,3.5],['Respond',2.4,3.5],['Recover',2.0,3.5]],general:[['Govern',2.4,3.5],['Identify',2.6,3.5],['Protect',2.8,3.5],['Detect',2.3,3.5],['Respond',2.2,3.5],['Recover',2.0,3.5]],manufacturing:[['Govern',2.0,3.0],['Identify',2.2,3.0],['Protect',2.3,3.0],['Detect',1.8,3.0],['Respond',2.0,3.0],['Recover',1.8,3.0]]};
const MOD={ // [id,name,type,tier,owner,use,validated,drift,findings,vendor]
 bfsi:[['MD-01','Retail credit scorecard','Statistical','High','Evan Brooks','Credit decisioning','2025-09-15','Stable',1,''],['MD-02','MSME early-warning model','Machine learning','High','Evan Brooks','Credit monitoring','2025-12-04','Drifted',2,''],['MD-03','Fraud detection engine','Vendor model','High','Jordan Lee','Payment fraud','2026-04-22','Watch',0,'PayBridge Switch'],['MD-04','AML transaction-monitoring scenarios','Rules / statistical','High','Jordan Lee','AML monitoring','2026-02-10','Stable',3,''],['MD-05','Expected credit loss (ECL) provisioning model','Statistical','High','Priya Shah','Provisioning','2026-06-30','Stable',0,''],['MD-06','Customer service GenAI assistant','Generative AI','Medium','Sam Rivera','Customer support','','Watch',0,'External LLM provider']],
 general:[['MD-01','Demand forecasting model','Machine learning','Medium','Jordan Lee','Planning','2025-06-10','Watch',1,''],['MD-02','Customer support AI assistant','Generative AI','Medium','Sam Rivera','Support','','Watch',0,'External LLM provider'],['MD-03','Credit-limit scoring','Statistical','High','Priya Shah','Customer credit','2026-03-18','Stable',0,'']],
 manufacturing:[['MD-01','Predictive maintenance model (Line 3)','Machine learning','Medium','Jordan Lee','Maintenance planning','2025-08-01','Watch',1,'']]};
G.seeders.cyber=pid=>({assets:(A[pid]||A.general).map(r=>({id:r[0],name:r[1],type:r[2],tier:r[3],owner:r[4],internet:r[5],crit:r[6],high:r[7],scan:r[8],mfa:r[9],enc:r[10],ibs:r[11]})),maturity:(MAT[pid]||MAT.general).map(r=>({fn:r[0],now:r[1],target:r[2]})),assessed:'2026-09-15',models:(MOD[pid]||MOD.general).map(r=>({id:r[0],name:r[1],type:r[2],tier:r[3],owner:r[4],use:r[5],validated:r[6],drift:r[7],findings:r[8],vendor:r[9]}))});
const BIA={bfsi:[['BIA-01','Retail payments processing','Jordan Lee','Critical',8,4,0.25,'2026-03-02','Payments switch, core banking, cloud hosting'],['BIA-02','Core banking operations','Sam Rivera','Critical',12,6,0.5,'2026-03-02','Core banking platform, cloud hosting, DR site'],['BIA-03','Treasury and liquidity management','Priya Shah','Critical',4,2,0,'2025-08-20','Treasury system, market data feeds'],['BIA-04','Customer onboarding and KYC','Jordan Lee','Important',48,24,4,'2025-09-12','e-KYC API, CRM'],['BIA-05','Customer support and grievance','Morgan Chen','Important',72,24,8,'2026-01-20','Telephony, CRM'],['BIA-06','Regulatory reporting','Morgan Chen','Important',72,80,24,'2025-07-30','Data warehouse, reporting tool']],
 general:[['BIA-01','Order-to-cash','Jordan Lee','Critical',24,12,2,'2026-02-10','ERP, customer portal'],['BIA-02','Payroll and HR','Morgan Chen','Important',72,48,24,'2025-09-01','HRMS, payroll provider'],['BIA-03','Customer support','Priya Shah','Important',48,24,8,'2025-06-20','Telephony, CRM']],
 manufacturing:[['BIA-01','Production Line 3 operation','Jordan Lee','Critical',24,12,1,'2026-01-15','SCADA, compressed air, power'],['BIA-02','Dispatch and logistics','Evan Brooks','Important',48,24,4,'2025-08-02','ERP, transport partners'],['BIA-03','Effluent treatment operation','Priya Shah','Critical',24,8,0,'2025-07-10','ETP, power, permits']]};
const PLN={bfsi:[['BCP-01','Core banking DR plan','Core banking, DR site','Sam Rivera','4.2','2026-05-20','Passed with findings','Semi-annual','Approved'],['BCP-02','Payments switch failover plan','Payments switch and UPI gateway','Jordan Lee','3.0','2026-05-20','Passed','Semi-annual','Approved'],['BCP-03','Branch and people continuity','Site loss, pandemic, strikes','Morgan Chen','2.1','2025-04-15','Passed','Annual','Approved'],['BCP-04','Cyber crisis management plan','Ransomware and destructive attacks','Sam Rivera','2.5','2026-08-10','Passed with findings','Annual','Approved'],['BCP-05','Treasury continuity plan','Treasury and liquidity','Priya Shah','1.3','','Not tested','Annual','Draft']],
 general:[['BCP-01','Business continuity plan','Head office and ERP','Jordan Lee','1.2','2025-11-20','Passed with findings','Annual','Approved'],['BCP-02','IT disaster recovery plan','ERP, email, portal','Sam Rivera','2.0','','Not tested','Annual','Draft']],
 manufacturing:[['BCP-01','Plant business continuity plan','Site loss and utility failure','Jordan Lee','2.2','2025-10-05','Passed','Annual','Approved'],['BCP-02','Fire and chemical emergency plan','Plant 01','Priya Shah','3.1','2026-02-14','Passed with findings','Annual','Approved']]};
G.seeders.bcp=pid=>({bia:(BIA[pid]||BIA.general).map(r=>({id:r[0],process:r[1],owner:r[2],crit:r[3],mtpd:r[4],rto:r[5],rpo:r[6],review:r[7],deps:r[8]})),plans:(PLN[pid]||PLN.general).map(r=>({id:r[0],name:r[1],scope:r[2],owner:r[3],ver:r[4],last:r[5],result:r[6],freq:r[7],status:r[8]}))});
G.seeders.fc=pid=>pid!=='bfsi'?{cases:[],kyc:[],complaints:[],screening:{}}:{
 cases:[['AML-401','Transaction-monitoring alert · structuring','Customer #55217','High','2026-09-08','','Investigating','Jordan Lee',4850000],['AML-402','Suspected mule account cluster','Customer cluster (14 accounts)','High','2026-10-01','2026-10-07','Escalated','Jordan Lee',2200000],['AML-403','Sanctions screening potential match','Customer #81230','High','2026-10-09','','Investigating','Priya Shah',0],['AML-404','Unusual cash deposits','Customer #20991','Medium','2026-08-20','2026-09-02','STR filed','Jordan Lee',1200000],['AML-405','Card chargeback pattern','Merchant M-4412','Medium','2026-09-28','','Open','Jordan Lee',640000],['AML-406','PEP onboarding review','Customer #99012','High','2026-09-14','','Open','Priya Shah',0]].map(r=>({id:r[0],type:r[1],who:r[2],risk:r[3],opened:r[4],suspicion:r[5],status:r[6],analyst:r[7],amount:r[8],strFiled:r[6]==='STR filed'?'2026-09-06':''})),
 kyc:[['High','2 years',12400,900,310],['Medium','8 years',210000,6800,1900],['Low','10 years',1410000,21000,2600]].map(r=>({band:r[0],interval:r[1],cust:r[2],due:r[3],overdue:r[4]})),
 screening:{last:'2026-10-11',pep:340,open:5},
 complaints:[['CMP-501','Digital','Unauthorised transaction','2026-09-12','Open','Jordan Lee',48000,false],['CMP-502','Branch','Mis-selling (insurance)','2026-08-30','Open','Morgan Chen',150000,true],['CMP-503','Call centre','Charges dispute','2026-10-05','Open','Morgan Chen',1200,false],['CMP-504','Digital','App outage during payment','2026-09-20','Resolved','Jordan Lee',0,false],['CMP-505','Email','Loan statement error','2026-10-08','Open','Evan Brooks',0,false],['CMP-506','Branch','Conduct during KYC re-verification','2026-09-02','Open','Jordan Lee',0,false]].map(r=>({id:r[0],channel:r[1],category:r[2],received:r[3],status:r[4],owner:r[5],amount:r[6],ombudsman:r[7]}))};
const AUD={bfsi:[['IA-01','IT general controls and change management','Technology & cyber','Q3','High','Complete','Priya Shah','2026-07-06','2026-08-14',3,'Needs improvement',[]],['IA-02','AML / KYC programme effectiveness','Financial crime','Q3','High','Reporting','Priya Shah','2026-08-24','2026-10-02',2,'Unsatisfactory',['F-051','F-049']],['IA-03','Outsourcing and third-party governance','Third party & outsourcing','Q4','High','Fieldwork','Evan Brooks','2026-09-21','2026-10-30',1,'',['F-047','F-055']],['IA-04','Privacy and data protection (DPDP readiness)','Privacy & data','Q4','High','Fieldwork','Priya Shah','2026-10-05','2026-11-13',1,'',['F-044']],['IA-05','Treasury and liquidity risk','Market & liquidity','Q4','Medium','Planned','Evan Brooks','2026-11-02','2026-11-27',0,'',['F-041']],['IA-06','Business continuity and disaster recovery','Technology & cyber','Q1 2027','High','Planned','Priya Shah','2027-01-11','2027-02-05',0,'',['F-038']],['IA-07','Credit underwriting and model risk','Credit risk','Q1 2027','Medium','Planned','Evan Brooks','2027-02-08','2027-03-05',0,'',[]]],
 general:[['IA-01','Financial close and ICFR','Financial','Q3','High','Complete','Priya Shah','2026-07-13','2026-08-21',2,'Needs improvement',[]],['IA-02','Access management for finance systems','Technology & cyber','Q3','High','Reporting','Priya Shah','2026-08-31','2026-09-25',1,'Needs improvement',['F-021']],['IA-03','Supplier management','Third party','Q4','Medium','Fieldwork','Morgan Chen','2026-10-05','2026-11-06',1,'',['F-019']],['IA-04','Privacy compliance','Compliance & legal','Q4','High','Planned','Priya Shah','2026-11-09','2026-12-04',0,'',['F-017']]],
 manufacturing:[['IA-01','Safety management system','Production','Q3','High','Complete','Priya Shah','2026-07-06','2026-08-07',2,'Satisfactory',[]],['IA-02','Environmental compliance and permits','Environment','Q3','High','Reporting','Priya Shah','2026-08-31','2026-09-25',2,'Needs improvement',[]],['IA-03','OT cybersecurity and access','Cybersecurity','Q4','High','Fieldwork','Morgan Chen','2026-10-05','2026-11-06',1,'',[]],['IA-04','Supplier quality and continuity','Supply chain','Q4','Medium','Planned','Morgan Chen','2026-11-09','2026-12-04',0,'',[]]]};
G.seeders.audit=pid=>({plan:(AUD[pid]||AUD.general).map(r=>({id:r[0],title:r[1],area:r[2],qtr:r[3],risk:r[4],status:r[5],lead:r[6],start:r[7],end:r[8],findings:r[9],rating:r[10],fids:r[11]}))});
// ---------------------------------------------------------------- mount
G.mount({id:'cyber',label:'Cyber & tech risk',ico:'⌨',group:RG,title:'Cyber & technology risk',sub:'Critical assets and their exposure, NIST CSF 2.0 maturity against target, and the model and AI inventory with validation status.',tabs:[['assets','Critical assets'],['maturity','NIST CSF maturity'],['models','Models & AI']]});
G.mount({id:'bcp',label:'Business continuity',ico:'↻',group:RG,title:'Business continuity & disaster recovery',sub:'Business impact analysis with recovery objectives, continuity plans and the test history that proves they work.',tabs:[['bia','Business impact analysis'],['plans','Plans & tests']]});
if(G.modOn('fincrime'))G.mount({id:'fincrime',label:'Financial crime & conduct',ico:'⚖',group:RO,title:'Financial crime & conduct',sub:'AML and fraud case management with reporting deadlines, KYC and screening health, and customer complaints against their turnaround time.',tabs:[['cases','Cases & alerts'],['kyc','KYC & screening'],['complaints','Complaints']]});
G.mount({id:'audit',label:'Internal audit',ico:'✎',group:RO,title:'Internal audit',sub:'Risk-based audit plan, progress and ratings, coverage of risk areas, and the findings that flow into the issues register.',tabs:[['plan','Audit plan'],['coverage','Risk coverage']]});
const cy=()=>S().cyber||{assets:[],maturity:[],models:[]},bc=()=>S().bcp||{bia:[],plans:[]},fc=()=>S().fc||{cases:[],kyc:[],complaints:[],screening:{}},au=()=>S().audit||{plan:[]};
// ---------------------------------------------------------------- cyber
const assetGaps=a=>{const g=[];if(a.crit&&a.internet)g.push(['red',`<b>${a.crit} critical</b> vulnerabilit${a.crit>1?'ies':'y'} on an internet-facing asset.`]);else if(a.crit)g.push(['amber',`${a.crit} critical vulnerabilit${a.crit>1?'ies':'y'} open.`]);if(a.high>5)g.push(['amber',`${a.high} high-severity vulnerabilities open.`]);if(dTo(addDays(a.scan,30))<0)g.push(['amber',`Last scan ${fmt(a.scan)}, more than 30 days ago.`]);if(!a.mfa&&a.tier==='Tier 1')g.push(['red','No multi-factor authentication on a Tier 1 asset.']);if(!a.enc)g.push(['amber','Sensitive data not encrypted at rest.']);return g};
const modDue=m=>m.validated?addDays(m.validated,m.tier==='High'?365:730):'';
const modGaps=m=>{const g=[];if(!m.validated)g.push(['red','Not validated before use.']);else if(dTo(modDue(m))<0)g.push(['red',`Validation overdue since ${fmt(modDue(m))}.`]);if(m.drift==='Drifted')g.push(['red','Performance has drifted from the validated baseline.']);else if(m.drift==='Watch')g.push(['amber','Performance under watch.']);if(m.findings)g.push(['amber',`${m.findings} validation finding(s) open.`]);return g};
function renderCyber(){const c=cy(),as=c.assets;
 head('cyber','<button class="btn" data-op="cy-export"><span class="btnico">↓</span>Export assets</button><button class="btn primary" data-op="as-new"><span class="btnico">＋</span>Add asset</button>');
 const worst=as.filter(a=>a.crit&&a.internet),crit=as.reduce((s,a)=>s+a.crit,0),f=flt('cyber','as');
 const rows=as.filter(a=>match(f,[a.id,a.name,a.owner,a.type].join(' '))&&(!f.tier||f.tier==='All'||a.tier===f.tier)).sort((a,b)=>assetGaps(b).filter(x=>x[0]==='red').length-assetGaps(a).filter(x=>x[0]==='red').length).map(a=>{const g=assetGaps(a),r=g.filter(x=>x[0]==='red').length;return `<tr data-op="open" data-t="asset" data-id="${a.id}"><td class="riskid">${a.id}</td><td><div class="riskname">${E(a.name)}</div><div class="riskarea">${E(a.type)}${a.internet?' · internet-facing':''}</div></td><td>${pill(a.tier,a.tier==='Tier 1'?'red':'amber')}</td><td>${own(a.owner)}</td><td><b style="color:${a.crit?'#bf554d':'#178b78'}">${a.crit}</b> / ${a.high}</td><td>${fmt(a.scan)}</td><td>${a.mfa?pill('MFA','green'):pill('no MFA','red')}</td><td>${g.length?pill(g.length+' issue'+(g.length>1?'s':''),r?'red':'amber'):pill('OK','green')}</td></tr>`});
 panel('cyber','assets').innerHTML=`<div class="op-kpis">${kpi('Critical assets',as.length,`${as.filter(a=>a.tier==='Tier 1').length} Tier 1`)}${kpi('Internet-facing with critical vulns',worst.length,'fix first',worst.length?'warn':'ok')}${kpi('Critical vulnerabilities',crit,'open across assets',crit?'warn':'ok')}${kpi('Tier 1 without MFA',as.filter(a=>a.tier==='Tier 1'&&!a.mfa).length,'enforce multi-factor',as.some(a=>a.tier==='Tier 1'&&!a.mfa)?'warn':'ok')}</div>${toolbar('cyber','as','Search assets, owners…',[['tier',['All','Tier 1','Tier 2','Tier 3'],'All tiers']])}${card('Critical technology assets','Sorted by urgency. Counts are critical / high vulnerabilities.',table(['ID','Asset','Tier','Owner','Vulns (C / H)','Last scan','MFA','Gaps'],rows,'No assets.'))}`;
 const sev=(n,t)=>n>=t?'':n>=t-0.7?'amber':'red',obl=(S().obl||[]).filter(o=>o.fw==='nist-csf2');const pre={Govern:'GV',Identify:'ID',Protect:'PR',Detect:'DE',Respond:'RS',Recover:'RC'};
 const mr=c.maturity.map(m=>{const ob=obl.filter(o=>o.ref.startsWith(pre[m.fn]));const cp=ob.length?Math.round(ob.filter(o=>o.status==='Compliant').length/ob.length*100):null;return `<tr data-op="open" data-t="csf" data-id="${m.fn}"><td><div class="riskname">${m.fn}</div></td><td style="min-width:200px">${bar(m.now/4*100,sev(m.now,m.target))}</td><td><b>${m.now.toFixed(1)}</b> / ${m.target.toFixed(1)}</td><td>${pill((m.target-m.now).toFixed(1)+' gap',m.target-m.now>1?'red':m.target-m.now>0.5?'amber':'green')}</td><td>${cp===null?'–':cp+'% of '+ob.length}</td></tr>`}).join('');
 panel('cyber','maturity').innerHTML=`<div class="op-kpis">${kpi('Average maturity',(c.maturity.reduce((s,m)=>s+m.now,0)/Math.max(1,c.maturity.length)).toFixed(1),'scale 0–4')}${kpi('Biggest gap',c.maturity.slice().sort((a,b)=>(b.target-b.now)-(a.target-a.now))[0]?.fn||'–','function furthest from target','warn')}${kpi('Assessed',fmt(c.assessed),'last maturity assessment')}${kpi('NIST CSF obligations',obl.length?Math.round(obl.filter(o=>o.status==='Compliant').length/obl.length*100)+'%':'–','compliant in the register')}</div>${card('NIST CSF 2.0 maturity by function','Current vs target (0–4). Obligations column links to the compliance register when NIST CSF 2.0 is adopted.',`<div class="tablewrap"><table><thead><tr><th>Function</th><th>Maturity</th><th>Current / target</th><th>Gap</th><th>Obligations compliant</th></tr></thead><tbody>${mr}</tbody></table></div><div style="padding:12px 18px"><button class="op-mini p" data-op="csf-assess">Update maturity scores</button></div>`)}`;
 const fm=flt('cyber','md'),ms=c.models.filter(m=>match(fm,[m.id,m.name,m.owner,m.type,m.use].join(' '))).map(m=>{const g=modGaps(m),r=g.filter(x=>x[0]==='red').length;return `<tr data-op="open" data-t="model" data-id="${m.id}"><td class="riskid">${m.id}</td><td><div class="riskname">${E(m.name)}</div><div class="riskarea">${E(m.use)}</div></td><td>${E(m.type)}</td><td>${pill(m.tier,m.tier==='High'?'red':'amber')}</td><td>${own(m.owner)}</td><td>${m.validated?fmt(m.validated):'—'}</td><td>${pill(m.drift,m.drift==='Stable'?'green':m.drift==='Watch'?'amber':'red')}</td><td>${g.length?pill(g.length+' issue'+(g.length>1?'s':''),r?'red':'amber'):pill('OK','green')}</td></tr>`});
 panel('cyber','models').innerHTML=`<div class="op-kpis">${kpi('Models and AI systems',c.models.length,`${c.models.filter(m=>m.tier==='High').length} high-tier`)}${kpi('Validation overdue / missing',c.models.filter(m=>!m.validated||dTo(modDue(m))<0).length,'validate before further use',c.models.some(m=>!m.validated||dTo(modDue(m))<0)?'warn':'ok')}${kpi('Drifted',c.models.filter(m=>m.drift==='Drifted').length,'retrain or recalibrate')}${kpi('Generative AI in use',c.models.filter(m=>m.type==='Generative AI').length,'needs an AI risk assessment')}</div>${toolbar('cyber','md','Search models…',[])}${card('Model and AI inventory','Validation yearly for high-tier models and every two years otherwise. Aligns with NIST AI RMF, ISO 42001 and supervisory model-risk expectations.',table(['ID','Model','Type','Tier','Owner','Last validated','Performance','Gaps'],ms,'No models.'))}`;
 G.setBadge('cyber',worst.length)}
G.renders.push(renderCyber);
G.drawers.asset=id=>{const a=cy().assets.find(x=>x.id===id);if(!a)return;const iss=S().issues.filter(i=>i.link===a.id&&i.status!=='Closed');
 detail({kicker:'Asset · '+a.id,title:a.name,pending:[...assetGaps(a),...iss.map(i=>['amber',`Open issue ${i.id}: ${E(i.title)}.`])],ok:'Scanned, patched and protected.',todo:['Patch or mitigate critical vulnerabilities within the patch SLA.','Enforce MFA for all privileged and remote access.','Scan at least monthly and after major changes.','Confirm encryption, backups and logging for sensitive data.'],facts:[['Type',E(a.type)],['Tier',pill(a.tier,a.tier==='Tier 1'?'red':'amber')],['Owner',E(a.owner)],['Exposure',a.internet?'Internet-facing':'Internal'],['Vulnerabilities',`${a.crit} critical · ${a.high} high`],['Last scan',fmt(a.scan)],['MFA',a.mfa?'Yes':'No'],['Encrypted at rest',a.enc?'Yes':'No']],buttons:`<button class="op-mini p" data-op="as-scan" data-id="${a.id}">Record scan result</button>${assetGaps(a).some(x=>x[0]==='red')&&!iss.length?`<button class="op-mini r" data-op="as-issue" data-id="${a.id}">Raise issue</button>`:''}`,links:[a.ibs,...iss.map(i=>i.id),...S().controls.filter(c=>/vulnerab|patch|access/i.test(c.name)).slice(0,2).map(c=>c.id)].filter(Boolean)})};
G.drawers.csf=fn=>{const m=cy().maturity.find(x=>x.fn===fn);if(!m)return;const pre={Govern:'GV',Identify:'ID',Protect:'PR',Detect:'DE',Respond:'RS',Recover:'RC'}[fn],obl=(S().obl||[]).filter(o=>o.fw==='nist-csf2'&&o.ref.startsWith(pre));
 detail({kicker:'NIST CSF 2.0',title:fn+' function',pending:m.target-m.now>0.5?[[m.target-m.now>1?'red':'amber',`Maturity <b>${m.now.toFixed(1)}</b> vs target <b>${m.target.toFixed(1)}</b>.`]]:[],ok:'At or near target.',todo:['Review the weakest categories in this function and agree actions.','Link improvement actions to owners and dates.','Re-assess maturity at least annually.'],facts:[['Current',m.now.toFixed(1)],['Target',m.target.toFixed(1)],['Obligations mapped',String(obl.length)]],buttons:'<button class="op-mini p" data-op="csf-assess">Update maturity scores</button>',links:obl.map(o=>o.id)})};
G.drawers.model=id=>{const m=cy().models.find(x=>x.id===id);if(!m)return;
 detail({kicker:'Model · '+m.id,title:m.name,pending:modGaps(m),ok:'Validated, stable and monitored.',todo:['Validate independently before use and at the required frequency.','Monitor performance, drift and bias; define retrain triggers.','Document purpose, data, limitations and owners.',m.type==='Generative AI'?'Complete an AI risk assessment, restrict sensitive data in prompts and review vendor terms.':'Keep a challenger or benchmark and an override process.'],facts:[['Type',E(m.type)],['Tier',pill(m.tier,m.tier==='High'?'red':'amber')],['Owner',E(m.owner)],['Use',E(m.use)],['Last validated',m.validated?fmt(m.validated):'Never'],['Next validation',m.validated?fmt(modDue(m)):'Overdue'],['Performance',E(m.drift)],['Vendor',E(m.vendor||'In-house')]],buttons:`<button class="op-mini p" data-op="md-validate" data-id="${m.id}">Record validation</button><button class="op-mini r" data-op="md-issue" data-id="${m.id}">Raise issue</button>`,links:S().policies.filter(p=>/model/i.test(p.title)).map(p=>p.id)})};
// ---------------------------------------------------------------- business continuity
const planDue=p=>p.last?addDays(p.last,FREQ[p.freq]||365):'';
const biaGap=b=>b.rto>b.mtpd;
function renderBcp(){const b=bc(),od=b.plans.filter(p=>!p.last||dTo(planDue(p))<0);
 head('bcp','<button class="btn" data-op="bc-export"><span class="btnico">↓</span>Export</button><button class="btn" data-op="plan-new"><span class="btnico">＋</span>Add plan</button><button class="btn primary" data-op="bia-new"><span class="btnico">＋</span>Add process</button>');
 const rows=b.bia.map(x=>`<tr data-op="open" data-t="bia" data-id="${x.id}"><td class="riskid">${x.id}</td><td><div class="riskname">${E(x.process)}</div><div class="riskarea">${E(x.deps)}</div></td><td>${pill(x.crit,x.crit==='Critical'?'red':'amber')}</td><td>${own(x.owner)}</td><td>${x.mtpd}h</td><td>${biaGap(x)?pill(x.rto+'h',  'red'):x.rto+'h'}</td><td>${x.rpo}h</td><td>${fmt(x.review)}${dTo(addDays(x.review,365))<0?' '+pill('review due','amber'):''}</td></tr>`);
 panel('bcp','bia').innerHTML=`<div class="op-kpis">${kpi('Processes analysed',b.bia.length,`${b.bia.filter(x=>x.crit==='Critical').length} critical`)}${kpi('RTO exceeds MTPD',b.bia.filter(biaGap).length,'recovery target is too slow',b.bia.some(biaGap)?'warn':'ok')}${kpi('Reviews overdue',b.bia.filter(x=>dTo(addDays(x.review,365))<0).length,'older than 12 months',b.bia.some(x=>dTo(addDays(x.review,365))<0)?'warn':'ok')}${kpi('Plans untested / overdue',od.length,'schedule a test',od.length?'warn':'ok')}</div>${card('Business impact analysis','MTPD = maximum tolerable period of disruption, RTO = recovery time objective, RPO = recovery point objective. RTO must be below MTPD.',table(['ID','Process','Criticality','Owner','MTPD','RTO','RPO','Last review'],rows,'No processes.'))}`;
 const pr=b.plans.map(p=>{const o=!p.last||dTo(planDue(p))<0;return `<tr data-op="open" data-t="plan" data-id="${p.id}"><td class="riskid">${p.id}</td><td><div class="riskname">${E(p.name)}</div><div class="riskarea">${E(p.scope)}</div></td><td>${own(p.owner)}</td><td>v${E(p.ver)} · ${pill(p.status,p.status==='Approved'?'green':'amber')}</td><td>${p.last?fmt(p.last):'—'}</td><td>${p.last?fmt(planDue(p)):'—'}${o?' '+pill('overdue','red'):''}</td><td>${pill(p.result,p.result==='Passed'?'green':p.result==='Not tested'?'red':'amber')}</td></tr>`});
 panel('bcp','plans').innerHTML=`<div class="op-kpis">${kpi('Plans',b.plans.length,`${b.plans.filter(p=>p.status==='Approved').length} approved`)}${kpi('Never tested',b.plans.filter(p=>!p.last).length,'untested plans are assumptions',b.plans.some(p=>!p.last)?'warn':'ok')}${kpi('Test overdue',b.plans.filter(p=>p.last&&dTo(planDue(p))<0).length,'past frequency',b.plans.some(p=>p.last&&dTo(planDue(p))<0)?'warn':'ok')}${kpi('Passed with findings',b.plans.filter(p=>p.result==='Passed with findings').length,'track fixes')}</div>${card('Continuity and recovery plans','Test at least annually and after major change; record results and findings.',table(['ID','Plan','Owner','Version','Last test','Next due','Result'],pr,'No plans.'))}`;
 G.setBadge('bcp',od.length)}
G.renders.push(renderBcp);
G.drawers.bia=id=>{const x=bc().bia.find(r=>r.id===id);if(!x)return;const P2=[];if(biaGap(x))P2.push(['red',`RTO <b>${x.rto}h</b> is longer than the maximum tolerable disruption <b>${x.mtpd}h</b>.`]);if(dTo(addDays(x.review,365))<0)P2.push(['amber',`Not reviewed for over 12 months (last ${fmt(x.review)}).`]);const pl=bc().plans.filter(p=>p.scope.toLowerCase().includes(x.process.split(' ')[0].toLowerCase()));if(x.crit==='Critical'&&!pl.length)P2.push(['amber','No continuity plan clearly covers this critical process.']);
 detail({kicker:'Business process · '+x.id,title:x.process,pending:P2,ok:'Objectives achievable and reviewed.',todo:['Confirm the impact of disruption over time (financial, customer, regulatory).','Set RTO below MTPD and check the recovery solution can meet it.','Map dependencies (systems, people, providers, locations).','Link to a plan and test it.'],facts:[['Criticality',pill(x.crit,x.crit==='Critical'?'red':'amber')],['Owner',E(x.owner)],['MTPD',x.mtpd+' hours'],['RTO',x.rto+' hours'],['RPO',x.rpo+' hours'],['Last review',fmt(x.review)],['Dependencies',E(x.deps)]],buttons:`<button class="op-mini g" data-op="bia-review" data-id="${x.id}">Mark reviewed</button>${biaGap(x)?`<button class="op-mini r" data-op="bia-issue" data-id="${x.id}">Raise issue</button>`:''}`,links:pl.map(p=>p.id)})};
G.drawers.plan=id=>{const p=bc().plans.find(r=>r.id===id);if(!p)return;const P2=[];if(!p.last)P2.push(['red','Never tested.']);else{const ds=dueState(planDue(p),30);if(ds)P2.push([ds[0],`Next test ${ds[1]}.`])}if(p.result==='Passed with findings')P2.push(['amber','Test raised findings to close.']);if(p.status!=='Approved')P2.push(['amber',`Plan is ${E(p.status.toLowerCase())}, not approved.`]);
 detail({kicker:'Plan · '+p.id,title:p.name,pending:P2,ok:'Approved, tested and current.',todo:['Run a realistic exercise (tabletop and technical) with the right people.','Record time to recover versus objectives and any findings.','Update the plan, contact lists and dependencies.','Get approval for the new version.'],facts:[['Scope',E(p.scope)],['Owner',E(p.owner)],['Version',E(p.ver)],['Status',E(p.status)],['Frequency',E(p.freq)],['Last test',p.last?fmt(p.last):'Never'],['Next due',p.last?fmt(planDue(p)):'Now'],['Result',E(p.result)]],buttons:`<button class="op-mini p" data-op="plan-test" data-id="${p.id}">Record test</button>`,links:S().controls.filter(c=>/BCP|continuity|DR|recovery|failover/i.test(c.name)).slice(0,2).map(c=>c.id)})};
// ---------------------------------------------------------------- financial crime & conduct
const strDue=c=>c.suspicion&&!c.strFiled?addDays(c.suspicion,7):'';
const caseOpen=c=>c.status!=='Closed'&&c.status!=='STR filed';
const cmpDue=c=>addDays(c.received,30),cmpOpen=c=>c.status!=='Resolved'&&c.status!=='Closed';
function renderFc(){if(!G.modOn('fincrime'))return;const f=fc();
 head('fincrime','<button class="btn" data-op="fc-export"><span class="btnico">↓</span>Export cases</button><button class="btn" data-op="cmp-new"><span class="btnico">＋</span>Log complaint</button><button class="btn primary" data-op="case-new"><span class="btnico">＋</span>New case</button>');
 const open=f.cases.filter(caseOpen),str=open.filter(c=>strDue(c)&&dTo(strDue(c))<=3),aged=open.filter(c=>dTo(addDays(c.opened,30))<0);
 const cr=f.cases.map(c=>`<tr data-op="open" data-t="case" data-id="${c.id}"><td class="riskid">${c.id}</td><td><div class="riskname">${E(c.type)}</div><div class="riskarea">${E(c.who)} · opened ${fmt(c.opened)}</div></td><td>${pill(c.risk,c.risk==='High'?'red':'amber')}</td><td>${own(c.analyst)}</td><td>${c.amount?G.inr(c.amount):'—'}</td><td>${strDue(c)?(dTo(strDue(c))<0?pill('STR overdue','red'):pill('STR due '+fmt(strDue(c)),dTo(strDue(c))<=3?'red':'amber')):c.strFiled?pill('STR filed','green'):'—'}</td><td>${pill(c.status,c.status==='Closed'||c.status==='STR filed'?'green':c.status==='Escalated'?'red':'amber')}</td></tr>`);
 panel('fincrime','cases').innerHTML=`<div class="op-kpis">${kpi('Open cases',open.length,`${f.cases.length} total`)}${kpi('STR deadline within 3 days',str.length,'file with FIU-IND promptly',str.length?'warn':'ok')}${kpi('Cases older than 30 days',aged.length,'escalate or close',aged.length?'warn':'ok')}${kpi('Value under review',G.inr(open.reduce((s,c)=>s+c.amount,0)),'open cases')}</div>${card('Financial crime cases and alerts','A suspicious transaction report is due within 7 working days of concluding suspicion (shown here as 7 calendar days for simplicity). Verify timelines.',table(['ID','Case','Risk','Analyst','Value','STR','Status'],cr,'No cases.'))}`;
 const kr=f.kyc.map(k=>{const pc=k.cust?(k.overdue/k.cust*100):0;return `<tr><td><div class="riskname">${E(k.band)} risk</div><div class="riskarea">Refresh every ${E(k.interval)}</div></td><td>${k.cust.toLocaleString('en-IN')}</td><td>${k.due.toLocaleString('en-IN')}</td><td>${k.overdue.toLocaleString('en-IN')}</td><td style="min-width:120px">${bar(Math.min(100,pc*8),pc>3?'red':pc>1.5?'amber':'')}</td><td>${pc.toFixed(1)}%</td></tr>`}).join('');
 const tot=f.kyc.reduce((s,k)=>({c:s.c+k.cust,o:s.o+k.overdue}),{c:0,o:0});
 panel('fincrime','kyc').innerHTML=`<div class="op-kpis">${kpi('Customers',tot.c.toLocaleString('en-IN'),'across risk bands')}${kpi('KYC reviews overdue',tot.o.toLocaleString('en-IN'),(tot.c?(tot.o/tot.c*100).toFixed(1):0)+'% of customers',tot.o?'warn':'ok')}${kpi('Screening alerts open',f.screening.open||0,`last full screen ${f.screening.last?fmt(f.screening.last):'—'}`,(f.screening.open||0)?'warn':'ok')}${kpi('PEP relationships',f.screening.pep||0,'enhanced due diligence')}</div>${card('KYC periodic review health','High-risk customers need the most frequent refresh. Overdue reviews feed KRI-07 and audit findings.',`<div class="tablewrap"><table><thead><tr><th>Risk band</th><th>Customers</th><th>Reviews due</th><th>Overdue</th><th>Overdue trend</th><th>% overdue</th></tr></thead><tbody>${kr}</tbody></table></div><div style="padding:12px 18px"><button class="op-mini p" data-op="kyc-update">Update KYC figures</button></div>`)}`;
 const cm=f.complaints.map(c=>{const od=cmpOpen(c)&&dTo(cmpDue(c))<0;return `<tr data-op="open" data-t="complaint" data-id="${c.id}"><td class="riskid">${c.id}</td><td><div class="riskname">${E(c.category)}</div><div class="riskarea">${E(c.channel)} · received ${fmt(c.received)}</div></td><td>${own(c.owner)}</td><td>${cmpOpen(c)?fmt(cmpDue(c)):'—'}</td><td>${cmpOpen(c)?(od?pill(-dTo(cmpDue(c))+' days late','red'):pill(dTo(cmpDue(c))+' days left',dTo(cmpDue(c))<=5?'amber':'green')):''}</td><td>${c.ombudsman?pill('Ombudsman','red'):''}</td><td>${pill(c.status,cmpOpen(c)?'amber':'green')}</td></tr>`});
 const lateC=f.complaints.filter(c=>cmpOpen(c)&&dTo(cmpDue(c))<0);
 panel('fincrime','complaints').innerHTML=`<div class="op-kpis">${kpi('Open complaints',f.complaints.filter(cmpOpen).length,`${f.complaints.length} logged`)}${kpi('Past 30-day turnaround',lateC.length,'resolve and explain',lateC.length?'warn':'ok')}${kpi('Escalated to Ombudsman',f.complaints.filter(c=>c.ombudsman).length,'review root cause',f.complaints.some(c=>c.ombudsman)?'warn':'ok')}${kpi('Mis-selling related',f.complaints.filter(c=>/mis-selling/i.test(c.category)).length,'conduct risk indicator')}</div>${card('Customer complaints','Turnaround target 30 days (RBI Integrated Ombudsman Scheme, verify). Repeat categories feed conduct risk.',table(['ID','Complaint','Owner','Due','Clock','Escalation','Status'],cm,'No complaints.'))}`;
 G.setBadge('fincrime',str.length+lateC.length)}
G.renders.push(renderFc);
G.drawers.case=id=>{const c=fc().cases.find(x=>x.id===id);if(!c)return;const P2=[];if(strDue(c)){const ds=dueState(strDue(c),3);P2.push(ds?[ds[0],`Suspicious transaction report ${ds[1]}.`]:['amber',`STR due ${fmt(strDue(c))}.`])}if(caseOpen(c)&&dTo(addDays(c.opened,30))<0)P2.push(['amber','Open for more than 30 days.']);if(caseOpen(c)&&c.risk==='High'&&c.status==='Open')P2.push(['amber','High-risk case not yet under investigation.']);
 detail({kicker:'Case · '+c.id,title:c.type,pending:P2,ok:'Closed or reported on time.',todo:['Gather account, KYC and transaction evidence; document the rationale.','Decide if suspicion is concluded; if so file the STR with FIU-IND promptly, without tipping off.','For fraud, freeze or restrict accounts and notify law enforcement as needed.','Record outcome and update scenarios and risk ratings.'],facts:[['Subject',E(c.who)],['Risk',pill(c.risk,c.risk==='High'?'red':'amber')],['Opened',fmt(c.opened)],['Suspicion concluded',c.suspicion?fmt(c.suspicion):'—'],['Analyst',E(c.analyst)],['Value',c.amount?G.inr(c.amount):'—'],['Status',E(c.status)],['STR filed',c.strFiled?fmt(c.strFiled):'No']],buttons:`<button class="op-mini p" data-op="case-update" data-id="${c.id}">Update case</button>${!c.strFiled?`<button class="op-mini g" data-op="case-str" data-id="${c.id}">Record STR filed</button>`:''}`,links:['R-109','R-110',...S().controls.filter(x=>/transaction|KYC/i.test(x.name)).map(x=>x.id)]})};
G.drawers.complaint=id=>{const c=fc().complaints.find(x=>x.id===id);if(!c)return;const P2=[];if(cmpOpen(c)){const ds=dueState(cmpDue(c),5);P2.push(ds?[ds[0],`Response ${ds[1]}.`]:['amber',`Due ${fmt(cmpDue(c))}.`])}if(c.ombudsman)P2.push(['red','Escalated to the Ombudsman: respond with full documentation.']);if(/mis-selling/i.test(c.category))P2.push(['amber','Mis-selling indicator: review the sale, suitability record and agent.']);
 detail({kicker:'Complaint · '+c.id,title:c.category,pending:P2,ok:'Resolved within turnaround.',todo:['Acknowledge, investigate and respond in writing within the turnaround time.','Check for redress and whether others are affected.','Record root cause; raise an issue if systemic.'],facts:[['Channel',E(c.channel)],['Received',fmt(c.received)],['Due',fmt(cmpDue(c))],['Owner',E(c.owner)],['Amount',c.amount?G.inr(c.amount):'—'],['Status',E(c.status)]],buttons:`<button class="op-mini g" data-op="cmp-resolve" data-id="${c.id}">Mark resolved</button><button class="op-mini r" data-op="cmp-issue" data-id="${c.id}">Raise issue</button>`,links:['R-111']})};
// ---------------------------------------------------------------- internal audit
const auEnd=x=>addDays(x.end,14);
const auLate=x=>x.status!=='Complete'&&((x.status==='Planned'&&dTo(x.start)<0)||dTo(auEnd(x))<0);
function renderAudit(){const p=au().plan,iss=S().issues;
 head('audit','<button class="btn" data-op="au-export"><span class="btnico">↓</span>Export plan</button><button class="btn primary" data-op="au-new"><span class="btnico">＋</span>Add audit</button>');
 const rows=p.map(x=>`<tr data-op="open" data-t="audit" data-id="${x.id}"><td class="riskid">${x.id}</td><td><div class="riskname">${E(x.title)}</div><div class="riskarea">${E(x.area)} · ${E(x.qtr)}</div></td><td>${pill(x.risk,x.risk==='High'?'red':'amber')}</td><td>${own(x.lead)}</td><td>${fmt(x.start)} → ${fmt(x.end)}</td><td>${x.findings}</td><td>${x.rating?pill(x.rating,x.rating==='Satisfactory'?'green':x.rating==='Unsatisfactory'?'red':'amber'):'—'}</td><td>${pill(x.status,x.status==='Complete'?'green':auLate(x)?'red':'amber')}</td></tr>`);
 const done=p.filter(x=>x.status==='Complete').length;
 panel('audit','plan').innerHTML=`<div class="op-kpis">${kpi('Audits in plan',p.length,`${done} complete`)}${kpi('Plan delivery',p.length?Math.round(done/p.length*100)+'%':'–','completed to date')}${kpi('Behind schedule',p.filter(auLate).length,'late start or report overdue',p.some(auLate)?'warn':'ok')}${kpi('Open audit findings',iss.filter(i=>i.source==='Audit finding'&&i.status!=='Closed').length,'tracked as issues',iss.some(i=>i.source==='Audit finding'&&i.status!=='Closed')?'warn':'ok')}</div>${card('Risk-based internal audit plan','Report due 14 days after fieldwork ends. Findings are tracked in the issues register and closed with independent verification.',table(['ID','Audit','Risk','Lead','Dates','Findings','Rating','Status'],rows,'No audits planned.'))}`;
 const areas=[...new Set(risks.map(r=>r.area))],cov=areas.map(a=>{const ar=risks.filter(r=>r.area===a),out=ar.filter(r=>r.score>(S().appetite||12)).length,as=p.filter(x=>x.area===a),last=as.filter(x=>x.status==='Complete').sort((x,y)=>x.end<y.end?1:-1)[0];const gap=out&&!as.length;return `<tr><td><div class="riskname">${E(a)}</div></td><td>${ar.length}</td><td>${out?pill(out,'red'):'–'}</td><td>${as.length||pill('none','red')}</td><td>${last?fmt(last.end):'—'}</td><td>${gap?pill('Coverage gap','red'):as.length?pill('Covered','green'):pill('Not planned','amber')}</td></tr>`}).join('');
 panel('audit','coverage').innerHTML=`<p class="op-note" style="margin:0 0 10px">Audit coverage should follow risk. Areas with risks outside appetite and no audit in the plan are coverage gaps.</p>${card('Audit coverage by risk area','Risks, risks outside appetite and audits per area',`<div class="tablewrap"><table><thead><tr><th>Risk area</th><th>Risks</th><th>Outside appetite</th><th>Audits</th><th>Last completed</th><th>Coverage</th></tr></thead><tbody>${cov}</tbody></table></div>`)}`;
 G.setBadge('audit',p.filter(auLate).length)}
G.renders.push(renderAudit);
G.drawers.audit=id=>{const x=au().plan.find(r=>r.id===id);if(!x)return;const fi=x.fids.map(f=>S().issues.find(i=>i.link===f)).filter(Boolean),P2=[];
 if(x.status==='Planned'&&dTo(x.start)<0)P2.push(['red',`Fieldwork should have started ${fmt(x.start)}.`]);else if(x.status!=='Complete'){const ds=dueState(auEnd(x),14);if(ds)P2.push([ds[0],`Report ${ds[1]}.`])}
 fi.filter(i=>i.status!=='Closed').forEach(i=>P2.push([i.due<TODAY?'red':'amber',`Finding ${E(i.link)} → ${i.id}: ${E(i.title)} (${E(i.owner)}, due ${fmt(i.due)}).`]));
 detail({kicker:'Audit · '+x.id,title:x.title,pending:P2,ok:'Delivered and findings closed.',todo:['Agree scope and terms of reference with management.','Test controls and evidence; discuss draft findings.','Issue the report with rating and agreed actions before the report due date.','Track management actions to closure and verify independently.'],facts:[['Area',E(x.area)],['Quarter',E(x.qtr)],['Risk',pill(x.risk,x.risk==='High'?'red':'amber')],['Lead auditor',E(x.lead)],['Fieldwork',`${fmt(x.start)} → ${fmt(x.end)}`],['Report due',fmt(auEnd(x))],['Findings',String(x.findings)],['Rating',E(x.rating||'Not yet rated')]],buttons:`<button class="op-mini p" data-op="au-update" data-id="${x.id}">Update audit</button>`,links:[...fi.map(i=>i.id),...risks.filter(r=>r.area===x.area).slice(0,4).map(r=>r.id)]})};
G.linkers.push(id=>{let x;if(x=cy().assets.find(q=>q.id===id))return{type:'asset',label:`${x.id} · ${x.name}`};if(x=cy().models.find(q=>q.id===id))return{type:'model',label:`${x.id} · ${x.name}`};if(x=bc().bia.find(q=>q.id===id))return{type:'bia',label:`${x.id} · ${x.process}`};if(x=bc().plans.find(q=>q.id===id))return{type:'plan',label:`${x.id} · ${x.name}`};if(x=fc().cases.find(q=>q.id===id))return{type:'case',label:`${x.id} · ${x.type}`};if(x=fc().complaints.find(q=>q.id===id))return{type:'complaint',label:`${x.id} · ${x.category}`};if(x=au().plan.find(q=>q.id===id))return{type:'audit',label:`${x.id} · ${x.title}`};return null});
// ---------------------------------------------------------------- actions
Object.assign(actions,{
 'cy-export':()=>csv('forge-assets.csv',[['ID','Asset','Type','Tier','Owner','Internet-facing','Critical vulns','High vulns','Last scan','MFA','Encrypted'],...cy().assets.map(a=>[a.id,a.name,a.type,a.tier,a.owner,a.internet,a.crit,a.high,a.scan,a.mfa,a.enc])],'Assets exported as CSV.'),
 'as-new':()=>openForm('Add critical asset',[{name:'name',label:'Asset',full:true},{name:'type',label:'Type',type:'select',options:['Application','Infrastructure','Data store','Network','OT system']},{name:'tier',label:'Tier',type:'select',options:['Tier 1','Tier 2','Tier 3']},{name:'owner',label:'Owner',type:'select',options:personOpts(),value:me().name},{name:'internet',label:'Internet-facing?',type:'select',options:['No','Yes']}],'Add',v=>{if(!v.name)return 'Name the asset.';cy().assets.push({id:nid(cy().assets,'AS-'),name:v.name,type:v.type,tier:v.tier,owner:v.owner,internet:v.internet==='Yes',crit:0,high:0,scan:TODAY,mfa:true,enc:true,ibs:''});commit()}),
 'as-scan':b=>{const a=cy().assets.find(x=>x.id===b.dataset.id);openForm('Scan result · '+a.id,[{name:'crit',label:'Critical vulnerabilities',type:'number',value:String(a.crit)},{name:'high',label:'High vulnerabilities',type:'number',value:String(a.high)},{name:'mfa',label:'MFA enforced?',type:'select',options:['Yes','No'],value:a.mfa?'Yes':'No'},{name:'enc',label:'Encrypted at rest?',type:'select',options:['Yes','No'],value:a.enc?'Yes':'No'}],'Save',v=>{a.crit=+v.crit||0;a.high=+v.high||0;a.mfa=v.mfa==='Yes';a.enc=v.enc==='Yes';a.scan=TODAY;logIt(a.id,`Scan: ${a.crit} critical, ${a.high} high.`);commit()})},
 'as-issue':b=>{const a=cy().assets.find(x=>x.id===b.dataset.id);raise('Asset review',a.id,`Remediate exposure: ${a.name}`,'High',a.owner,assetGaps(a).map(g=>g[1].replace(/<[^>]+>/g,'')).join(' '),'Resourcing / capacity');commit()},
 'csf-assess':()=>openForm('Update NIST CSF maturity (0–4)',cy().maturity.flatMap(m=>[{name:'n'+m.fn,label:m.fn+' · current',type:'number',step:'0.1',value:String(m.now)},{name:'t'+m.fn,label:m.fn+' · target',type:'number',step:'0.1',value:String(m.target)}]),'Save scores',v=>{cy().maturity.forEach(m=>{m.now=Math.max(0,Math.min(4,+v['n'+m.fn]||0));m.target=Math.max(0,Math.min(4,+v['t'+m.fn]||0))});cy().assessed=TODAY;logIt('CSF','Maturity updated.');commit()}),
 'md-validate':b=>{const m=cy().models.find(x=>x.id===b.dataset.id);openForm('Record validation · '+m.id,[{name:'date',label:'Validation date',type:'date',value:TODAY},{name:'drift',label:'Performance',type:'select',options:['Stable','Watch','Drifted'],value:m.drift},{name:'findings',label:'Open findings',type:'number',value:String(m.findings)}],'Save',v=>{m.validated=v.date;m.drift=v.drift;m.findings=+v.findings||0;logIt(m.id,'Validation recorded.');commit()})},
 'md-issue':b=>{const m=cy().models.find(x=>x.id===b.dataset.id);raise('Model review',m.id,`Model risk: ${m.name}`,m.tier==='High'?'High':'Medium',m.owner,modGaps(m).map(g=>g[1]).join(' ')||'Model risk review.','Control design');commit()},
 'bc-export':()=>csv('forge-continuity.csv',[['ID','Process','Criticality','Owner','MTPD h','RTO h','RPO h','Last review'],...bc().bia.map(x=>[x.id,x.process,x.crit,x.owner,x.mtpd,x.rto,x.rpo,x.review])],'Continuity data exported.'),
 'bia-new':()=>openForm('Add business process',[{name:'process',label:'Process',full:true},{name:'crit',label:'Criticality',type:'select',options:['Critical','Important']},{name:'owner',label:'Owner',type:'select',options:personOpts(),value:me().name},{name:'mtpd',label:'MTPD (hours)',type:'number',value:'24'},{name:'rto',label:'RTO (hours)',type:'number',value:'8'},{name:'rpo',label:'RPO (hours)',type:'number',value:'1'}],'Add',v=>{if(!v.process)return 'Name the process.';bc().bia.push({id:nid(bc().bia,'BIA-'),process:v.process,owner:v.owner,crit:v.crit,mtpd:+v.mtpd||24,rto:+v.rto||8,rpo:+v.rpo||1,review:TODAY,deps:'To be mapped'});commit()}),
 'bia-review':b=>{const x=bc().bia.find(r=>r.id===b.dataset.id);x.review=TODAY;logIt(x.id,'BIA reviewed.');commit();toast(x.id+' reviewed.')},
 'bia-issue':b=>{const x=bc().bia.find(r=>r.id===b.dataset.id);raise('BIA review',x.id,`Recovery objective gap: ${x.process}`,'High',x.owner,`RTO ${x.rto}h exceeds MTPD ${x.mtpd}h.`,'Control design');commit()},
 'plan-new':()=>openForm('Add continuity plan',[{name:'name',label:'Plan',full:true},{name:'scope',label:'Scope',ph:'e.g. Core banking and DR site'},{name:'owner',label:'Owner',type:'select',options:personOpts(),value:me().name},{name:'freq',label:'Test frequency',type:'select',options:['Quarterly','Semi-annual','Annual'],value:'Annual'}],'Add',v=>{if(!v.name)return 'Name the plan.';bc().plans.push({id:nid(bc().plans,'BCP-'),name:v.name,scope:v.scope||'',owner:v.owner,ver:'0.1',last:'',result:'Not tested',freq:v.freq,status:'Draft'});commit()}),
 'plan-test':b=>{const p=bc().plans.find(x=>x.id===b.dataset.id);openForm('Record test · '+p.id,[{name:'date',label:'Test date',type:'date',value:TODAY},{name:'result',label:'Result',type:'select',options:['Passed','Passed with findings','Failed'],value:'Passed'},{name:'status',label:'Plan status',type:'select',options:['Draft','In review','Approved'],value:p.status}],'Save',v=>{p.last=v.date;p.result=v.result;p.status=v.status;logIt(p.id,'Test recorded: '+v.result);commit()})},
 'fc-export':()=>csv('forge-fincrime-cases.csv',[['ID','Case','Subject','Risk','Opened','Status','Analyst','Value'],...fc().cases.map(c=>[c.id,c.type,c.who,c.risk,c.opened,c.status,c.analyst,c.amount])],'Cases exported as CSV.'),
 'case-new':()=>openForm('New case',[{name:'type',label:'Case type',type:'select',options:['Transaction-monitoring alert','Suspected mule account','Sanctions screening hit','Card / payment fraud','PEP review','Internal fraud']},{name:'who',label:'Subject reference',ph:'e.g. Customer #12345',full:true},{name:'risk',label:'Risk',type:'select',options:['High','Medium','Low']},{name:'analyst',label:'Analyst',type:'select',options:personOpts(),value:me().name},{name:'amount',label:'Value (₹)',type:'number',value:'0'}],'Open case',v=>{if(!v.who)return 'Add a subject reference.';fc().cases.push({id:nid(fc().cases,'AML-',3),type:v.type,who:v.who,risk:v.risk,opened:TODAY,suspicion:'',status:'Open',analyst:v.analyst,amount:+v.amount||0,strFiled:''});commit()}),
 'case-update':b=>{const c=fc().cases.find(x=>x.id===b.dataset.id);openForm('Update · '+c.id,[{name:'status',label:'Status',type:'select',options:['Open','Investigating','Escalated','STR filed','Closed'],value:c.status},{name:'suspicion',label:'Date suspicion concluded (starts STR clock)',type:'date',value:c.suspicion},{name:'analyst',label:'Analyst',type:'select',options:personOpts(),value:c.analyst}],'Save',v=>{c.status=v.status;c.suspicion=v.suspicion;c.analyst=v.analyst;logIt(c.id,'Updated: '+v.status);commit()})},
 'case-str':b=>{const c=fc().cases.find(x=>x.id===b.dataset.id);c.strFiled=TODAY;c.status='STR filed';logIt(c.id,'STR filed with FIU-IND.');commit();toast('STR recorded for '+c.id)},
 'kyc-update':()=>openForm('Update KYC figures',fc().kyc.flatMap(k=>[{name:'d'+k.band,label:k.band+' · reviews due',type:'number',value:String(k.due)},{name:'o'+k.band,label:k.band+' · overdue',type:'number',value:String(k.overdue)}]),'Save',v=>{fc().kyc.forEach(k=>{k.due=+v['d'+k.band]||0;k.overdue=+v['o'+k.band]||0});logIt('KYC','KYC health updated.');commit()}),
 'cmp-new':()=>openForm('Log complaint',[{name:'category',label:'Category',type:'select',options:['Unauthorised transaction','Mis-selling','Charges dispute','Digital service','Loan statement error','Conduct']},{name:'channel',label:'Channel',type:'select',options:['Digital','Branch','Call centre','Email']},{name:'owner',label:'Owner',type:'select',options:personOpts(),value:me().name},{name:'amount',label:'Amount (₹)',type:'number',value:'0'}],'Log complaint',v=>{fc().complaints.push({id:nid(fc().complaints,'CMP-',3),channel:v.channel,category:v.category,received:TODAY,status:'Open',owner:v.owner,amount:+v.amount||0,ombudsman:false});commit()}),
 'cmp-resolve':b=>{const c=fc().complaints.find(x=>x.id===b.dataset.id);c.status='Resolved';logIt(c.id,'Complaint resolved.');commit()},
 'cmp-issue':b=>{const c=fc().complaints.find(x=>x.id===b.dataset.id);raise('Complaint',c.id,`Complaint root cause: ${c.category}`,'Medium',c.owner,`${c.channel} complaint, ${c.category}.`,'Process / procedure');commit()},
 'au-export':()=>csv('forge-audit-plan.csv',[['ID','Audit','Area','Quarter','Risk','Status','Lead','Start','End','Findings','Rating'],...au().plan.map(x=>[x.id,x.title,x.area,x.qtr,x.risk,x.status,x.lead,x.start,x.end,x.findings,x.rating])],'Audit plan exported.'),
 'au-new':()=>openForm('Add audit',[{name:'title',label:'Audit',full:true},{name:'area',label:'Risk area',type:'select',options:[...new Set(risks.map(r=>r.area))]},{name:'risk',label:'Risk',type:'select',options:['High','Medium','Low']},{name:'lead',label:'Lead auditor',type:'select',options:personOpts(),value:me().name},{name:'start',label:'Start',type:'date',value:addDays(TODAY,30)},{name:'end',label:'End',type:'date',value:addDays(TODAY,60)}],'Add',v=>{if(!v.title)return 'Name the audit.';au().plan.push({id:nid(au().plan,'IA-'),title:v.title,area:v.area,qtr:'',risk:v.risk,status:'Planned',lead:v.lead,start:v.start,end:v.end,findings:0,rating:'',fids:[]});commit()}),
 'au-update':b=>{const x=au().plan.find(r=>r.id===b.dataset.id);openForm('Update · '+x.id,[{name:'status',label:'Status',type:'select',options:['Planned','Fieldwork','Reporting','Complete'],value:x.status},{name:'rating',label:'Rating',type:'select',options:['','Satisfactory','Needs improvement','Unsatisfactory'],value:x.rating},{name:'findings',label:'Findings',type:'number',value:String(x.findings)}],'Save',v=>{x.status=v.status;x.rating=v.rating;x.findings=+v.findings||0;logIt(x.id,'Audit updated: '+v.status);commit()})}
});
// ---------------------------------------------------------------- executive tiles
G.xTiles.push(()=>{const as=cy().assets;if(!as.length)return null;const w=as.filter(a=>a.crit&&a.internet);return{key:'cy-exp',l:'Exposed critical assets',v:w.length,f:`${as.reduce((s,a)=>s+a.crit,0)} critical vulns open · NIST CSF avg ${(cy().maturity.reduce((s,m)=>s+m.now,0)/Math.max(1,cy().maturity.length)).toFixed(1)}/4`,k:w.length>1?'red':w.length?'amber':'green',ic:'⌨'}});
G.xTiles.push(()=>{const b=bc();if(!b.plans.length)return null;const u=b.plans.filter(p=>!p.last||dTo(planDue(p))<0);return{key:'bc-gap',l:'Continuity plans untested',v:`${u.length}<span style="font-size:15px;color:#8a95a3"> / ${b.plans.length}</span>`,f:`${b.bia.filter(biaGap).length} process(es) with RTO above MTPD`,k:u.length>1?'red':u.length?'amber':'green',ic:'↻'}});
G.xTiles.push(()=>{if(!G.modOn('fincrime'))return null;const f=fc();if(!f.cases.length)return null;const str=f.cases.filter(c=>caseOpen(c)&&strDue(c)&&dTo(strDue(c))<=3).length,late=f.complaints.filter(c=>cmpOpen(c)&&dTo(cmpDue(c))<0).length;return{key:'fc-risk',l:'Financial-crime deadlines',v:str+late,f:`${str} STR due soon · ${late} complaint(s) past turnaround · ${f.cases.filter(caseOpen).length} open cases`,k:str+late>1?'red':str+late?'amber':'green',ic:'⚖'}});
G.xTiles.push(()=>{const p=au().plan;if(!p.length)return null;const l=p.filter(auLate).length,open=S().issues.filter(i=>i.source==='Audit finding'&&i.status!=='Closed').length;return{key:'au-risk',l:'Audit plan behind schedule',v:l,f:`${open} open audit findings · ${p.filter(x=>x.status==='Complete').length} of ${p.length} audits complete`,k:l>1?'red':l?'amber':'green',ic:'✎'}});
G.metrics['cy-exp']=()=>['Cyber','Cyber exposure','Assets with critical vulnerabilities or control gaps, most urgent first.',cy().assets.filter(a=>assetGaps(a).length).sort((a,b)=>assetGaps(b).filter(x=>x[0]==='red').length-assetGaps(a).filter(x=>x[0]==='red').length).map(a=>({id:a.id,sub:`${a.tier} · ${a.crit} critical / ${a.high} high${a.internet?' · internet-facing':''}${a.mfa?'':' · no MFA'}`,pill:pill(assetGaps(a).some(x=>x[0]==='red')?'urgent':'review',assetGaps(a).some(x=>x[0]==='red')?'red':'amber')}))];
G.metrics['bc-gap']=()=>['Continuity','Continuity gaps','Untested or overdue plans and recovery objectives that are too slow.',[...bc().plans.filter(p=>!p.last||dTo(planDue(p))<0).map(p=>({id:p.id,sub:`${p.name} · ${p.last?'last tested '+fmt(p.last):'never tested'}`,pill:pill(p.last?'overdue':'untested','red')})),...bc().bia.filter(biaGap).map(x=>({id:x.id,sub:`${x.process} · RTO ${x.rto}h vs MTPD ${x.mtpd}h`,pill:pill('RTO gap','red')}))]];
G.metrics['fc-risk']=()=>['Financial crime','Financial-crime and conduct deadlines','STR deadlines, aged cases and late complaints.',[...fc().cases.filter(c=>caseOpen(c)&&(strDue(c)&&dTo(strDue(c))<=3||dTo(addDays(c.opened,30))<0)).map(c=>({id:c.id,sub:`${c.type} · ${strDue(c)?'STR due '+fmt(strDue(c)):'open since '+fmt(c.opened)}`,pill:pill(c.status,'amber')})),...fc().complaints.filter(c=>cmpOpen(c)&&dTo(cmpDue(c))<0).map(c=>({id:c.id,sub:`${c.category} · due ${fmt(cmpDue(c))}`,pill:pill('late','red')}))]];
G.metrics['au-risk']=()=>['Audit','Audit plan exceptions','Late audits and open audit findings.',[...au().plan.filter(auLate).map(x=>({id:x.id,sub:`${x.title} · ${x.status} · report due ${fmt(auEnd(x))}`,pill:pill('behind','red')})),...S().issues.filter(i=>i.source==='Audit finding'&&i.status!=='Closed').map(i=>({id:i.id,sub:`${i.title} · ${i.owner} · due ${fmt(i.due)}`,pill:pill(i.sev,G.sevK(i.sev))}))]];
G.renderAll();
})();
